Adds dynamic filters component
yext/answers-search-ui pull request #105
Opened 2019-07-29 17:40 UTC by Delerme

2019-07-30 20:36 UTC, b1lly requested changes

2019-07-30 20:36 UTC, b1lly commented on src/core/core.js
> +      .verticalQuery(Object.assign({}, searchOptions, { isDynamicFiltersEnabled: this._isDynamicFiltersEnabled }))
why is dynamicFiltersEnabed part of the core? Seems like it should be part of the UI component

2019-07-30 20:36 UTC, b1lly commented on src/core/models/dynamicfilters.js
> +    this.filters = data.filters || [];
jsdoc?

2019-07-30 20:36 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +    }
I'd consider making a filters model that is a wrapper around the `array` filterComponents (e.g. `FitlerComponentCollection`) that expose an interface for add, remove, clear, get, etc.

then you can just do
```
this._filterComponents = new FilterComponentCollection();
```
```
this._filterComponents.clear();
this._filterComponents.remove(c)
this._filterComponents.add(c) // or push if you want to be consistent
```

2019-07-30 20:36 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +      .filter(f => f !== undefined && f !== null && Object.keys(f).length > 0);
neat! Can you expand this logic out so its more legible.

2019-07-30 20:36 UTC, b1lly commented
Is it possible to add tests for some of the model/transformation stuff? Or no?

2019-08-08 18:22 UTC, Delerme commented on src/core/core.js
> +      .verticalQuery(Object.assign({}, searchOptions, { isDynamicFiltersEnabled: this._isDynamicFiltersEnabled }))
`dynamicFiltersEnabled` determines whether or not api requests include `retrieveFacets` or not. We don't want to default to always requesting because retrieving facets is a significant performance hit. 

This property just happens to be controlled by the presence of a UI component, but is totally detached. The only purpose it serves is to optionally fetch more data from the backend, and the ui lib sets it to true in some circumstances

There may be a better name for this property if you have some ideas

2019-08-08 18:22 UTC, Delerme commented on src/core/models/dynamicfilters.js
> +    this.filters = data.filters || [];
done

2019-08-08 18:22 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +    }
hmm maybe. Main issue here is with clearing the old components and I don't think `this._filterComponents.clear()` is that much more clear than `this._filterComponents = []`. Punting for now

2019-08-08 18:22 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +      .filter(f => f !== undefined && f !== null && Object.keys(f).length > 0);
Done

2019-08-12 20:07 UTC, b1lly approved these changes

2019-08-12 20:07 UTC, b1lly commented on src/ui/components/filters/dynamicfilterscomponent.js
> +    );
If someone changes the template, would this break pretty easily? Would using markup syntax make this a little less fragile?

2019-08-12 20:07 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +    }
SGTM.

Just to clarify, I was showing the higher level interface it would expose.

`filterComponents.clear()` would internally iterate on each component, call `c.remove()` and set the value to empty `[]`.

Probably not the best name.... but was just elaborating.

2019-08-12 20:07 UTC, b1lly commented on src/core/core.js
> +      .verticalQuery(Object.assign({}, searchOptions, { isDynamicFiltersEnabled: this._isDynamicFiltersEnabled }))
Yeah, but why is it referencing `this._isDynamicFiltersEnabled`?

Shouldn't it just be provided by searchOptions, which would default to false if not provided?

Yeah, I don't feel strongly about the name but some alternatives: `fetchDynamicFilters` or `retrieveDynamicFilters`.

2019-08-16 19:05 UTC, Delerme commented on src/core/core.js
> +      .verticalQuery(Object.assign({}, searchOptions, { isDynamicFiltersEnabled: this._isDynamicFiltersEnabled }))
once dynamic filters is enabled, it should be disabled, i.e. it should be enabled once at the start if appropriate and then sent with every request. If it were included with searchOptions, you'd have to guarantee every caller of verticalSearch properly set it, which isn't feasible

2019-08-16 19:06 UTC, Delerme commented on src/ui/components/filters/dynamicfilterscomponent.js
> +    );
not sure what you mean but can do in a different commit

2019-08-16 19:06 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +    }
yea seems like premature abstraction but if we add any more manipulations I'll wrap it

2019-08-16 19:07 UTC, merged