Updating autocomplete class naming and styling (#114)
yext/answers-search-ui pull request #119
Opened 2019-07-31 14:49 UTC by aginsberg

2019-07-31 15:40 UTC, Delerme commented
It seems like we should be using either hyphen or camelCase for classes, but not both. Doesn't really matter but seems kind of strange to me. Any thoughts?

2019-07-31 15:58 UTC, aginsberg commented
> It seems like we should be using either hyphen or camelCase for classes, but not both. Doesn't really matter but seems kind of strange to me. Any thoughts?

We try to follow SUIT naming conventions https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md, so .yxt-AutoComplete is the base component, anything followed by a '-' is a descendant, and '--' indicates a modifier. I am trying to use the same naming convention that was used here https://github.com/yext/answers/pull/81/files#diff-9156501bba9bf6edadf5b90e9d3398b1R4

2019-08-01 23:29 UTC, benmcginnis commented
@Delerme yeah, the only thing about this that's weird / doesn't really fit is the name spacing that @b1lly wants the library to have so we potentially can avoid style collisions with clients' css.  But it works.  The convention is basically `.namespace-Module-child` and `.namespace-Module--modifier` . The benefit of adopting this naming convention is that it's very clear what's a module and what's an element, and you can easily separate concerns between modules.

If you're familiar at all with [BEM](http://getbem.com/introduction/), SUIT is basically the same thing, but is easier to type and read.

2019-08-02 15:35 UTC, b1lly requested changes
A few questions about long term organization of code.

2019-08-02 15:35 UTC, b1lly commented on src/ui/sass/modules/_AutoComplete.scss
> +      background-color: black;
do we want to use variables for colors? perhaps creating a `_colors.scss` file that gets imported for use? @benmcginnis

2019-08-02 15:35 UTC, b1lly commented on src/ui/sass/modules/_AutoComplete.scss
> +}
Do you want to remove the dead autocomplete scss code from answers.scss?

2019-08-02 15:35 UTC, b1lly commented on src/ui/sass/modules/_AutoComplete.scss
> +    }
should there be some base file for `fonts`?

2019-08-02 16:11 UTC, aginsberg commented on src/ui/sass/modules/_AutoComplete.scss
> +      background-color: black;
For Pages, we have a single 'variables.scss' file, where we store things like colors, font-weights, etc. Would it make sense for me to add that?

2019-08-02 16:25 UTC, aginsberg commented on src/ui/sass/modules/_AutoComplete.scss
> +}
@b1lly It looks like answers.scss only contains file imports now. Is there a different file you're referring to?

2019-08-02 16:28 UTC, aginsberg commented on src/ui/sass/modules/_AutoComplete.scss
> +    }
By base file, do you mean someplace to store variables like this?

2019-08-02 16:47 UTC, aginsberg commented on src/ui/sass/modules/_AutoComplete.scss
> +      background-color: black;
@b1lly I just pushed a commit that shows what it might look like with a variables.scss file. If we like this way I can refactor the Nav and Searchbar scss files to use this as well

2019-08-02 16:56 UTC, benmcginnis commented on src/ui/sass/modules/_AutoComplete.scss
> +}
Yeah I removed the styles in a previous pr.

2019-08-02 16:57 UTC, benmcginnis commented on src/ui/sass/modules/_AutoComplete.scss
> +    }
@b1lly yes, I was thinking about doing this I just hadn't written my thoughts down yet.  I think we want to handle font styles & colors in a similar way by setting defaults.

2019-08-02 16:57 UTC, benmcginnis commented on src/ui/sass/_variables.scss
> +$font-weight-bold: 700;
I think you want to mark these with `!default` so implementers can override with their own settings and they will take precedence

2019-08-02 17:01 UTC, b1lly commented on src/ui/sass/modules/_AutoComplete.scss
> +}
Oh, woops!

2019-08-02 17:04 UTC, b1lly requested changes

2019-08-02 17:04 UTC, b1lly commented on src/ui/sass/_variables.scss
> +$autocomplete-option-hover-background-color: gray;
If they're autocomplete specific, I don't see harm in defining them at the header of the autocomplete scss. Thoughts @benmcginnis ?

2019-08-02 17:04 UTC, b1lly commented on src/ui/sass/modules/_AutoComplete.scss
> +    }
Yup, I was thinking longer term there'd probably be things for like:

```
_fonts.scss
_colors.scss
_layouts.scss
```
etc. etc.

2019-08-02 17:25 UTC, benmcginnis commented on src/ui/sass/_variables.scss
> +$autocomplete-option-hover-background-color: gray;
I generally like the approach of putting things in their corresponding modules, but I think bootstrap goes with a global variable file for a reason: it's easier for implementors to see all of the variables that they might override.

I don't really feel strongly, though.

2019-08-07 17:16 UTC, benmcginnis commented
@aginsberg I think you need to rebase this on v0.8.0

2019-08-09 17:10 UTC, b1lly approved these changes
Nice :)

2019-08-09 18:07 UTC, merged