Added default analytics and eventtypes and eventoptions for implement…
yext/answers-search-ui pull request #163
Opened 2019-08-23 13:05 UTC by creotutar

…ation specific events (#157)

2019-08-23 14:21 UTC, Delerme commented on src/ui/templates/filters/filterbox.hbs
> +              {{#if applyEventPptions}} data-eventoptions='{{applyEventOptions}}'{{/if}}>
typo

2019-08-26 14:11 UTC, Delerme approved these changes

2019-08-26 14:36 UTC, b1lly requested changes
I'm not sure I understand what this is doing here, and i'm not sure this is the right "generic" solution.
Correct me if i'm wrong, but what you did here was bake variables in the template, from which you plan to use dataTransform to populate?

That is not the right approach. I'd expect each templates default data properties piped in through as core data.

2019-08-26 14:41 UTC, benmcginnis commented
Billy, when we discussed this it seemed like you weren't interested in
having us make that change.  In my mind, the templates shouldn't need to
know the event options at all, but this is what we could do in the short
term, and we have to have something for launch.

On Mon, Aug 26, 2019 at 10:36 AM Billy Bastardi <notifications@github.com>
wrote:

> *@b1lly* requested changes on this pull request.
>
> I'm not sure I understand what this is doing here, and i'm not sure this
> is the right "generic" solution.
> Correct me if i'm wrong, but what you did here was bake variables in the
> template, from which you plan to use dataTransform to populate?
>
> That is not the right approach. I'd expect each templates data the
> properties piped in through as core data.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/yext/answers/pull/163?email_source=notifications&email_token=AAJGVKPJAY777IN2OZNLLX3QGPTAHA5CNFSM4IO7NUR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCCVNHKY#pullrequestreview-279630763>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJGVKPCNVD6XIAWVNHJ2KTQGPTAHANCNFSM4IO7NURQ>
> .
>

2019-08-26 14:42 UTC, benmcginnis commented
It's also what Christian & Julian discussed in their meeting for what we
were going to do for analytics in the short term.

On Mon, Aug 26, 2019 at 10:40 AM Ben McGinnis <bmcginnis@yext.com> wrote:

> Billy, when we discussed this it seemed like you weren't interested in
> having us make that change.  In my mind, the templates shouldn't need to
> know the event options at all, but this is what we could do in the short
> term, and we have to have something for launch.
>
> On Mon, Aug 26, 2019 at 10:36 AM Billy Bastardi <notifications@github.com>
> wrote:
>
>> *@b1lly* requested changes on this pull request.
>>
>> I'm not sure I understand what this is doing here, and i'm not sure this
>> is the right "generic" solution.
>> Correct me if i'm wrong, but what you did here was bake variables in the
>> template, from which you plan to use dataTransform to populate?
>>
>> That is not the right approach. I'd expect each templates data the
>> properties piped in through as core data.
>>
>> —
>> You are receiving this because your review was requested.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/yext/answers/pull/163?email_source=notifications&email_token=AAJGVKPJAY777IN2OZNLLX3QGPTAHA5CNFSM4IO7NUR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCCVNHKY#pullrequestreview-279630763>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AAJGVKPCNVD6XIAWVNHJ2KTQGPTAHANCNFSM4IO7NURQ>
>> .
>>
>

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/filters/filterbox.hbs
> +              {{#if applyEventType}} data-eventtype="{{applyEventType}}"{{/if}}
I think this should be
```
{{if isFacet}}
  data-eventtype="FACETING"
{{else}}
  data-eventtype="FILTERING"
{{/if}}

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/filters/filterbox.hbs
> +              {{#if applyEventOptions}} data-eventoptions='{{applyEventOptions}}'{{/if}}>
I think we should remove this, since there are no options in the spec.

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +       {{#if eventType}} data-eventtype="{{eventType}}"{{/if}}
I think this should always be `data-eventtype="VERTICAL_SEARCHER_TAB"` based on the spec

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +       {{#if eventOptions}} data-eventoptions='{{eventOptions}}'{{/if}}>
I think we should remove this, since there are no options in the spec.

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/results/resultsitem.hbs
> +             {{#if titleEventOptions}} data-eventoptions='{{titleEventOptions}}'{{/if}}>
@b1lly how should we get the vertical config id & searcher type here? If we work out how we want to pass that in we can remove the need for the implementor doing anything.  Otherwise they need to fill this out in transform data.  The entityId is the only thing we get on the model right now.

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/results/resultssectionheader.hbs
> +       {{#if viewAllEventType}} data-eventtype="{{viewAllEventType}}"{{/if}}
this should always be `data-eventtype="VERTICAL_SEARCHER_VEIW_ALL"` based on the spec.

@b1lly same question on how do you want to pass the vertical config id to this as that's the only eventoption?

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/results/resultssectionheader.hbs
> +           {{#if filteringEventOptions}} data-eventoptions='{{filteringEventOptions}}'{{/if}}>
same vertical config id question @b1lly

2019-08-26 15:40 UTC, benmcginnis commented on src/ui/templates/filters/filterbox.hbs
> +              {{#if applyEventType}} data-eventtype="{{applyEventType}}"{{/if}}
I think we would want to determine the value of isFacet [here](https://github.com/yext/answers/blob/71fbeae7c59f83226229f216f3852ee02ae5d539/src/ui/components/filters/filterboxcomponent.js#L19), though I'm not sure exactly how we would

2019-08-26 17:34 UTC, benmcginnis commented on src/ui/templates/results/resultsitem.hbs
> +             {{#if titleEventOptions}} data-eventoptions='{{titleEventOptions}}'{{/if}}>
I think we can get it via _config._parentOpts.verticalConfigId if we just make sure that's set in the config we pass in.

2019-08-26 17:34 UTC, benmcginnis commented on src/ui/templates/results/resultsitem.hbs
> +             {{#if titleEventOptions}} data-eventoptions='{{titleEventOptions}}'{{/if}}>
same with searcher type if it's not available elsewhere

2019-09-06 17:38 UTC, b1lly approved these changes

2019-09-06 17:38 UTC, b1lly commented on src/ui/components/navigation/navigationcomponent.js
> +  }
what's this being used for?

2019-09-06 17:45 UTC, benmcginnis commented on src/ui/components/navigation/navigationcomponent.js
> +  }
spec says we need to send this for clicks on the nav tabs.

2019-09-06 17:48 UTC, merged