Add "More" dropdown functionality to navbar
yext/answers-search-ui pull request #226
Opened 2019-09-16 18:06 UTC by Delerme

Posted demo link in slack, let me know if you need the link again

2019-09-16 18:08 UTC, Delerme commented
Left the styling pretty simple so you can apply some of your better stylings @benmcginnis which we can merge back in a separate commit

2019-09-16 18:43 UTC, benmcginnis reviewed
Do you want to just grab the stylings from #167  ?

2019-09-16 18:43 UTC, benmcginnis commented on src/ui/components/navigation/navigationcomponent.js
> +    this.dropdownIcon = config.dropdownIcon || null;
should probably default to "kabob"

2019-09-16 18:43 UTC, benmcginnis commented on src/ui/components/navigation/navigationcomponent.js
> +    const moreButton = DOM.query(this._container, '.yxt-Nav-more-button');
for performance reasons, I recommend not making any dom updates inside of a resize callback, but rather doing them inside of requestAnimationFrame.  Not sure why this technique isn't up on MDN anymore but here's the wayback machine link: https://web.archive.org/web/20190116150203/https://developer.mozilla.org/en-US/docs/Web/Events/resize#requestAnimationFrame

2019-09-16 18:48 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +    {{#each tabs}}
should we do this in setState / updateState? moving the tabs between more & not more.  Not sure if that would blink or not but if you use requestAnimation frame above it probably would work

2019-09-16 19:04 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +      <img src="{{dropdownIcon}}" class="yxt-Nav-more-icon" alt="More Navigation Links">
this should probably use the icon component, so it would be:
```
<div class="yxt-Nav-moreIconWrapper">
      <div class="yxt-Nav-moreIcon"
      data-component="IconComponent"
      data-opts='{"iconName": "{{#if dropdownIcon}}{{dropdownIcon}}{{/if}}"}'
      data-prop="icon"></div>
    </div>
```

2019-09-16 20:19 UTC, Delerme reviewed
Added most of the styles from the other PR too

2019-09-16 20:19 UTC, Delerme commented on src/ui/components/navigation/navigationcomponent.js
> +    this.dropdownIcon = config.dropdownIcon || null;
as in all implementations should default to kabob? Currently by default it shows "more"

2019-09-16 20:19 UTC, Delerme commented on src/ui/components/navigation/navigationcomponent.js
> +    const moreButton = DOM.query(this._container, '.yxt-Nav-more-button');
Added a 100ms debounce

2019-09-16 20:19 UTC, Delerme commented on src/ui/templates/navigation/navigation.hbs
> +    {{#each tabs}}
Yea I'd like to but that means untangling the tab reordering stuff. I think I'll do that in a separate commit

2019-09-16 20:19 UTC, Delerme commented on src/ui/templates/navigation/navigation.hbs
> +      <img src="{{dropdownIcon}}" class="yxt-Nav-more-icon" alt="More Navigation Links">
done

2019-09-17 17:13 UTC, benmcginnis commented on src/ui/components/navigation/navigationcomponent.js
> +    this.dropdownIcon = config.dropdownIcon || null;
the `kabob` icon name is the name of the three vertical dots icon that you see next to "more" [here](https://answers.yext.com/), the idea is that you show the text _and_ the icon.

2019-09-17 17:16 UTC, benmcginnis commented on src/ui/sass/modules/_Nav.scss
> +  &-collapsed-items
do you mind camel casing module descendant selectors? e.g. `.yxt-Nav-collapsedItems` an descendant selector being a child of a module. https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md#ComponentName-descendentName

2019-09-17 17:50 UTC, benmcginnis commented
Also same request that this go into an 8.x version, please.  I'd prefer not to open up the 0.9.0 can of worms on the existing implementations.

2019-09-17 18:01 UTC, Delerme commented
Yea I put this one on 0.9.0 since it's component changes, and affects the implementation. I guess if we need it for current implementations I can backport it. Is the idea that we stay on 0.8.x until onward?

2019-09-17 18:05 UTC, benmcginnis commented
I'd like to get all of the "core" functionality that we've built into the implementations into an 8.x version so that we can just lock the implementations on that until we're ready to test the 9.0 changes and ensure we don't have any regressions.

2019-09-17 18:06 UTC, Delerme commented
Gotcha, what's left on that list after nav?

2019-09-17 18:08 UTC, benmcginnis commented
Nothing, though calls to action would be nice, I hadn't opened a PR because it's still wip, but I can push it up if you're interested in taking a look.

2019-09-17 18:09 UTC, Delerme commented
Those are components too right? I'd prefer to put it on 0.9.0

Alright I'll backport this then

2019-09-17 18:24 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +  <ul class="yxt-Nav-expanded-items">
I don't think we actually want these two side by side `<ul>` elements, and it would be better to use this style from #167 https://github.com/yext/answers/pull/167/files#diff-88c35f3580ae030fbd06d720c842fe1bR9 . this will ensure the user can tab through with their keyboard properly

2019-09-17 18:26 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +  <ul class="yxt-Nav-expanded-items">
the only additional part that we would need for all the styling to work is changing the class on the nav-item when it gets moved to the dropdown, as done here: https://github.com/yext/answers/pull/167/files#diff-011a08758bbc7f4e509ccdcdd4cb335fR338

2019-09-17 19:09 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +  <button class="yxt-Nav-more-button {{#if static}}yxt-Nav-hidden{{/if}}">
this should also have aria-controls and aria-expanded attributes, where the aria-controls points to the ID of the container of the hidden nav items and the aria-expanded attribute is "false" when it's collapsed and "true" when it's open.

2019-09-17 19:49 UTC, Delerme reviewed
Backported to 0.8.5. Made some tiny template changes so let me know if you see anything weird on your end

2019-09-17 19:49 UTC, Delerme commented on src/ui/components/navigation/navigationcomponent.js
> +    this.dropdownIcon = config.dropdownIcon || null;
Ah we want both, gotcha, set.

2019-09-17 19:49 UTC, Delerme commented on src/ui/sass/modules/_Nav.scss
> +  &-collapsed-items
Ended up removing this but will keep in mind

2019-09-17 19:49 UTC, Delerme commented on src/ui/templates/navigation/navigation.hbs
> +  <ul class="yxt-Nav-expanded-items">
Copied over all the template and styling stuff from your PR

2019-09-17 19:49 UTC, Delerme commented on src/ui/templates/navigation/navigation.hbs
> +  <button class="yxt-Nav-more-button {{#if static}}yxt-Nav-hidden{{/if}}">
Added aria stuff

2019-09-18 15:33 UTC, benmcginnis commented
@Delerme I think you need to rebase this and drop the 9.0 commits

2019-09-18 15:46 UTC, Delerme commented
oof yea rebasing back and forth caught some stragglers, fixed

2019-09-18 16:14 UTC, benmcginnis commented on src/ui/templates/navigation/navigation.hbs
> +    <div class="yxt-Nav-moreIconWrapper">
this is probably duplicative in reality, of the span below it. Also, I divs are invalid inside buttons which I realized after doing some audits.

2019-09-18 16:14 UTC, benmcginnis commented on src/ui/sass/modules/_Nav.scss
> +    margin-right: 7px;
these styles can live in the moreIcon selector, I think

2019-09-19 23:06 UTC, b1lly requested changes
Here's how I think i'd approach this problem:

1. Create a `moreTabs` property on the data model that contains the tabs to be rendered under "more"
2. Template renders using the `tabs` and `moreTabs` data

To handle resizing:
1. When resize happens, compute the total number of "tabs" that can fit from the DOM.
2. Using the total number of "tabs" that can fit, re-generate `tabs` and `moretabs`.
3. Set State with new data to trigger re-render.

That would eliminate all the DOM manipulation we're doing for 'refitNav' and hopefully reduce some of that complexity here.

Thoughts?

2019-09-19 23:06 UTC, b1lly commented on src/core/models/autocompletedata.js
> +    }
is this related to nav?

2019-09-19 23:06 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +      showApplyButton: !this._searchOnChange
^

2019-09-19 23:06 UTC, b1lly commented on src/ui/components/navigation/navigationcomponent.js
> + * The debounce duration for resize events
Can you describe the purpose of this in the comment?

2019-09-23 14:28 UTC, Delerme commented on src/ui/templates/navigation/navigation.hbs
> +    <div class="yxt-Nav-moreIconWrapper">
deleted

2019-09-23 14:28 UTC, Delerme commented on src/ui/sass/modules/_Nav.scss
> +    margin-right: 7px;
done

2019-09-23 14:28 UTC, Delerme commented on src/core/models/autocompletedata.js
> +    }
no you were seeing old commit because this pr became stale, updated

2019-09-23 14:28 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +      showApplyButton: !this._searchOnChange
no you were seeing old commit because this pr became stale, updated

2019-09-23 14:29 UTC, Delerme commented on src/ui/components/navigation/navigationcomponent.js
> + * The debounce duration for resize events
resize events can trigger many times a second (as the user drags the window), this makes it so we only really do all refitting when the browser size has settled (the user has stopped dragging)

2019-09-23 14:31 UTC, Delerme commented
As mentioned on one of Ben's comments, I wanted to make it based on state, but that would require tangling with all of the taborder logic which is currently tightly coupled to setState. Since this is needed for existing implementations, I figured this was factored well enough to be moved to stateful when we start rewriting all the components

2019-09-23 19:05 UTC, b1lly commented
> As mentioned on one of Ben's comments, I wanted to make it based on state, but that would require tangling with all of the taborder logic which is currently tightly coupled to setState. Since this is needed for existing implementations, I figured this was factored well enough to be moved to stateful when we start rewriting all the components

@Delerme  How long would it take to refactor this to be based on state? Also, @benmcginnis what is the expected timeline/need for this component being in the library?

If it's urgent, i'm ok merging this in now to unblock them and make a high priority item to fix it. I'd prefer this stateful issue to be resolved before this story is called complete.

2019-09-23 19:10 UTC, Delerme commented
Better part of a week, and I'd have port it _back_ to 0.9.0 for the component changes (which is fine, but it just sucks that I wasted a bunch of time porting to 8.x because we needed it soon, and will then have to basically rewrite the component from scratch in 0.9.0). I know we don't plan on bringing in preact anytime soon, but I think we should save rewriting this component until then, so we don't lose x days to redoing it now, just to again redo it later in preact. I think there are more pressing components like autocomplete which has super flaky keyboard and mouse support that we should rewrite before onward for compliance. In this nav case it seems like a refactor would be nice to have, but not a pressing concern

2019-09-23 20:17 UTC, benmcginnis commented
I'd like to have this done so we can pin the 10 implementations onto a
reliable version of the library.

On Mon, Sep 23, 2019 at 3:10 PM Julian Delerme <notifications@github.com>
wrote:

> Better part of a week, and I'd have port it *back* to 0.9.0 for the
> component changes (which is fine, but it just sucks that I wasted a bunch
> of time porting to 8.x because we needed it soon, and will then have to
> basically rewrite the component from scratch in 0.9.0). I know we don't
> plan on bringing in preact anytime soon, but I think we should save
> rewriting this component until then, so we don't lose x days to redoing it
> now, just to again redo it later in preact. I think there are more pressing
> components like autocomplete which has super flaky keyboard and mouse
> support that we should rewrite before onward for compliance. In this nav
> case it seems like a refactor would be nice to have, but not a pressing
> concern
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yext/answers/pull/226?email_source=notifications&email_token=AAJGVKPO4SSAPCCCQ22Y7GTQLEIDXA5CNFSM4IXFQ2V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7L6EDA#issuecomment-534241804>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJGVKM2NSXRXAUEDOHCQEDQLEIDXANCNFSM4IXFQ2VQ>
> .
>

2019-09-23 20:17 UTC, benmcginnis commented
And eliminate prototype branch.

On Mon, Sep 23, 2019 at 4:17 PM Ben McGinnis <bmcginnis@yext.com> wrote:

> I'd like to have this done so we can pin the 10 implementations onto a
> reliable version of the library.
>
> On Mon, Sep 23, 2019 at 3:10 PM Julian Delerme <notifications@github.com>
> wrote:
>
>> Better part of a week, and I'd have port it *back* to 0.9.0 for the
>> component changes (which is fine, but it just sucks that I wasted a bunch
>> of time porting to 8.x because we needed it soon, and will then have to
>> basically rewrite the component from scratch in 0.9.0). I know we don't
>> plan on bringing in preact anytime soon, but I think we should save
>> rewriting this component until then, so we don't lose x days to redoing it
>> now, just to again redo it later in preact. I think there are more pressing
>> components like autocomplete which has super flaky keyboard and mouse
>> support that we should rewrite before onward for compliance. In this nav
>> case it seems like a refactor would be nice to have, but not a pressing
>> concern
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/yext/answers/pull/226?email_source=notifications&email_token=AAJGVKPO4SSAPCCCQ22Y7GTQLEIDXA5CNFSM4IXFQ2V2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7L6EDA#issuecomment-534241804>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AAJGVKM2NSXRXAUEDOHCQEDQLEIDXANCNFSM4IXFQ2VQ>
>> .
>>
>

2019-09-23 21:48 UTC, Delerme commented
@b1lly

2019-09-24 02:12 UTC, b1lly commented
Ok. merge it in! 

Lets make a separate item to fix the stateful issue. I want to try to be more proactive with tech debt instead of burying ourselves further.

2019-09-24 02:58 UTC, merged

2019-09-25 17:34 UTC, benmcginnis commented
@b1lly & @Delerme there's one bug with this that I had mentioned before but doesn't look like it got fixed.  On mobile the "more" dropdown appears centered on the page rather than aligned with the "more" button".  I also think the more button should probably be aligned to the right side.

![Screen Shot 2019-09-25 at 1 33 01 PM](https://user-images.githubusercontent.com/1206953/65625038-0c3faa00-df99-11e9-9794-51baa00df26b.png)

2019-09-25 17:42 UTC, benmcginnis commented
Oh, also, setting the "static" key causes side-scrolling
![Screen Shot 2019-09-25 at 1 42 10 PM](https://user-images.githubusercontent.com/1206953/65625706-5d9c6900-df9a-11e9-95a7-fe9f39fae8cb.png)

2019-09-25 17:44 UTC, benmcginnis commented
And the more button is still in the DOM if you set "static", so it the nav doesn't take up the full width if you set "overflow: hidden"

2019-09-25 18:52 UTC, Delerme commented
Made the changes here: https://github.com/yext/answers/pull/247