Add IE bundle
yext/answers-search-ui pull request #240
Opened 2019-09-18 21:35 UTC by Delerme

2019-09-18 21:36 UTC, Delerme commented
IE still has one issue with this line
`	    var e = new Event(event, Object.assign({`
which prevents autocomplete from working, but I was able to search stuff and see results

2019-09-18 21:41 UTC, b1lly requested changes
seems solid. what you mean by there is still an IE bug?

@benmcginnis are you aware of that, or know the proper resolution there?

2019-09-18 21:41 UTC, b1lly commented on conf/gulp-tasks/library.gulpfile.js
> +  series(bundle, legacyBundle, minifyJS, minifyLegacy),
minor nit, you can probably move legacyBundle and minifyLegacy to a separate series right?

2019-09-18 21:47 UTC, Delerme commented on conf/gulp-tasks/library.gulpfile.js
> +  series(bundle, legacyBundle, minifyJS, minifyLegacy),
done

2019-09-19 18:26 UTC, benmcginnis approved these changes

2019-09-19 18:26 UTC, benmcginnis commented on conf/gulp-tasks/library.gulpfile.js
> +        if (!Element.prototype.matches) { // Element.matches polyfill from MDN
you might want to create a polyfills.js file to hold all of these and then do a prepend `import polyfills` that way it will be a little nicer to update

2019-09-19 18:28 UTC, Delerme commented on conf/gulp-tasks/library.gulpfile.js
> +        if (!Element.prototype.matches) { // Element.matches polyfill from MDN
agreed, punting til I have better internet and don't have to wait 3 seconds between key presses

2019-09-19 18:28 UTC, merged