Support did you mean in ui
yext/answers-search-ui pull request #253
Opened 2019-09-26 18:52 UTC by bwangYext

2019-09-26 21:51 UTC, Delerme reviewed
Nice, can you also update the README in root

2019-09-26 21:51 UTC, Delerme commented on src/core/models/spellcheck.js
> +    /**
new line above

2019-09-26 21:51 UTC, Delerme commented on src/ui/components/search/spellcheckcomponent.js
> + * provided from speelling correction.
typo

2019-09-26 21:51 UTC, Delerme commented on src/ui/components/search/spellcheckcomponent.js
> +  init (opts) {
Is this needed? The superclass one should get called automatically

2019-09-26 21:51 UTC, Delerme commented on src/ui/components/search/spellcheckcomponent.js
> +    return super.setState(Object.assign(data, {
Object.assign modifies the first argument, so to avoid doing that pop in `{}` as the first argument so it creates a new object

2019-09-27 17:12 UTC, b1lly requested changes
Nice start dude :)

2019-09-27 17:12 UTC, b1lly commented on src/core/models/spellcheck.js
> +    this.correctedQuery = data.correctedQuery || null;
is this the suggestedQuery?

2019-09-27 17:12 UTC, b1lly commented on src/ui/components/search/spellcheckcomponent.js
> +  }
is it possible to generate this from the core and then be part of the core spellcheck model?

2019-09-27 17:12 UTC, b1lly commented on src/ui/components/search/spellcheckcomponent.js
> +  }
same question, can this be part of the core model? or is it influenced by component configuration?

2019-09-27 18:09 UTC, bwangYext commented on src/core/models/spellcheck.js
> +    /**
Done

2019-09-27 18:09 UTC, bwangYext commented on src/ui/components/search/spellcheckcomponent.js
> + * provided from speelling correction.
Done

2019-09-27 18:10 UTC, bwangYext commented on src/ui/components/search/spellcheckcomponent.js
> +  init (opts) {
Removed.

2019-09-27 18:10 UTC, bwangYext commented on src/ui/components/search/spellcheckcomponent.js
> +    return super.setState(Object.assign(data, {
Not needed after moving to model.

2019-09-27 18:11 UTC, bwangYext commented on src/core/models/spellcheck.js
> +    this.correctedQuery = data.correctedQuery || null;
Yes, the response field name is called corrected query.

2019-09-27 18:11 UTC, bwangYext commented on src/ui/components/search/spellcheckcomponent.js
> +  }
Done.

2019-09-27 18:11 UTC, bwangYext commented on src/ui/components/search/spellcheckcomponent.js
> +  }
Done.

2019-09-27 18:21 UTC, b1lly requested changes

2019-09-27 18:21 UTC, b1lly commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
So one thing the core should never have is a dependency on the DOM.

For instance, we shouldn't be accessing "window" directly here. Is it possible to get the existing URL from the  `storage`, and provide it to the model as input that it can use to build the new URL?

2019-09-27 19:13 UTC, Delerme commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
As you said, the core shouldn't really have a dependency on the DOM. Is there a strong reason to go through the trouble of passing around the URL through core? It seems to make more sense just keeping the logic in the component

2019-09-27 20:24 UTC, bwangYext commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
Passed params to the model. Do we need to replace !, '. (, ) as SearchParams.encode() does?

2019-09-27 20:29 UTC, b1lly commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
The base URL, or the url params string? I think in an ideal world there would be a single source of truth that powers all the data for the application, which includes data for the URL and URL params. 

In that world, the `storage` would be the thing that contains all that information-- which would eliminate the need for it to be "passed around". 

I think it's time to revisit the storage as a whole. I'll setup a meeting to get a brain storming sessions started.

2019-09-30 14:17 UTC, Delerme commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
@b1lly in the short term is it fine to keep the url logic in the component? It seems very specific to that component and if we later revisit storage it won't be too difficult to move over

2019-09-30 15:39 UTC, b1lly commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
I'm open to moving it, but what makes you feel that the data for the view model should be generated in the component instead of being part of the storage? 

For me, keeping the core view models and their data part of the core feels correct. Part of the purpose of the core is to encapsulate the transformation logic for models, and to provide the core models that are needed to power the UI.

I also think it's better for testability and robustness... And if someone were to ever build their own UI components, they would already have access to the proper models that power the view.

I agree that it hasn't always been a consistent practice across our components, but I think that's mostly when configuration from the UI has to impact the data in the component.

2019-09-30 15:48 UTC, Delerme commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
Yea it sounds like we have two different ideas for storage

I think storage should be used exclusively for global app knowledge. Kind of like how redux is used in other applications. The data there can power components, but not all components and state should be powered by storage. I.e. it's just used for shared knowledge and components explicitly use it when needed, but they should not automatically be powered by storage. Therefore, if the knowledge (in this case the url) is not needed elsewhere it should not be in storage.

I think your idea of storage is a single source of truth for app state that powers all the components. I.e. everything that components need should go into storage, which automatically triggers rerenders on the components. Therefore, since this url is needed for rendering, it should be in storage.

Definitely think it's worth stepping back and investigating our architecture for the future, but I'd argue it should not block this PR and the url logic should just stay in the component for now.

2019-09-30 18:59 UTC, Delerme commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
As discussed, let's leave in the component for this PR while we revisit the higher level storage architecture

@bwangYext go ahead and keep the url creation logic in the component like you first had

2019-09-30 19:56 UTC, bwangYext commented on src/core/models/spellcheck.js
> +    return window.location.href.split('?')[0] + '?' + params.toString();
@Delerme @b1lly Moved back to component.

2019-09-30 19:58 UTC, Delerme commented on src/core/core.js
> +      .then(response => SearchDataTransformer.transformVertical(response, this._fieldFormatters, this.persistentStorage.getAll()))
can these persistenststorage calls be removed now?

2019-09-30 19:58 UTC, Delerme commented on src/core/search/searchdatatransformer.js
> +  static transform (data, urls = {}, formatters, params) {
params is not needed now right?

2019-09-30 20:19 UTC, bwangYext commented on src/core/search/searchdatatransformer.js
> +  static transform (data, urls = {}, formatters, params) {
cleaned up.

2019-10-01 14:37 UTC, Delerme approved these changes

2019-10-01 15:36 UTC, b1lly approved these changes
LGTM

2019-10-01 15:36 UTC, b1lly commented on src/ui/components/search/spellcheckcomponent.js
> +  }
I don't think it matters too much for this function since SearchParams is technically a DOM API dependency, but just for context, one good practice that is worth following is to always "provide" the input that is being operated on.

For instance, instead of "looking up the URL string" from the DOM as part of the function, you provide it to the function.

e.g.
```
_buildRedirectQueryUrl (urlString, query, type) { ... }
```

Then to use it:
```
_buildRedirectQueryUrl(window.location.search.substring(1), ...);
```
That enables you to write unit tests on your helper method without the DOM dependency.

Again, since SearchParams is technically a DOM dependency, I wouldn't worry too much here. But just for general context.

2019-10-01 15:42 UTC, merged