Add sample Answers app
yext/answers-search-ui pull request #275
Opened 2019-10-07 22:32 UTC by data-enabler

![Screen Shot 2019-10-08 at 7 36 48 PM](https://user-images.githubusercontent.com/1616815/66441073-56964180-ea03-11e9-9fd4-58b61f8a481b.png)
![Screen Shot 2019-10-08 at 7 37 23 PM](https://user-images.githubusercontent.com/1616815/66441076-5a29c880-ea03-11e9-9586-198a93dfccb3.png)
![Screen Shot 2019-10-08 at 7 37 34 PM](https://user-images.githubusercontent.com/1616815/66441078-5c8c2280-ea03-11e9-9e64-1830bda5e44d.png)

2019-10-08 15:39 UTC, b1lly requested changes
SAVAGE!

2019-10-08 15:39 UTC, b1lly commented on sample-app/public/app.js
> +  } = config;
Style nit:

Lets try to be consistent with our declarations
```
const config = {
   ..
}
```

2019-10-08 15:39 UTC, b1lly commented on sample-app/public/app.js
> +  };
new line

2019-10-08 15:39 UTC, b1lly commented on sample-app/public/app.js
> +/* eslint-env es6 */
I don't think we use eslint?

2019-10-08 15:39 UTC, b1lly commented on sample-app/public/style.css
> +}
I'd prefer if we kept the default styling, and baked this type of stuff into the sdk based on the UX mocks.

It's not a big deal for now.

2019-10-08 15:39 UTC, b1lly commented on sample-app/index.js
> +    .catch(console.error);
Minor nit: can we just push both operations into helpers?

And/or move the templates to static files, instead of inlined? It's fine for them to be ES6 templates in the short-term, but I can imagine cases more long-term where keeping the templating language consistent (e.g. handlebars) would be beneficial.

```
writeFile('index.html', generateUniversalHtml(config))
  .catch(console.error);

writeFile('vertical.html', generateVerticalHtml(config))
  .catch(console.error);
```

2019-10-08 22:34 UTC, data-enabler commented on sample-app/public/app.js
> +  } = config;
Not sure what you mean here. Are you just suggesting that I don't use object destructuring?

2019-10-08 22:34 UTC, data-enabler commented on sample-app/public/app.js
> +  };
oops

2019-10-08 22:34 UTC, data-enabler commented on sample-app/public/app.js
> +/* eslint-env es6 */
`semistandard` is just a set of configuration options for ESLint.
However, I think the issue I was dealing with here was that my IDE is using the default ESLint config because this repo doesn't have its own eslintrc.

Will remove.

2019-10-08 22:34 UTC, data-enabler commented on sample-app/public/style.css
> +}
I'll trim this down the the minimum required to actually look like a webpage.

2019-10-08 22:35 UTC, data-enabler commented on sample-app/index.js
> +    .catch(console.error);
Not a problem; I was on the fence about making these helpers actually.

2019-10-08 23:49 UTC, b1lly requested changes
Minor templates file name changes. Otherwise LGTM.

2019-10-08 23:49 UTC, b1lly commented on sample-app/index.js
> +  fs.readFileSync('./metadata.handlebars', 'utf8')
for consistency, can we just name all the handlebars templates *.hbs?

2019-10-09 18:58 UTC, data-enabler commented on sample-app/index.js
> +  fs.readFileSync('./metadata.handlebars', 'utf8')
done

2019-10-09 23:09 UTC, b1lly approved these changes

2019-10-10 00:54 UTC, merged