Pretty print answers errors, add debug option
yext/answers-search-ui pull request #285
Opened 2019-10-14 19:43 UTC by Delerme

When debug is true, ugly print errors

2019-10-14 21:39 UTC, b1lly requested changes

2019-10-14 21:39 UTC, b1lly commented on src/answers-umd.js
> +    window.addEventListener('unhandledrejection', printError);
Can we move this to a helper? Or better yet, into the ErrorReporter implementation?

If the ErrorReporter is mainly to be a networking an abstraction, i'd suggest creating a separate ErrorReporting implementation that encapsulates this DOM integration and uses the ErrorReportingApi for sending data.

That way lines 132-153 are all encapsulated in the implementation itself.

2019-10-15 18:40 UTC, Delerme commented on src/answers-umd.js
> +    window.addEventListener('unhandledrejection', printError);
done

2019-10-15 22:21 UTC, b1lly requested changes
Mmm... that looks so much better!

2019-10-15 22:21 UTC, b1lly commented on src/answers-umd.js
> +    window.addEventListener('unhandledrejection', e => this._errorReporter.report(e.error));
I'd consider these DOM dependencies to be part of the "ErrorReporting" implementation. Thoughts?

2019-10-16 14:35 UTC, Delerme commented on src/answers-umd.js
> +    window.addEventListener('unhandledrejection', e => this._errorReporter.report(e.error));
done

2019-10-16 16:28 UTC, b1lly approved these changes

2019-10-16 16:28 UTC, merged