Mock services
yext/answers-search-ui pull request #317
Opened 2019-10-22 02:23 UTC by data-enabler

Was a bit confused by the exports in `core/index.js`; Should `answers-umd` only use exports from this file?

2019-10-22 02:30 UTC, data-enabler commented
Also, names aren't the best because I chose not to rename the existing files to avoid merge conflict nightmares

2019-10-25 17:17 UTC, b1lly requested changes
Savage.

Two minor comments.

Otherwise, code organization discussion:

I was thinking we should organize the packages like so:

core/services/*[interfaces]
core/infra/*[implementations]

Services would be named e.g. SearchService

Implementation would be named: HttpSearchService, MockSearchService

Or something like that? Is there anything we can learn from the way we organize our java code that might be applicable here?

2019-10-25 17:17 UTC, b1lly commented on src/answers-umd.js
> +      });
This works, alternatively

const services = config.mock ? this.getMockServices() : this.getServices();


```
// example getServices()
// note, this can probably just be a literal unless we wanted to require certain services to be constructed
return Services({
  searchService: new SearchApi(),
  errorReporter: new ErrorReporter(),
  analyticsReporter: new AnalyticsReporter()
  ...
})

// example getMockServices()
return Services({
  searchService: new MockSearchService()
  errorReporter: new ConsoleErrorReporter(),
  analyticsReporter: NoopAnalyticsReporter()
  ...
})

```

And then we'd just reference the services object throughout the code instead of having the mock configuratino check sprinkled everywhere:

```
// usage
services.searchService;
```

2019-10-25 17:17 UTC, b1lly commented on src/answers-umd.js
> +      : new SearchApi({
I think you mentioned this in the comments, but how come we didn't update this to `SearchService` from the SearchAPI?

2019-10-29 18:10 UTC, data-enabler commented on src/answers-umd.js
> +      : new SearchApi({
Well `SearchService` is the name of the interface, so it would get renamed to `ApiSearchService`. Yeah, like I mentioned before, I avoided renaming the classes in this commit because it made merge more likely and annoying to deal with and also messed with Git history for the classes where the interface takes the name that the implementation was using.

I figure the names can be renamed in a separate commit and it'll be less disruptive.

2019-10-30 21:50 UTC, data-enabler commented on src/answers-umd.js
> +      });
Good idea. Only problem is that AnalyticsReporter depends on Core, which depends on the rest of the services, so I've left it out for now.

Moved the service interfaces to `services/`, but held of on moving the other files for the same merge-conflict and git-history reasons I gave below.

2019-10-31 19:33 UTC, b1lly approved these changes

2019-10-31 19:33 UTC, b1lly commented on src/answers-umd.js
> +      questionAnswerService: this._services.questionAnswerService
is there an disadvantage to providing the core the 'services' object instead of explicitly listing out each of them?

2019-10-31 19:45 UTC, data-enabler commented on src/answers-umd.js
> +      questionAnswerService: this._services.questionAnswerService
Not against doing that and was already considering it, but it would involve moving the `Services` type into its own file, and I don't think it's quite ready for that since there's things missing from it (AnalyticsReporterService).

2019-10-31 19:48 UTC, merged