Add pagination component
yext/answers-search-ui pull request #320
Opened 2019-10-22 22:44 UTC by Delerme

2019-10-23 18:21 UTC, Delerme commented
Message me on slack if you want a demo link

2019-10-24 18:51 UTC, b1lly requested changes

2019-10-24 18:51 UTC, b1lly commented on src/ui/components/results/paginationcomponent.js
> +  }
Is there a disadvantage to just using a list of links? The urls for the pagination can just be precomputed, and the page would reload and use it as part of the initial search.  I think that would eliminate a lot of the state that is being managed in the component as well.

2019-10-24 18:51 UTC, b1lly commented on src/core/models/searchconfig.js
> +export default class SearchConfig {
I LIKE THIS!

2019-10-24 18:51 UTC, b1lly commented on src/core/models/searchconfig.js
> +    this.limit = config.limit || 20;
What do you think about this config supporting vertical key too?

2019-10-24 18:51 UTC, b1lly commented on src/ui/components/results/paginationcomponent.js
> +    this._verticalKey = config.verticalKey;
Could this be part of the search config?

2019-10-24 18:51 UTC, b1lly commented on src/ui/components/search/filtersearchcomponent.js
> +    this.core.globalStorage.delete(StorageKeys.SEARCH_OFFSET);
This seems like an unfortunate, but necessary situation with the existing way we do things.

Do you have any ideas in regards to how this would work in e.g. the model where "search controller" didn't live inside the component?

2019-10-28 17:58 UTC, Delerme commented on src/ui/components/results/paginationcomponent.js
> +  }
Ideally we wouldn't trigger a full refresh for each page. Our sample apps might be relatively tiny and have only the answers logic to init on load, but our customers' pages might have all sorts of logic that happen on every load, some of which may be super slow. We don't want to be the bad neighbor on our clients' pages that constantly reloads the entire page and creates a bad user experience

2019-10-28 17:58 UTC, Delerme commented on src/core/models/searchconfig.js
> +    this.limit = config.limit || 20;
done

2019-10-28 17:58 UTC, Delerme commented on src/ui/components/results/paginationcomponent.js
> +    this._verticalKey = config.verticalKey;
Done

2019-10-28 17:58 UTC, Delerme commented on src/ui/components/search/filtersearchcomponent.js
> +    this.core.globalStorage.delete(StorageKeys.SEARCH_OFFSET);
Yea the controller would deal with this stuff

2019-10-28 21:32 UTC, Delerme commented on src/ui/components/results/paginationcomponent.js
> +  }
As discussed, talked with product and they decided we should just submit a new search instead of refreshing the whole page

2019-10-31 19:28 UTC, b1lly commented on src/ui/components/results/paginationcomponent.js
> +  }
This is fine as long as it works well for the IFRAME integrations. Has it been tested? Is there something we can do with the test app that would enable us to test the IFRAME integration cases better @data-enabler ?

2019-10-31 19:31 UTC, b1lly submitted a review, later dismissed
As long as its been tested with the IFRAME integrations it seems fine. I'm still not too warm about the single page experience for pagination, it doesn't seem to be a thing that a lot of the other search competitors do -- and for the added complexity it might not be warranted.

BUT, if that's what product wants *shrug*.

LGTM

2019-11-01 14:37 UTC, Delerme commented
Fixed merge conflicts

2019-11-01 21:21 UTC, data-enabler commented on src/ui/components/results/paginationcomponent.js
> +  }
Hmm, I guess it wouldn't be too hard to generate iframe'd versions for each page.

2019-11-01 23:05 UTC, data-enabler approved these changes

2019-11-01 23:06 UTC, merged