Facets
yext/answers-search-ui pull request #342
Opened 2019-10-30 21:56 UTC by Delerme

Message me on a slack for a demo link

2019-11-05 22:54 UTC, b1lly requested changes
Nice dude.

Can you clean up the ReadMe to support all the new configurations. And just strengthen the documentation there a little bit with some of the use cases?

2019-11-05 22:54 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +    }));
Nit: Might be able to push this logic to a helper.

this.options = this.computeOptions(config.previousOptions)

2019-11-05 22:54 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +    this.allShown = false;
jsdoc?

2019-11-06 17:09 UTC, benmcginnis commented on src/ui/components/const.js
> +  .register(FacetsComponent)
So, just to confirm, this is going to be a breaking change because the component name is different now?

2019-11-06 17:09 UTC, benmcginnis commented on src/ui/sass/_fonts.scss
> +$font-family: system-ui,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif !default;
seems like this is a conflict with #345

2019-11-06 17:09 UTC, benmcginnis commented on src/ui/sass/modules/_FilterBox.scss
> +  &-filter:not(.yxt-FilterBox-filter--first) {
is this the equivalent of doing `&-filter + &-filter`?

2019-11-06 17:09 UTC, benmcginnis commented on src/ui/sass/modules/_FilterBox.scss
> +      text-decoration: none;
would this make sense in the `TextButton` mixin?

2019-11-06 17:09 UTC, benmcginnis commented on src/ui/sass/modules/_FilterOptions.scss
> +    svg {
is this just meant to affect the icon component? if so I don't think you actually need to set this styling on the svg element.  If you set the font-size of the icon it should shrink down appropriately if it's square.  additionally i recommend adding a selector to the icon's parent and setting the left margin there.  I also recommend setting the margin with an `ex` unit as it will scale with the font-size without an implementer having to change it explicitly.

2019-11-06 17:09 UTC, benmcginnis commented on src/ui/sass/modules/_FilterOptions.scss
> +    transform: rotate(270deg);
do you need the svg as part of this selector or does rotating the parent work?

2019-11-06 17:09 UTC, benmcginnis commented on src/ui/templates/filters/filterbox.hbs
> +    <div class="yxt-FilterBox-titleContainer">
you should use an h level element for a title, such as an h2 or h3 depending on the overall document outline

2019-11-06 17:24 UTC, Delerme commented on src/ui/components/const.js
> +  .register(FacetsComponent)
Yea you can more of less consider this deleting the old facets and creating a new component. So any usages of the old facets are now broken

2019-11-06 18:15 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +    }));
done

2019-11-06 18:15 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +    this.allShown = false;
done

2019-11-06 18:15 UTC, Delerme commented on src/ui/sass/_fonts.scss
> +$font-family: system-ui,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif !default;
yea kelly stole that from this review, it should merge fine

2019-11-06 18:15 UTC, Delerme commented on src/ui/sass/modules/_FilterBox.scss
> +      text-decoration: none;
as a flag? This button works the opposite from normal text buttons (shows underline default, then hides on hover, whereas textbutton does the opposite)

2019-11-06 18:15 UTC, Delerme commented on src/ui/sass/modules/_FilterOptions.scss
> +    svg {
deleted

2019-11-06 18:15 UTC, Delerme commented on src/ui/sass/modules/_FilterOptions.scss
> +    transform: rotate(270deg);
has to be svg

2019-11-06 18:15 UTC, Delerme commented on src/ui/templates/filters/filterbox.hbs
> +    <div class="yxt-FilterBox-titleContainer">
yea I'm worried we don't really know the document outline since these components are used on thirdparty sites, so we should remain h-agnostic, thoughts?

2019-11-06 18:41 UTC, benmcginnis commented on src/ui/templates/filters/filterbox.hbs
> +    <div class="yxt-FilterBox-titleContainer">
Yeah, I think probably what we should do is add an optional "staring h level" or some such to the init config and have it cascade down from there.  The issue with not having them is that it's an accessibility problem.

2019-11-06 19:01 UTC, Delerme commented on src/ui/templates/filters/filterbox.hbs
> +    <div class="yxt-FilterBox-titleContainer">
Yea that's an annoying situation. This should probably be discussed at a high level with product and ux and fix the headings across the library all at once, do you think we should wait for that before merging this?

2019-11-06 19:36 UTC, Delerme commented on src/ui/sass/modules/_FilterBox.scss
> +  &-filter:not(.yxt-FilterBox-filter--first) {
yup, changed

2019-11-06 19:36 UTC, benmcginnis commented on src/ui/sass/modules/_FilterBox.scss
> +      text-decoration: none;
Sorry I didn't realize it was special it seemed like it was part of the style

2019-11-06 21:05 UTC, benmcginnis commented on src/ui/templates/filters/filterbox.hbs
> +    <div class="yxt-FilterBox-titleContainer">
I think we can maybe just pick a sensible h level here so we don't lose this line?

2019-11-06 21:06 UTC, benmcginnis commented on src/ui/templates/filters/filterbox.hbs
> +    <div class="yxt-FilterBox-titleContainer">
2 probably makes the most sense in isolation, as currently the searchbar sets an h1

2019-11-06 21:07 UTC, benmcginnis commented
Since this is a breaking change, should it be against the 0.10.0 version?

2019-11-07 00:20 UTC, benmcginnis commented on src/ui/sass/modules/_FilterOptions.scss
> +    transform: rotate(270deg);
Interesting and unexpected

2019-11-07 18:01 UTC, Delerme commented on src/ui/templates/filters/filterbox.hbs
> +    <div class="yxt-FilterBox-titleContainer">
set to 2

2019-11-07 18:02 UTC, Delerme commented
Moved to 10

2019-11-12 17:29 UTC, b1lly approved these changes

2019-11-12 17:45 UTC, merged

2019-11-19 00:28 UTC, data-enabler commented
> Since this is a breaking change, should it be against the 0.10.0 version?

Speaking of which, this broke the sample app.