Add LocationBias component
yext/answers-search-ui pull request #343
Opened 2019-10-31 18:41 UTC by bwangYext

Backend changes for this are still in CR but should be out soon.

TEST=auto,manual
Tested it locally with backend change.

2019-11-05 20:56 UTC, b1lly requested changes
Savage! I'd like to be CC'd on the backend change please.

2019-11-05 20:56 UTC, b1lly commented on src/ui/components/search/locationbiascomponent.js
> +    this._updateLocationEl = config.updateLocationEl || '.js-locationBias-update-location';
can you add JS doc to each of these?

Also, can you update the documentation to include updateLocationEl?

2019-11-05 20:56 UTC, b1lly commented on src/ui/components/search/locationbiascomponent.js
> +      }
@Delerme is this navigator logic shared somewhere else in code?

What do you think about creating an GeoLocation abstraction class that abstracts away the implementation details and is shared amongst the system?

2019-11-05 20:56 UTC, b1lly commented on src/ui/components/component.js
> +        console.log(e);
woops

2019-11-05 20:56 UTC, b1lly commented on src/core/core.js
> +        this.globalStorage.set(StorageKeys.LOCATION_BIAS, data[StorageKeys.LOCATION_BIAS]);
style nit:

can we keep the sets together? or is there a reason it needs to happen after the deletes?

2019-11-05 20:56 UTC, b1lly commented on src/ui/components/search/searchcomponent.js
> +    });
Is this a product requirement? Where whenever we remove geolocation we should be automatically be triggering searches?

2019-11-06 16:55 UTC, benmcginnis commented on src/ui/sass/modules/_LocationBias.scss
> +  &-bullet-unknown-loc
Similar to my comment [here](https://github.com/yext/answers/pull/350#discussion_r342734680), I'd really appreciate it if we could use single level class names following the [SUIT CSS naming convention](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md).

2019-11-06 19:32 UTC, bwangYext commented on src/ui/components/search/locationbiascomponent.js
> +    this._updateLocationEl = config.updateLocationEl || '.js-locationBias-update-location';
Done

2019-11-06 19:33 UTC, bwangYext commented on src/ui/components/search/locationbiascomponent.js
> +      }
Let me know if you want to do this now.

2019-11-06 19:33 UTC, bwangYext commented on src/ui/components/component.js
> +        console.log(e);
Removed.

2019-11-06 19:33 UTC, bwangYext commented on src/core/core.js
> +        this.globalStorage.set(StorageKeys.LOCATION_BIAS, data[StorageKeys.LOCATION_BIAS]);
Done.

2019-11-06 19:33 UTC, bwangYext commented on src/ui/components/search/searchcomponent.js
> +    });
Calling search in component.

2019-11-06 19:33 UTC, bwangYext commented on src/ui/sass/modules/_LocationBias.scss
> +  &-bullet-unknown-loc
Renamed.

2019-11-06 21:09 UTC, benmcginnis commented on src/ui/sass/modules/_LocationBias.scss
> +  a
you should have a class selector on this element, rather than using the `a` selector

2019-11-07 00:22 UTC, benmcginnis commented on src/ui/sass/modules/_LocationBias.scss
> +  &-bullet-unknown-loc
Thank you!!

2019-11-07 16:10 UTC, bwangYext commented on src/ui/sass/modules/_LocationBias.scss
> +  a
Done

2019-11-15 15:49 UTC, bwangYext commented
Poke

2019-11-15 15:53 UTC, b1lly commented on src/ui/components/search/locationbiascomponent.js
> +      }
I would have preferred to do it now, but because of my absence of this review -- seems like this item might be expected to be done already.

I think it's ok to push the refactor for this area to the next version, and merge this as is.

2019-11-15 15:55 UTC, b1lly submitted a review, later dismissed

2019-11-15 16:08 UTC, b1lly approved these changes

2019-11-15 16:10 UTC, merged