cookies: session tracking opt in feature
yext/answers-search-ui pull request #349
Opened 2019-11-04 20:45 UTC by apokellypse

I set it to true by default. I think we want some way for the client to customize it further, but it didn't occur to me how we wanted to do this, so decided to put up a patch for now.

2019-11-04 21:59 UTC, apokellypse commented
Sorry, I investigated and realized I misunderstood the prompt. Closing this for now.

2019-11-05 23:01 UTC, apokellypse commented
After some discussion, It turns out that this approach is on the right track, and the client should be able to set the Session opt in, similar to how conversion tracking is done. Reopening.

2019-11-05 23:34 UTC, data-enabler commented
Looks like my commits are still being included in this? You can always just rebase locally and `push -f` if you need to.

2019-11-06 15:58 UTC, apokellypse commented
Got rid of the commit sandwich! Ended up using cherry-picking after interactive rebase didn't handle my merge commit and initial commit well.

2019-11-08 16:50 UTC, data-enabler commented on src/answers-umd.js
> +    globalStorage.set(StorageKeys.SESSIONS_OPT_IN, config.sessionTrackingEnabled);
If we're adding a config option, we should add it to the table in the readme.

2019-11-08 16:50 UTC, data-enabler commented on src/core/services/searchservice.js
> +   * @param {string} query.sessionTrackingEnabled The boolean as string to indicate if session tracking is on
Seems weird to require users of the interface to deal with stringifying the boolean, and we already have a boolean param in `isDynamicFiltersEnabled`.

2019-11-11 21:43 UTC, apokellypse commented on src/core/services/searchservice.js
> +   * @param {string} query.sessionTrackingEnabled The boolean as string to indicate if session tracking is on
good point, will make this a boolean

2019-11-11 21:44 UTC, apokellypse commented on src/answers-umd.js
> +    globalStorage.set(StorageKeys.SESSIONS_OPT_IN, config.sessionTrackingEnabled);
will do

2019-11-12 19:19 UTC, data-enabler requested changes

2019-11-12 19:19 UTC, data-enabler commented on src/answers-umd.js
> +    let sessionTrackingEnabled = config.sessionTrackingEnabled || true;
Doesn't this always evaluate to true?

2019-11-12 21:24 UTC, apokellypse commented on src/answers-umd.js
> +    let sessionTrackingEnabled = config.sessionTrackingEnabled || true;
Yes, will fix

2019-11-12 22:45 UTC, data-enabler approved these changes

2019-11-13 00:04 UTC, merged