Generator
yext/answers-search-ui pull request #357
Opened 2019-11-08 17:23 UTC by b1lly

There's definitely a few more iterations to organizing this a little better.

We need to:

1. Organize the generator code into its own package and files
2. Have the SDK be a dependency thats pulled in to the app and speed up the compilation of this step
3. Define the TOP LEVEL configuration object for the siteConfig more concretely instead of just depending on an object literal. For instance, we should have a concrete model defined in the library of all the configuration options we allow.

2019-11-08 19:53 UTC, data-enabler requested changes

2019-11-08 19:53 UTC, data-enabler commented on sample-app/README.md
> +You can `cd` into that directory and open `index.html` in your browser of choice
Probably simpler to just say that they should open `generated/index.html`

2019-11-08 19:53 UTC, data-enabler commented on sample-app/config/config.json
> +}
Missing newline

2019-11-08 19:53 UTC, data-enabler commented on sample-app/index.js
> +// TODO(billy) Move to ES6 imports when Node supports ES6 modules
Node does support ES6 modules, so I'd just remove the latter part of this comment.

2019-11-08 19:53 UTC, data-enabler commented on sample-app/index.js
>  const writeFile = util.promisify(fs.writeFile);
Side note: apparently as of Node 10 there's promise-based versions of the fs methods
https://nodejs.org/api/fs.html#fs_fs_promises_api

2019-11-08 19:53 UTC, data-enabler commented on sample-app/index.js
> +      return console.error(err);
Promise APIs are nice for simple error handling like this, since you can say:
```js
fs.copy(config.assetsDir, `${config.outputDir}/${config.assetsDir}`)
  .catch(console.error)
  .then(() => console.log('Copied assets to generated site!'));
```

2019-11-08 19:53 UTC, data-enabler commented on sample-app/index.js
> +    this.outputDir = './generated';
It occurs to me that specifying paths like this makes the script not compatible with Windows. We should start using the `path` api at some point.

2019-11-08 19:53 UTC, data-enabler commented on sample-app/index.js
> +class Configuration {
If we're going to bother writing JSDoc, I think this could just be a `typedef` + a `DEFAULTS` object.

2019-11-08 19:53 UTC, data-enabler commented on sample-app/index.js
> +      require('./config/credentials.json'),
If we're cleaning stuff up, it probably makes sense to just parse the file normally, since this is kind of a hack.

2019-11-08 19:53 UTC, data-enabler commented on sample-app/index.js
> +    this.templateUrl = `${config.assetsDir}/answerstemplates.compiled.min.js`;
This isn't currently being used, is it? Before, this was being added to the config so that `app.js` could pass it to `ANSWERS.init`.

2019-11-08 19:54 UTC, b1lly commented on sample-app/index.js
> +// TODO(billy) Move to ES6 imports when Node supports ES6 modules
Isn't it only supported under an experimental flag?

2019-11-08 19:55 UTC, vramesh1 commented on sample-app/index.js
> +// TODO(billy) Move to ES6 imports when Node supports ES6 modules
https://timonweb.com/posts/how-to-enable-es6-imports-in-nodejs/

2019-11-08 20:05 UTC, data-enabler commented on sample-app/config/config.json
> +}
Actually, this file shouldn't have even been in the repo at all; I think I just accidentally committed it at some point.

2019-11-08 20:14 UTC, data-enabler commented on sample-app/index.js
> +// TODO(billy) Move to ES6 imports when Node supports ES6 modules
@b1lly Yeah, but it would just be a matter of changing the buildHtml script to use the flag.
@vramesh1 That article is out of date, at the end it links to a more recent version that uses the `esm` module (which is what I personally use to handle ES6 imports.

Point is, there isn't really anything stopping us from using ES6 imports right now, so I don't see a reason to phrase it like we're waiting on outside stuff. (Also, if we were to use TypeScript we'd get ES6 module compatibility for free 😉)

2019-11-12 17:36 UTC, b1lly commented on sample-app/index.js
> +      require('./config/credentials.json'),
You mean with fetch? or with the fs module?

2019-11-12 17:38 UTC, b1lly commented on sample-app/index.js
> +    this.templateUrl = `${config.assetsDir}/answerstemplates.compiled.min.js`;
This is a temporary object. I think it actually should be pulled in as a dependency into the library via a package manager.

2019-11-12 17:50 UTC, b1lly commented on sample-app/index.js
> +    this.outputDir = './generated';
Agreed. Also, we'll have to revisit some of these values and variables because some are "src" of data and some are "dest" of the directory to put it in.

To keep things simple it just uses the same dest (e.g. assets) as it does from source.

2019-11-12 20:25 UTC, data-enabler commented on sample-app/index.js
> +      require('./config/credentials.json'),
With `fs`, rather than using `require`

2019-11-12 21:40 UTC, data-enabler requested changes

2019-11-12 21:40 UTC, data-enabler commented on sample-app/README.md
> +You can `cd` into that directory and open `generated/index.html` in your browser of choice
They don't need to `cd` if they're using the `generated/index.html` path.

2019-11-12 21:40 UTC, data-enabler commented on sample-app/index.js
> +    this.templateUrl = `${config.assetsDir}/answerstemplates.compiled.min.js`;
To be clear, I'm talking about `templateUrl` specifically. The sample app generator currently sets the `templateUrl` property passed to `ANSWERS.init` to point at the locally compiled templates, but it looks like we're no longer doing that.

2019-11-12 21:40 UTC, data-enabler commented on sample-app/index.js
> +    .then(() => console.log('Copied SDK bundles to generated site!'))
Missing semicolon

2019-12-14 00:22 UTC, vramesh1 commented
Closing for now since I'm not sure if this will work will continue.
Pls re-open if needed.

2019-12-14 00:22 UTC, closed without merging