questionsubmission: add show/hide trigger and interaction
yext/answers-search-ui pull request #363
Opened 2019-11-15 19:05 UTC by apokellypse

Please add ?w=1 param to view this without the whitespace changes.

More context here:
https://stackoverflow.com/questions/37007300/how-to-ignore-whitespace-in-github-when-comparing

2019-11-15 19:05 UTC, apokellypse commented
Here's a link to see the diffs without whitespace changes:

https://github.com/yext/answers/pull/363/files?utf8=%E2%9C%93&diff=unified&w=1

2019-11-16 00:07 UTC, data-enabler requested changes

2019-11-16 00:07 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +      <div class="{{#if questionExpanded}}yxt-QuestionSubmission-expandWrapper{{else}}yxt-QuestionSubmission-collapseWrapper{{/if}} js-content-visibility-toggle"
I think if we're actually doing BEM this should be yxt-QuestionSubmission__toggle--expanded, though a quick grep shows that there's no `__` in the codebase. But we should at least make these suffixes `--expanded` and `--collapsed`.

2019-11-16 00:07 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +      <div class="{{#if questionExpanded}}yxt-QuestionSubmission-expandWrapper{{else}}yxt-QuestionSubmission-collapseWrapper{{/if}} js-content-visibility-toggle"
This isn't keyboard accessible; you should wrap it in a `button`. I think there should be an example in `resultsaccordion.hbs`

2019-11-18 20:05 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +      <div class="{{#if questionExpanded}}yxt-QuestionSubmission-expandWrapper{{else}}yxt-QuestionSubmission-collapseWrapper{{/if}} js-content-visibility-toggle"
fixed in latest commit

2019-11-18 20:05 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +      <div class="{{#if questionExpanded}}yxt-QuestionSubmission-expandWrapper{{else}}yxt-QuestionSubmission-collapseWrapper{{/if}} js-content-visibility-toggle"
fixed in latest commit

2019-11-19 19:31 UTC, data-enabler requested changes

2019-11-19 19:31 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +      return;
It would be nice if  not having a toggle element didn't prevent the component from working. I think that would make it possible to use the new code with an old template without things breaking.

2019-11-19 19:31 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +                <a class="yxt-QuestionSubmission-privacyPolicyUrl" href="{{_config.privacyPolicyUrl}}">{{_config.privacyPolicyUrlLabel}}</a>
This link should open in a separate tab/window.

2019-11-19 19:31 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  &--expanded
`yxt-QuestionSubmission--expanded` doesn't really make sense as the selector when it's being applied specifically to the toggle element. Let's make this `yxt-QuestionSubmission__toggle--expanded`.

@b1lly Are we actually using BEM notation for the sdk, or did we cook up our own thing?

2019-11-19 19:31 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    cursor: pointer;
I think this shouldn't be necessary anymore since it's inside a button

2019-11-19 21:33 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +      <button class="{{#if questionExpanded}}yxt-QuestionSubmission--expanded{{else}}yxt-QuestionSubmission--collapsed{{/if}} js-content-visibility-toggle"
Another thing: screen readers can't make sense of a toggle button like this unless you use the `aria-expanded` and `aria-controls` attributes. You can see an example in `resultsaccordion.hbs`. In the ANS-325 description they suggested that we should reuse the implementation between that component and this one, but I'm not sure how easy that would actually be with our current component architecture.

It's also probably worthwhile to make the whole header the toggle rather than the icon.

2019-11-20 20:10 UTC, apokellypse commented
will apply these comments to the new branch; right now separating these out into separate reviews

2019-11-20 21:14 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +      return;
fixed in patch 2 of new pull request

2019-11-20 21:14 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +                <a class="yxt-QuestionSubmission-privacyPolicyUrl" href="{{_config.privacyPolicyUrl}}">{{_config.privacyPolicyUrlLabel}}</a>
fixed in patch 2 of new pull request

2019-11-20 21:16 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    cursor: pointer;
it's still necessary, unfortunately; otherwise it's a default pointer

2019-11-20 21:17 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +      <button class="{{#if questionExpanded}}yxt-QuestionSubmission--expanded{{else}}yxt-QuestionSubmission--collapsed{{/if}} js-content-visibility-toggle"
fixed in patch 2 of new pull request

2019-11-20 21:17 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +      <button class="{{#if questionExpanded}}yxt-QuestionSubmission--expanded{{else}}yxt-QuestionSubmission--collapsed{{/if}} js-content-visibility-toggle"
header is not toggle-able yet so I'll wait to resolve

2019-12-09 16:55 UTC, vramesh1 commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  &--expanded
@data-enabler seems like we've been doing our own thing for now.
to avoid mixing notations within the same stylesheet, should we keep consistent with the current methodology for the time being, while we document/communicate team-wide the methodology to implement in new components going forward?
so in this case, keeping with current methodology, it would probably be something closer to `yxt-QuestionSubmission-toggle-expanded` or `yxt-QuestionSubmission-expanded`?

2019-12-09 17:09 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  &--expanded
let's continue this conversation in https://github.com/yext/answers/pull/389, am closing this review because it is no longer needed after it was split out into a functional PR and a styling PR

2019-12-09 17:10 UTC, closed without merging