qacomponent: functional changes for the following:
yext/answers-search-ui pull request #386
Opened 2019-11-20 20:08 UTC by apokellypse

- add show/hide trigger and interaction
- add link to privacy policy
- new error handling

2019-11-20 21:51 UTC, data-enabler requested changes
Make sure the tests continue to pass. You can run them locally with `npm run test`.

2019-11-20 21:51 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    var chromiumEmailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Browsers have built-in validation for `input type="email"`; we should be able to use this by calling [`checkValidity()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/checkValidity), even though we're using `novalidate` on the form.

We should be able to do this for the other required fields as well, which is nice since it means we don't have to duplicate validation requirements in the html and js (having it in the html is desirable for screen reader accessibility).

2019-11-20 21:51 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +              <textarea class="yxt-QuestionSubmission-formInput js-question-field js-question-text{{#if errors.questionTextRequired}} required-error{{/if}}"
If you're just planning on using `required-error` for styling, we could probably use `yxt-QuestionSubmission-formInput:invalid` instead

2019-11-20 21:51 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +                value="true"
Since we're using the `checked` property, I think we can get rid of this.
Also, if I'm reading this correctly, seems like the original check for this never worked lol (since `.value` would always return `'true'`).

2019-11-20 21:51 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +  {{#if questionExpanded}}
Torn on whether it makes more sense to just hide this with CSS when it's collapsed. We're not using a virtual dom, so there isn't really a performance benefit.

Looking at ResultsAccordion, it looks like we're hiding collapsed content with CSS there.

2019-11-20 21:51 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +        aria-controls="yxt-QuestionSubmission-form"
Looks like you didn't add this class to the form itself.

Also, we unfortunately need to account for the fact that users could put multiple of these components on the page, so any ids we use need to be unique per component. I think `name` is supposed to be unique, so we can probably just append that. Looks like that's what the range and date components do.

2019-11-20 21:51 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +      <button class="{{#if questionExpanded}}yxt-QuestionSubmission__toggle--expanded{{else}}yxt-QuestionSubmission__toggle--collapsed{{/if}} js-content-visibility-toggle"
Looked around at some css files, and it seems like our current style is basically BEM, but we use a hyphen to separate block and element instead of double underscore. Whether we should use BEM proper is outside of the scope for this, so let's just be consistent with our other stuff.

2019-11-20 21:51 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +              <label for="yxt-QuestionSubmission-ackCheckboxInput"
If you put the checkbox inside the label element, you don't have to worry about creating an id for it.

2019-11-21 22:09 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +                value="true"
yeah lol the original check for this never worked

2019-11-21 22:12 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +              <label for="yxt-QuestionSubmission-ackCheckboxInput"
I wanted to separate them out for ease of styling. Based on the design, the checkbox effectively has its own column, so no text should appear under it with word wrapping. Any suggestions?

2019-11-21 22:18 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    var chromiumEmailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
won't this mean we can't validate based on the formData object alone, but now need to depend on using references to the dom object to call checkValidity?

I'm ok with that, but some part of me really liked validating using what the form submitted, and this will make it so that I need to validation logic on the submit handler, separating validation in two stages

2019-11-21 22:19 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    var chromiumEmailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
I guess validateRequired is fine as a separate step actually, because this is validating format, which is different

2019-11-21 23:51 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +              <textarea class="yxt-QuestionSubmission-formInput js-question-field js-question-text{{#if errors.questionTextRequired}} required-error{{/if}}"
the red styling provided by required-error should only show up after the form submits, but :invalid will select it in real-time, which doesn't make it the perfect replacement at this time

2019-11-22 00:05 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    var chromiumEmailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
The way I see it, there isn't any validation logic here that can't be checked using `checkValidity`, so our validation code becomes "if `checkValidity` returns false for anything, then show the appropriate error".

2019-11-22 00:07 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    var chromiumEmailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
sgtm

2019-11-22 00:07 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +              <textarea class="yxt-QuestionSubmission-formInput js-question-field js-question-text{{#if errors.questionTextRequired}} required-error{{/if}}"
Ah, fair enough. In that case, I think we probably want to prefix the classes so that it doesn't interfere with any of the client's CSS? Not sure where we stand on that, since there are other places that run afoul of this.

2019-11-22 00:14 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +              <label for="yxt-QuestionSubmission-ackCheckboxInput"
You can probably either
1. Make the label `display: flex` and put the text inside a div
1. Use `margin-left` and negative `textIndent`

2019-11-22 19:49 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +              <textarea class="yxt-QuestionSubmission-formInput js-question-field js-question-text{{#if errors.questionTextRequired}} required-error{{/if}}"
prefixing sgtm

2019-11-22 19:51 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +  {{#if questionExpanded}}
since there doesn't seem to be a big difference between the two methods, I'm in favor of keeping it this way because it's less html to render

2019-11-22 20:11 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +              <label for="yxt-QuestionSubmission-ackCheckboxInput"
done

2019-11-22 21:52 UTC, data-enabler requested changes

2019-11-22 21:52 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +        if (fields[i].name === 'email') {
`switch (fields[i].name) {`

2019-11-22 21:52 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +      <div class="yxt-QuestionSubmission-form">
I think we want the id to be on both elements, which is fine since only one is rendered at a time. Also, you didn't update the `aria-controls` attribute.

2019-11-22 22:01 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +        if (fields[i].name === 'email') {
tru

2019-11-22 22:02 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +      <div class="yxt-QuestionSubmission-form">
gotcha, will do

2019-11-22 22:58 UTC, data-enabler requested changes

2019-11-22 22:58 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +              errors['emailErrorText'] = '* Please enter a valid email address';
According to Max, all user-facing text needs to be configurable. Seems like the error messages were overlooked in the spec.

2019-11-22 23:21 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +              errors['emailErrorText'] = '* Please enter a valid email address';
ahh yes

2019-11-23 00:16 UTC, data-enabler requested changes

2019-11-23 00:16 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +            <div class='yxt-QuestionSubmission-inputError'>{{#if errors.emailErrorText}}{{errors.emailErrorText}}{{/if}}</div>
I think this should be `strong` instead of `div`.
https://www.w3.org/TR/WCAG20-TECHS/G138.html

Though this makes me wonder if we need to have better cues for errors for missing required fields.

2019-11-23 00:16 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +  'privacyPolicyErrorText': '* You must agree to the privacy policy to submit feedback.',
Don't forget to add these to the readme.

2019-11-25 18:10 UTC, data-enabler approved these changes

2019-11-25 18:10 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +                  <a class="yxt-QuestionSubmission-privacyPolicyUrl" href="{{_config.privacyPolicyUrl}}" target="_blank">{{_config.privacyPolicyUrlLabel}}</a>
If you're going with the approach we talked about the text and link will need to be wrapped in a span or div, unless you were planning on doing that alongside the styling changes.

Also, looks like the indentation's a bit weird here.

2019-11-25 20:23 UTC, merged