qa-component: styling
yext/answers-search-ui pull request #389
Opened 2019-11-25 20:29 UTC by apokellypse

styling changes for:
    
    - icon sizing to 18px by 18px
    - font sizes in form
    - using new mixins
    - focus state for input elements
    - error states
    - link to privacy policy

2019-11-25 23:09 UTC, data-enabler requested changes

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  $acknowledgement-bar-background: $color-background-highlight !default;
It's kinda weird for this to be the only variable without the `question-submission-` prefix. You could replace `background` with `bg` to stop the variable from being too long.

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  $question-submission-title-bar-background: $color-background-highlight !default;
Thinking about the variable organization, it probably makes sense to just alphabetize them? I was expecting this to be near the rest of the title variables.

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  &-titleIconWrapper, &-toggle--expanded, &-toggle--collapsed
Missed this in the previous review, but the idea with BEM is that we would put both `yxt-QuestionSubmission-toggle` and `yxt-QuestionSubmission-toggle--expanded` on the element, so styling common to both states would go on the former and we wouldn't need to write selectors like this.

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      margin-top: $base-spacing;
In my experience, `:first-child` can cause issues if, say, you added a hidden input at the beginning of the form. I'd suggest sibling selectors instead:
```scss
&-formRow {
  margin: $base-spacing;

  & + & {
    margin-top: 0;
  }
}
```
(Also personal preference on my part to use the special-case to remove margins rather than adding them.)

If the container weren't `flex`, we could just take advantage of margin collapsing.

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    margin-bottom: $base-spacing;
Unrelated: there's a `margin-block-end` a few lines up that we should change, since that property isn't supported in IE.

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    text-indent: -1.75rem;
I'd rather go with the `flex`-based approach we discussed, since the `text-indent` method is kinda hacky.

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  &-privacyPolicyUrl
There's some `Link` mixins we should probably use here.

2019-11-25 23:09 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
>    $question-submission-error-text-color: rgb(148, 0, 0);
Is this unused?

2019-11-26 19:59 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  $question-submission-title-bar-background: $color-background-highlight !default;
I think that if things are in the same level of importance, alphabetizing them is probably good

2019-11-26 19:59 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  $question-submission-title-bar-background: $color-background-highlight !default;
*or within the same level of context

2019-11-26 20:03 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  &-titleIconWrapper, &-toggle--expanded, &-toggle--collapsed
oh, I see. I'll make that change and add in the template file

2019-11-26 20:27 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
>    $question-submission-error-text-color: rgb(148, 0, 0);
it's used. will rename to make it more obvious

2019-11-26 20:38 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
>    $question-submission-error-text-color: rgb(148, 0, 0);
More concerned about the color literal. It's identical to `$color-error`, right?

2019-11-26 20:58 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      margin-top: $base-spacing;
the margins seem to be collapsing with flex :o

2019-11-26 21:14 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      margin-top: $base-spacing;
jk they are not collapsing

2019-11-27 17:17 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
>    $question-submission-error-text-color: rgb(148, 0, 0);
It is; I'll make it equal to $color-error

2019-11-27 17:20 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
>    $question-submission-error-text-color: rgb(148, 0, 0);
In the most recent commit, it's already been fixed with the color literal removed.

2019-12-02 20:05 UTC, data-enabler requested changes

2019-12-02 20:05 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    flex-flow: row nowrap;
We should use `align-items: flex-start` since we want the checkbox to be at the top of the container. The default behaves like `stretch`, which happens to align checkboxes to the top in Chrome, but not in Firefox.

2019-12-02 20:05 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +                  id="yxt-QuestionSubmission-ackCheckboxInput"
`id`s still need to be unique.

2019-12-02 20:05 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +                <label class="yxt-QuestionSubmission-privacyPolicyText">
Looks like you're missing the `for`?

2019-12-02 20:05 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +                  <span>
Is this span doing anything? it seems unnecessary.

2019-12-09 16:36 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    flex-flow: row nowrap;
ah, thanks for this useful tidbit

2019-12-09 16:51 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +                  id="yxt-QuestionSubmission-ackCheckboxInput"
done

2019-12-09 16:51 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +                <label class="yxt-QuestionSubmission-privacyPolicyText">
yeah it was missing; put it back in

2019-12-09 17:37 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +  &-toggle--expanded
@vramesh1 We're already deviating from BEM to match the existing stylesheets. The CSS here doesn't the `__{element}` syntax, which we aren't using anywhere yet, but does use the `--{modifier}` syntax, which is already present in some files.

2019-12-09 23:40 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +                  <span>
not necessary so removed it

2019-12-10 01:29 UTC, data-enabler requested changes

2019-12-10 01:29 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +  'teaser': 'Can’t find what you are looking for? Provide your feedback below.',
This reminds me that we need to make sure the readme includes all the configuration options, though maybe not in this PR.

2019-12-10 01:29 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +        <input style="display: none" type="email" name="decoyemailforchromeautofill">
Do we specifically not want this form to autofillable? Can't really see a good reason for disabling.

Also, if that is what we want, is `autocomplete="off"` not an option?

2019-12-10 01:29 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +      <button class="yxt-QuestionSubmission-toggle{{#if questionExpanded}}--expanded{{else}}--collapsed{{/if}} yxt-QuestionSubmission-toggle"
If this no longer performs actions, it shouldn't be a button.

2019-12-10 01:29 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +    class="yxt-QuestionSubmission-titleBar js-content-visibility-toggle"
Just adding a click handler to a `div` doesn't account for keyboard users, who won't be able to navigate to and activate the element. I also don't know if the aria attributes here are enough for screen readers to present the element as a control.

https://www.w3.org/TR/wai-aria-practices/examples/button/button.html

Often it's easier to just make the element a button and override the styling as necessary, since you get all the behavior for free.

2019-12-10 01:29 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    height: auto;
Could we just remove the line instead? I think `auto` should be the default.

2019-12-10 01:29 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +        margin-bottom: 0;
I don't think this works correctly when there's 3+ fields in the row.

I think what we probably want is:
```scss
      & + &
      {
        margin-top: $base-spacing;
      }
```

2019-12-10 20:10 UTC, rosiegrant commented on README.md
ANSWERS.addComponent('QASubmission', {
  container: '.question-submission-container',
  formSelector: '.js-form',                       // Defaults to native form node within container
  nameLabel: 'Name', //Label for name input
  emailLabel: 'Email', //Label for email input
  questionLabel: 'Question', //Label for question input
  sectionTitle: 'Ask a question', //Title displayed for the form
  teaser: 'Can\'t find what you’re looking for? Ask a question below.', //Teaser displayed for the form, next to the title
  description: 'Enter your question and contact information, and we\'ll get back to you with a response shortly.' // Description for the form. 
  privacyPolicyText: 'By submitting my email address, I consent to being contacted via email at the address provided.', //Text before the privacy policy link
  privacyPolicyUrlLabel: 'Learn more here.', //Label for the privacy policy url 
  privacyPolicyUrl: 'https://mybiz.com/policy',   // Required. Defaults to ''.
  privacyPolicyErrorText: '* You must agree to the privacy policy to submit feedback.', //error message displayed when the privacy policy is not selected
  emailFormatErrorText: '* Please enter a valid email address.'  //error message displayed when an invalid email is not submitted.
  requiredInputPlaceholder: '(required)', //placeholder displayed in all required fields
  questionSubmissionConfirmationText: 'Thank you for your question!', //Confirmation displayed once a question is submitted
  buttonLabel: 'Submit', //Label displayed on the button to submit a question 
  entityId: 123,                                  // Required. Entity ID of the organization entity in the Knowledge Graph. 
  language: 'en', 
  expanded: true //whether or not the form is expanded by default when a user arrives on the page. 
})

2019-12-11 16:46 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +        <input style="display: none" type="email" name="decoyemailforchromeautofill">
@rosiegrant we want autofill to be off because it's a bad experience right? I personally don't like the Chrome autofill, but I don't know the official reason.

This solution was proposed in stackoverflow to work, but it doesn't seem to work all the time. Will look into the autocomplete solution.

2019-12-11 19:34 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +  'teaser': 'Can’t find what you are looking for? Provide your feedback below.',
it's already in the pr, rip

2019-12-11 19:34 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +    height: auto;
yeah & done

2019-12-11 19:34 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +        margin-bottom: 0;
oh i like this much better.

2019-12-11 19:35 UTC, apokellypse commented on README.md
done!

2019-12-11 19:37 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +    class="yxt-QuestionSubmission-titleBar js-content-visibility-toggle"
thanks for the link! I went with using the <button> element

2019-12-11 22:01 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      box-shadow: inset 0 0 0 1px $color-text-primary;
`outline` is another alternative to border, and is what's typically used by browsers for focus styling.

2019-12-12 22:34 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      box-shadow: inset 0 0 0 1px $color-text-primary;
whoaaaa

2020-01-02 18:50 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      padding: 7px 13px;
This is kind of unfortunate, but the fix would have to happen in the `Button` mixin so it's not worth addressing in this commit.

2020-01-02 19:05 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      padding: 7px 13px;
Understood, will remove this from my commit

2020-01-02 19:08 UTC, data-enabler requested changes

2020-01-02 19:08 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
>      width: 100px;
Is there a reason for the fixed width? Anything longer than the default text is going to wrap in a weird way. Seems like we could just remove this, but if not then `min-width` would be more appropriate.

2020-01-02 19:08 UTC, data-enabler commented on src/ui/templates/questions/questionsubmission.hbs
> +      <form id="yxt-QuestionSubmission-form-{{name}}" class="yxt-QuestionSubmission-form" novalidate autocomplete="false">
I don't think it's worth trying to use hacks like `"new-password"` to get around browser autofill, since browsers are always free to ignore html attributes and do whatever they want. I'd just put `autocomplete="off"` on the form and call it a day. Not sure if `autocomplete="false"` is supposed to do something special, but it's not a standard autocomplete value.

2020-01-02 19:19 UTC, data-enabler commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      padding: 7px 13px;
No, leave this as-is. My point was that we either have to adjust the padding here or change how the border works in the `Button` mixin, and it's not worth doing the latter right now.

I'm just leaving this comment for anyone in the future who wonders why things were done this way.

2020-01-02 19:20 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
> +      padding: 7px 13px;
ahh gotcha

2020-01-02 19:22 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
>      width: 100px;
based on some previous conversations it seems like we want to allow for button text that take up multiple lines. I'll check with Rose

2020-01-02 19:24 UTC, apokellypse commented on src/ui/templates/questions/questionsubmission.hbs
> +      <form id="yxt-QuestionSubmission-form-{{name}}" class="yxt-QuestionSubmission-form" novalidate autocomplete="false">
the `autocomplete="false"` was another hack that some SO users reported working. I'll remove that and the other hacks and go with `autocomplete="off"` as recommended.

2020-01-02 20:00 UTC, apokellypse commented on src/ui/sass/modules/_QuestionSubmission.scss
>      width: 100px;
offline discussion conclusion: flex will take care of evenly distributing words across lines, so removing fixed-width will get us what we want

2020-01-02 20:12 UTC, rosiegrant commented on src/ui/templates/questions/questionsubmission.hbs
> +        <input style="display: none" type="email" name="decoyemailforchromeautofill">
correct we wanted it to be off b/c it's a bad experience

2020-01-02 20:55 UTC, data-enabler approved these changes

2020-01-02 21:19 UTC, merged