Add enzyme & enzyme adapter for component testing
yext/answers-search-ui pull request #393
Opened 2019-12-02 17:35 UTC by Delerme

Add enzyme to dev dependencies along with jest setup and a custom enzyme adapter
for the Answers component framework. To support this, adjust a few Component
requirements and move the component registry to a static object so a mock
component manager can use the same set of components

2019-12-02 17:35 UTC, Delerme commented
will update the now obsolete component tests but wanted to get this up for CR in the meantime

2019-12-02 23:31 UTC, data-enabler requested changes
Seems like it might be worth sprinkling some more JSDoc around the new files.

2019-12-02 23:31 UTC, data-enabler commented on src/ui/components/registry.js
> + * @type {Object.<string, function>}
Even more accurate would be `{Object.<string, Component>}`

2019-12-02 23:31 UTC, data-enabler commented on src/ui/components/registry.js
> +export const COMPONENT_CLASS_LIST = [
Does this actually need to be exported?

2019-12-02 23:31 UTC, data-enabler commented on tests/setup/mockcomponentmanager.js
> +    this.renderer = new Renderers.Handlebars();
Any significance to `_core` having the leading underscore but `renderer` not? I assume we don't need to reference this from outside the class.

2019-12-02 23:31 UTC, data-enabler commented on tests/setup/mockcomponentmanager.js
> +/** @module MockComponentManager */
Been meaning to ask: does `@module` really do anything if there aren't exported functions/variables outside the class?

2019-12-02 23:31 UTC, data-enabler commented on tests/setup/enzymeadapter.js
> +    childRstNodes.push(toDomRstNode(child));
`children.map(toDomRstNode)`?

2019-12-02 23:31 UTC, data-enabler commented on tests/setup/enzymeadapter.js
> +      props['className'] = attr[i].value;
Does enzyme actually require this? Doesn't seem like the sort of thing we'd want to copy from React otherwise.

2019-12-02 23:31 UTC, data-enabler commented on tests/setup/enzymeadapter.js
> +    const text = Text.wholeText;
Should this be `domElement.wholeText`?

2019-12-03 01:54 UTC, Delerme commented on src/ui/components/registry.js
> +export const COMPONENT_CLASS_LIST = [
guess not, removed

2019-12-03 01:54 UTC, Delerme commented on src/ui/components/registry.js
> + * @type {Object.<string, function>}
true, done

2019-12-03 01:54 UTC, Delerme commented on tests/setup/enzymeadapter.js
> +    childRstNodes.push(toDomRstNode(child));
done

2019-12-03 01:54 UTC, Delerme commented on tests/setup/enzymeadapter.js
> +    const text = Text.wholeText;
yup, fixed

2019-12-03 01:54 UTC, Delerme commented on tests/setup/enzymeadapter.js
> +      props['className'] = attr[i].value;
yea it's how `hasClass` functions. I figured it's fine to support that, and `getDOMNode().classList` also works as expected so seems like no downside really

2019-12-03 01:54 UTC, Delerme commented on tests/setup/mockcomponentmanager.js
> +/** @module MockComponentManager */
I forget exactly, but it was only useful for generating jsdoc. I figure if we remove the generated jsdoc we'll probably clean these declarations then

2019-12-03 01:54 UTC, Delerme commented on tests/setup/mockcomponentmanager.js
> +    this.renderer = new Renderers.Handlebars();
was mostly copy pasta, moved to `.core` since tests may want to access each to mess with them

2019-12-03 19:58 UTC, b1lly reviewed
Just some minor nuggets:

@data-enabler for transparency

2019-12-03 19:58 UTC, b1lly commented on src/ui/components/component.js
>        this._container = DOM.query(this._parentContainer, config.container);
What happens if this is null?

2019-12-03 19:58 UTC, b1lly commented on src/ui/components/componentmanager.js
> +  static getInstance () {
This originally was meant to be a singleton, what was the advantage of making a helper that returned a new instance every time? Should we just deprecate this helper all together if we don't want it to be a singleton anymore?

2019-12-03 19:58 UTC, b1lly commented on src/ui/components/registry.js
> +];
In the future, I think all "components" should be exported from the package.

And this Manager could just do something like:

psuedo:

```
import * as COMPONENTS;

const manager = new ComponentManager();
for (component in COMPONENTS) {
  manager.register(component);
}

```

Obviously the above wont work right out of the box, but the idea being:

1. All component `classes` are exported from the package
2. The manager just automatically registers everything that was exported

2019-12-03 20:16 UTC, Delerme commented on src/ui/components/componentmanager.js
> +  static getInstance () {
This is still a singleton, you can't really make a private constructor in JS, but the getInstance method is now more inline with how singletons work in other languages. We were actually wondering why this was a singleton in the first place, if you're okay with this no longer being a singleton we can make that change next commit

2019-12-03 20:16 UTC, Delerme commented on src/ui/components/registry.js
> +];
sounds good, can you make a story for that?

2019-12-03 20:16 UTC, Delerme commented on src/ui/components/component.js
>        this._container = DOM.query(this._parentContainer, config.container);
It'll fail during the render instead of during the constructor. I think the goal going forward would be to split rendering and mounting logic from the component. Component instances should be able to be created without knowing things like what container they'll eventually make it to.

2019-12-04 21:28 UTC, data-enabler requested changes

2019-12-04 21:28 UTC, data-enabler commented on tests/setup/mockcomponentmanager.js
> +  create (componentType, config, analyticsReporter) {
Pretty sure this breaks a bunch of stuff. At the very least, the `create` call in `answers-umd` needs to be updated.

Alternatively, we could use the existing `setAnalyticsReporter` method on `ComponentManager`. But we shouldn't need to have both.

2019-12-04 21:28 UTC, data-enabler commented on tests/ui/components/component.js
> +    expect(div.getAttribute('data-eventtype')).toBe('test_event');
This seems like it's just testing that the template rendered, and isn't really relevant to testing the analytics functionality.

2019-12-04 21:28 UTC, data-enabler commented on tests/ui/components/component.js
> +    expect(div.getAttribute('data-is-analytics-attached')).toBe('true');
This feels like it's testing the implementation.

2019-12-06 19:23 UTC, Delerme commented on tests/setup/mockcomponentmanager.js
> +  create (componentType, config, analyticsReporter) {
yea I should keep them to be the same interface, updated the mock

2019-12-06 19:23 UTC, Delerme commented on tests/ui/components/component.js
> +    expect(div.getAttribute('data-eventtype')).toBe('test_event');
true, removed

2019-12-06 19:23 UTC, Delerme commented on tests/ui/components/component.js
> +    expect(div.getAttribute('data-is-analytics-attached')).toBe('true');
yup, removed

2019-12-06 19:46 UTC, data-enabler approved these changes

2019-12-06 20:34 UTC, merged