Update navigation component for oobx
yext/answers-search-ui pull request #403
Opened 2019-12-10 21:17 UTC by bwangYext

https://yexttest.atlassian.net/browse/ANS-323

TEST=auto,manual

2019-12-11 19:00 UTC, data-enabler commented on src/ui/templates/navigation/navigation.hbs
> +        role="tab"
I don't think we should be using the tab role here. These may visually look like tabs, but they're just links to separate pages.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role
In particular, there's nothing that makes sense to put in the `aria-controls` attribute.

I think just having links inside the nav element should be enough, though we should probably be using a `<ul>`.
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/navigation.html

2019-12-11 21:02 UTC, bwangYext commented on src/ui/templates/navigation/navigation.hbs
> +        role="tab"
Using `<ul>` for both main links and collapsed links. Removed role and aria-selected.

2019-12-12 20:48 UTC, bwangYext commented
Ready for review

2019-12-20 01:23 UTC, data-enabler requested changes
Honestly, there's a lot of things that this component isn't really doing correctly for keyboard navigation and screen reader support, but It's probably not worth the time to address them all, since the new team might end up rewriting things anyway.

If you're curious, W3C has a guide on how to implement components like this:
https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html

2019-12-20 01:23 UTC, data-enabler commented on README.md
> +| navigation | object | Provide navigation configuartion including tab configurations | optional |
Typo in the first "configuration"

2019-12-20 01:23 UTC, data-enabler commented on README.md
> +navigation: {
The pattern we've been using is to have init configuration objects like this in a section below Configuration Options. Here's how it was done for the `search` property: https://github.com/yext/answers/pull/379/files

2019-12-20 01:23 UTC, data-enabler commented on README.md
> +<nav class="navigation-container"></nav>
Since we use a `nav` element in the NavigationComponent template, using one for the container results in two `nav` elements. We should just change this to be a `div`; that's consistent with current Answers implementations.

2019-12-20 01:23 UTC, data-enabler commented on tests/ui/components/navigation/navigationcomponent.js
> +          return navigationConfig;
You should check that the string passed in getState is the navigation config key. This code is making an assumption about how the component uses global storage, which is fine, but if that changes then this code should throw an error.

2019-12-20 01:23 UTC, data-enabler commented on src/ui/templates/navigation/navigation.hbs
>          aria-labelledby="yxt-Nav-moreButton"
Is there a reason this element is labeled by itself?

2019-12-20 01:23 UTC, data-enabler commented on README.md
> +Tab configurations should be provided in initial configuration.
Make sure you update the sample app, so it doesn't break

2019-12-20 01:23 UTC, data-enabler commented on src/ui/components/navigation/navigationcomponent.js
> +        this.setAriaHidden('true');
If we use `visibility: hidden` instead of `opacity: 0` on `yxt-Nav-item--more`, then we don't need this. It also takes care of an issue the nav bar has currently where you can still tab to the More button even when it's hidden

2019-12-20 01:23 UTC, data-enabler commented on README.md
> +  overflowIcon: null        // optional, show this icon on the dropdown button instead when overflow
"when overflow" -> "when it overflows"
On the previous line as well.

2019-12-20 01:23 UTC, data-enabler commented on README.md
> +  mobileOverflowBehavior: 'COLLAPSE'     // optional, options which are COLLAPSE, INNERSCROLL to control if navigation shows scroll bar or dropdown for mobile
"// optional, controls if navigation shows a scroll bar or dropdown for mobile. Options are COLLAPSE and INNERSCROLL"

2019-12-20 01:23 UTC, data-enabler commented on src/ui/components/navigation/navigationcomponent.js
> +        return true;
Seems wasteful to bother bother querying the DOM if we're just going to return true in this case.

2019-12-20 01:23 UTC, data-enabler commented on src/ui/components/navigation/navigationcomponent.js
> +    this.unbindOverflowHandlers();
This should go in `onUnMount`, which should also mean that you don't need to call `bindOverflowHandlers` in `onCreate`.

2019-12-20 01:23 UTC, data-enabler commented on src/ui/components/navigation/navigationcomponent.js
> +    DOM.off(window, 'click', this.checkOutsideClick.bind(this));
In order for `removeEventListener` to work you have to pass the same function that was used in `addEventListener`. `.bind` creates a new function every time you call it.

Either call `this.checkOutsideClick = this.checkOutsideClick.bind(this);` in the constructor, or just declare it as an arrow function.

2019-12-20 01:23 UTC, data-enabler commented on src/ui/components/navigation/navigationcomponent.js
> +    DOM.on(window, 'resize', () => {
We never remove either of the resize handlers; this causes errors if you ever remove the navigation component from the page.

2019-12-20 01:23 UTC, data-enabler commented on src/ui/components/navigation/navigationcomponent.js
> +      this._checkMobileOverflowBehaviorTimer = setTimeout(this.setState.bind(this), RESIZE_DEBOUNCE);
Re-rendering and re-mounting the component every time the window changes size isn't great. I guess it's probably not worth the time to clean it up if this works as-is, but I would at least leave a TODO about it.

Currently, the `_debounceTimer` timeout never even activates, since this runs first.

2019-12-26 18:10 UTC, bwangYext commented on README.md
> +| navigation | object | Provide navigation configuartion including tab configurations | optional |
Done.

2019-12-26 18:10 UTC, bwangYext commented on README.md
> +navigation: {
Done

2019-12-26 18:10 UTC, bwangYext commented on README.md
> +<nav class="navigation-container"></nav>
Done.

2019-12-26 18:10 UTC, bwangYext commented on tests/ui/components/navigation/navigationcomponent.js
> +          return navigationConfig;
Done.

2019-12-26 18:10 UTC, bwangYext commented on src/ui/templates/navigation/navigation.hbs
>          aria-labelledby="yxt-Nav-moreButton"
Removed.

2019-12-26 18:10 UTC, bwangYext commented on src/ui/components/navigation/navigationcomponent.js
> +        this.setAriaHidden('true');
Done.

2019-12-26 18:10 UTC, bwangYext commented on README.md
> +  overflowIcon: null        // optional, show this icon on the dropdown button instead when overflow
Done.

2019-12-26 18:11 UTC, bwangYext commented on README.md
> +  mobileOverflowBehavior: 'COLLAPSE'     // optional, options which are COLLAPSE, INNERSCROLL to control if navigation shows scroll bar or dropdown for mobile
Done.

2019-12-26 18:11 UTC, bwangYext commented on src/ui/components/navigation/navigationcomponent.js
> +        return true;
Done.

2019-12-26 18:11 UTC, bwangYext commented on src/ui/components/navigation/navigationcomponent.js
> +    this.unbindOverflowHandlers();
Moved to onUnMount.

2019-12-26 18:11 UTC, bwangYext commented on src/ui/components/navigation/navigationcomponent.js
> +    DOM.off(window, 'click', this.checkOutsideClick.bind(this));
Done.

2019-12-26 18:12 UTC, bwangYext commented on src/ui/components/navigation/navigationcomponent.js
> +    DOM.on(window, 'resize', () => {
Added calls to remove both handlers.

2019-12-26 18:13 UTC, bwangYext commented on src/ui/components/navigation/navigationcomponent.js
> +      this._checkMobileOverflowBehaviorTimer = setTimeout(this.setState.bind(this), RESIZE_DEBOUNCE);
Added to do. Could you explain why _debounceTimer timeout never activates? It seems that the it is refitting nav when resize.

2019-12-26 18:37 UTC, bwangYext commented on README.md
> +Tab configurations should be provided in initial configuration.
Done.

2020-01-02 20:19 UTC, data-enabler commented on src/ui/components/navigation/navigationcomponent.js
> +      this._checkMobileOverflowBehaviorTimer = setTimeout(this.setState.bind(this), RESIZE_DEBOUNCE);
The code registers two `resize` event handlers, which get called in the order they were registered. That means that this handler gets called before the one in `bindOverflowHandlers`; Javascript is single-threaded, so the handlers get called sequentially. Both handlers call `setTimeout` with the same delay; those timeouts will also happen sequentially. In this timeout we call `setState`, which causes the component to be unmounted, then re-mounted. In `onMount` we call `unbindOverflowHandlers`, which clears the `_debounceTimer` before it gets a chance to fire.

The reason the resizing works correctly is because we also call `refitNav` in `onMount`.

2020-01-02 20:49 UTC, data-enabler requested changes

2020-01-02 20:49 UTC, data-enabler commented on README.md
> +  mobileOverflowBehavior: 'COLLAPSE'     // optional, options which are COLLAPSE, INNERSCROLL to control if navigation shows scroll bar or dropdown for mobile
Looks like this wasn't changed.

2020-01-02 20:49 UTC, data-enabler commented on src/ui/templates/navigation/navigation.hbs
> +      <ul class="yxt-Nav-modal js-yxt-navModal {{#if expanded}}is-active{{/if}}"></ul>
It's fine to leave the `aria-labelledby` on this element.

2020-01-02 21:02 UTC, bwangYext commented on src/ui/templates/navigation/navigation.hbs
> +      <ul class="yxt-Nav-modal js-yxt-navModal {{#if expanded}}is-active{{/if}}"></ul>
Done

2020-01-02 21:03 UTC, bwangYext commented on README.md
> +  mobileOverflowBehavior: 'COLLAPSE'     // optional, options which are COLLAPSE, INNERSCROLL to control if navigation shows scroll bar or dropdown for mobile
Done

2020-01-02 21:04 UTC, bwangYext commented on src/ui/components/navigation/navigationcomponent.js
> +      this._checkMobileOverflowBehaviorTimer = setTimeout(this.setState.bind(this), RESIZE_DEBOUNCE);
Thanks! Removed `_debouncerTimer`.

2020-01-02 21:42 UTC, data-enabler approved these changes

2020-01-02 21:43 UTC, merged