send analytics events for form
yext/answers-search-ui pull request #412
Opened 2019-12-12 17:16 UTC by apokellypse

2019-12-12 19:24 UTC, data-enabler requested changes

2019-12-12 19:24 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +      // we report that we are attempting to submit form data
Putting a comment before a block of code is usually a good sign that it should be pulled out into a helper function.

2019-12-12 19:24 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    this._verticalKey = config.verticalKey;
What I was trying to say before is that now that we have `verticalKey` available in the global config `ANSWERS.init()`, we don't need to set it for each individual component.

[I've suggested that in the future the global config should be passed to components](https://docs.google.com/document/d/1-iS_Z1ur3_2MMw8mIj6GCVp5m_PGmzLPSpv7mYxufX4/edit#heading=h.pifayunu5mve), but in the meantime you can retrieve it from global storage [like we do in PaginationComponent](https://github.com/yext/answers/blob/master/src/ui/components/results/paginationcomponent.js#L18)

2019-12-12 19:24 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    this._isUniversal = config.isUniversal || false;
Isn't this just `!verticalKey`?

2019-12-12 19:24 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    for (let i = 0; i < questionFields.length; i++) {
For loops are so last-year; you could use `Array.prototype.foreach` instead and not have to deal with indices. I'd suggest `for ... of`, but I think we're trying to avoid that in the SDK because it transpiles to a lot of code and bloats the IE bundle.

2019-12-12 19:24 UTC, data-enabler commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    const questionFields = DOM.queryAll(formEl, '.js-question-field');
From the discussion, it sounded like Rose only wants events to get sent when the question input itself gets focused, not name, email, etc.

I'd suggest the `'[name="questionText"]'` selector.

2019-12-12 21:56 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    for (let i = 0; i < questionFields.length; i++) {
Thanks for the note, I didn't know about that caveat with for...of, so that's a cool fact.

Turns out after limiting the focus event to the question itself iteration won't be necessary, so I won't need to use foreach or for after all.

2019-12-12 21:57 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    const questionFields = DOM.queryAll(formEl, '.js-question-field');
there is an existing selector js-question-text that was already hooked up with an event that I can also use

2019-12-12 21:58 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    this._isUniversal = config.isUniversal || false;
Could there be a situation where the client messes up and defines verticalKey but the component was added by UniversalResults, so config.isUniversal is true? Or, pending the new behavior with verticalKey available in the global config, is that scenario not possible?

2019-12-12 21:58 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +      // we report that we are attempting to submit form data
good point, will do

2019-12-12 22:07 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    this._verticalKey = config.verticalKey;
ahhh what I thought was that it was going to happen, not that I could use it now. Thanks for the links.

2019-12-13 17:40 UTC, apokellypse commented on src/ui/components/questions/questionsubmissioncomponent.js
> +    this._isUniversal = config.isUniversal || false;
turns out QA component isn't a child of UniversalResults, so it doesn't have a meaningful isUniversal value. will use !verticalKey instead

2019-12-13 18:28 UTC, data-enabler approved these changes

2019-12-13 18:44 UTC, merged