change default text values in qa component and update readme. now sup…
yext/answers-search-ui pull request #414
Opened 2019-12-13 20:17 UTC by apokellypse

…ports expanded state as well.

2019-12-13 22:12 UTC, data-enabler requested changes

2019-12-13 22:12 UTC, data-enabler commented on README.md
> +// Unless noted, fields are optional and show default values
`container` is required as well

2019-12-13 22:12 UTC, data-enabler commented on README.md
> +  language: 'en',
Currently checking with Rose if we even want to keep this config options, but we can leave it be in the meantime.

2019-12-13 22:20 UTC, data-enabler commented on README.md
> +  language: 'en',
Heard back from her and it doesn't sound like there's a good reason for it. So I guess we're free to use the global config locale, although I am now remembering that that isn't an easy thing to do... 😩

2019-12-30 16:28 UTC, apokellypse commented on README.md
> +// Unless noted, fields are optional and show default values
thanks, I will add a comment

2019-12-30 16:30 UTC, apokellypse commented on README.md
> +  language: 'en',
In questionsubmissioncomponent we already have
`
'questionLanguage': this._config.language,`

which doesn't seem that hard; am I missing something

2020-01-02 17:58 UTC, data-enabler requested changes

2020-01-02 17:58 UTC, data-enabler commented on README.md
> +  language: 'en',
Pretty sure that refers to the language passed in with the component config, not the language set on the global config. What we've been doing for now is to store parts of the global config in global storage (see PaginationComponent).

2020-01-02 19:04 UTC, apokellypse commented on README.md
> +  language: 'en',
Ah I see, thanks! Most recent commit should have this corrected.

2020-01-02 19:46 UTC, data-enabler requested changes

2020-01-02 19:46 UTC, data-enabler commented on sample-app/public/app.js
> +    locale: locale,
You should set a locale in `sample-config.json`. Seems like the code as-is will pass `locale: undefined` to the SDK, and the SDK currently doesn't validate locales.

Also, you can just to `locale,` instead of `locale: locale,`, to be consistent with the other lines.

2020-01-02 20:20 UTC, apokellypse commented on sample-app/public/app.js
> +    locale: locale,
sgtm!

2020-01-02 20:52 UTC, data-enabler approved these changes

2020-01-02 21:05 UTC, merged