Add filterbox and filteroptions component
yext/answers-search-ui pull request #42
Opened 2019-07-08 20:52 UTC by Delerme

Adds the FilterBox component which manages a set of filters, searching with them
when applied, and the static filter component FilterOptions which renders a set
of radio buttons or checkboxes which each correspond to a filter.

2019-07-08 20:52 UTC, Delerme commented
Working on tests but wanted to get eyes on for feedback

2019-07-08 21:37 UTC, b1lly reviewed
Savage mode. Mostly stylistic nits. I do have some minor functional thoughts but i'll do that in a separate review. Nothing major so the design/approach shouldn't change much.

2019-07-08 21:37 UTC, b1lly commented on src/core/models/filter.js
> +   */
What are your thoughts on also adding the @return {Filter} annotation for each of this?

2019-07-08 21:37 UTC, b1lly commented on src/core/models/filter.js
> +  static group (...filters) {
in ES6, destructing these things is actually pretty slow. The ES6 implementation did change how this works to make it faster, but I can't remember how many browsers adopted it, which is why I avoided it.

Anyway, its much faster to access the arguments object (which actually is slow itself, inherently) but better than this.

If destructing isn't a problem anymore its worth keeping, because the syntax is beautiful. But just worth considering.

2019-07-08 21:37 UTC, b1lly commented on src/core/models/filter.js
Lets add some unit tests for these class.

2019-07-08 21:37 UTC, b1lly commented on src/core/models/filter.js
> +  static _makeFilter (field, matcher, value) {
our factory "pattern" is typically a static method named "from (...arguments)".

2019-07-08 21:37 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> + */
just add the

@module FilterBoxComponent as part of the top level class documentation instead of a separate multi-line-comment.
```
/**
  * Describe behavior
  * @module FilterBoxComponent
  * @class
  */
```
It's probably worth always adding both, but I don't feel strongly.

2019-07-08 21:37 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +  }
Can we annotate all of these properties and values so that they show up in the jsdoc properly as well?

```
/**
  * Usage
  * @type {Object}
  * @default 'Value'
  */
```

2019-07-08 21:37 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +/** @module FilterOptionsComponent */
same comment

2019-07-08 21:37 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +const controls = {
Style nit: 

CONTROLS

All constants in the "global scope" should be capitalized.

That way when im reading code below I know its not a local variable.

2019-07-08 21:37 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +    this._onChange = opts.onChange || function () {};
jsdoc

2019-07-08 21:37 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +        'FilterOptions component requires options to be provided',
usually `options` are not "required" . Maybe name it config?

2019-07-08 21:37 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +};
should the selectors be configurable? 

Perhaps you can give me some sample usages of your interface so I can look at it, at a high level.

2019-07-09 18:22 UTC, Delerme commented on src/core/models/filter.js
> +   */
done

2019-07-09 18:22 UTC, Delerme commented on src/core/models/filter.js
> +  static group (...filters) {
we use babel so all es6 features are just for the syntax, none of it makes it to the browser

2019-07-09 18:22 UTC, Delerme commented on src/core/models/filter.js
done

2019-07-09 18:22 UTC, Delerme commented on src/core/models/filter.js
> +  static _makeFilter (field, matcher, value) {
done

2019-07-09 18:22 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> + */
That doesn't seem to work. Based on the jsdoc docs the current format is correct
https://jsdoc.app/howto-es2015-modules.html
https://jsdoc.app/howto-es2015-classes.html

2019-07-09 18:22 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +  }
done

2019-07-09 18:22 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +/** @module FilterOptionsComponent */
see above

2019-07-09 18:22 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +const controls = {
done

2019-07-09 18:22 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +    this._onChange = opts.onChange || function () {};
done

2019-07-09 18:22 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +        'FilterOptions component requires options to be provided',
yea, though this is the FilterOptions component so passing in `options` seems to make more sense, and I think it's more clear than `config`

2019-07-09 18:22 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +};
yup done

2019-07-09 18:23 UTC, Delerme commented
I tried to get some tests for the components but ran into trouble with the rendering and mounting, and think it's probably not worth blocking this. I think we should figure that out before scalars though

2019-07-10 21:21 UTC, b1lly requested changes
Dude super great!

The only thing I would suggest is reducing the dependency of the component on the DOM. The Component should be the source of truth for the state, which handles the rendering. The DOM integration (e.g. change event handling), should then update the local state to reflect the state of the DOM.

Then the component could work off the local state, instead of having to query the DOM for the state whenever it needs to do things (e.g. persist to local storage, or bubble up the state to external code).

It's also much easier to test state then the DOM, and also easier to work and reason about state in memory than state in DOM.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +  _applyFilters () {
Minor nit.

Might be worth separating this method into two.

1. persistFilters to storage.
2. trigger a search, using filters.

that'd make it easier to test in the future as well.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> + */
@extends Component

2019-07-10 21:21 UTC, b1lly commented on src/core/models/filter.js
Can we give an example in documentation with this filter object structure might look like? Or is it possible to set all the defaults to null?
```
this.$or = null;

this.$and = null;
```

Just so that when im reading through this code I have a reference of what some of these filter objects can look like without having to dig through the backend.

2019-07-10 21:21 UTC, b1lly commented on src/core/models/filter.js
> +      const key = Object.keys(filter)[0];
Just a question. Is it possible for a filter to have an `and` and an `or`? or is it only ever going to be one or the other? If not, the Filter object probably needs some better JSDoc describing what it represents. See above comment.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +     * @type {Component[]}
Is this new sytax? It used to be `{Array.<Component>}`

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +      const button = DOM.query(this._container, '.js-yext-filterbox-apply');
we might want to make this selector configurable as well.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +          onChange: (f) => {
filter

I know golang code style likes to use 1 variable names, but lets let the minified handle that and keep our stuff readable.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +    const combinedFilter = validFilters.length > 1 ? Filter.and(...validFilters) : validFilters[0];
ternaries are great but they hurt readability. I think we should heir on using these sparingly. Can we update this to be its expanded form? Here and below?

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> + * Renders a set of options, each one representing a filter in a search.
What do you think about defining an example configuration in the JSdoc for all of our components moving forward? That way when people open the class they know how to use it. I can take the time to update all the existing components JSDoc if you think it'd be good to have.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +const SUPPORTED_CONTROLS = [
```
/**
 * @type {Array.<string>}
 */
```

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +     * @type {object[]}
Unless this is a new JSDoc thing can you update it everywhere? Otherwise ignore my comment.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +    elements.forEach(e => DOM.on(e, 'change', () => this._applyFilter()));
You might be able to just do all this using event delegation instead of binding to each one.

```
DOM.delegate(this._container, this._optionSelector, 'change', () => {

});
```

Also, we can update the `DOM.on(...)` method if we want to support multiple selectors to make usage and the interface easier, if you prefer.

2019-07-10 21:21 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +  _applyFilter () {
I think applyFilter is a bad name here. I also think this method could be broken into two separate unit testable operations if it were to stay this way.

Separately, I think there's a way to provide the values from the onChange handler instead of having to requery the DOM to parse the values. That way this would be unit testable without having to depending on the DOM.

For instance,

One approach would be to render the DOM based on the local state. Whenever the DOM changes, update the local state. And when you ready to use the state, you pull it from local state instead of the DOM.

So overall, the goal would be to make the component be the source of truth for the state of the component options. When the DOM changes, it updates the source of truth. Then all these DOM dependencies go away and its easier to unit test.

We can talk offline if this is a little confusing.

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> + */
done

2019-07-11 17:45 UTC, Delerme commented on src/core/models/filter.js
it's kinda arbitrary and the spec for it is kind of intense, I guess I'll just link to our api docs which has more details then we could ever provide

2019-07-11 17:45 UTC, Delerme commented on src/core/models/filter.js
> +      const key = Object.keys(filter)[0];
yea that's what this function does, creates a single filter representing the combination of other filters. As mentioned above I just linked to our api docs which better specifies the structure of a filter

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +     * @type {Component[]}
maybe, I've always used it 
https://jsdoc.app/tags-type.html

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +          onChange: (f) => {
done

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +      const button = DOM.query(this._container, '.js-yext-filterbox-apply');
yup done

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +    const combinedFilter = validFilters.length > 1 ? Filter.and(...validFilters) : validFilters[0];
what if I do them on separate lines? I agree the single line is hard to read, but I think the multiline form is easier to comprehend than a full if statement because it doesn't require a variable reassignment. Check now and if you still don't like it I'll make a full if

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +  _applyFilters () {
done

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +const SUPPORTED_CONTROLS = [
done

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> + * Renders a set of options, each one representing a filter in a search.
don't we do that already in the README? Went ahead and added these components there

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +     * @type {object[]}
Don't know if it's new, I've always used it. Seems more readable than the alternative so updated it everywhere

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +    elements.forEach(e => DOM.on(e, 'change', () => this._applyFilter()));
yup meant to switch to delegate after POC, done.

2019-07-11 17:45 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +  _applyFilter () {
done

2019-07-11 17:58 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +     * @type {Component[]}
Ah, ok. I've always down the former way. Whatever we decide should be consistent across the library though. So if you haven't already done a lot of the Component[] syntax maybe just update it here? Or we can switch all the other docs to follow this pattern at another point.

2019-07-11 18:00 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> + * Renders a set of options, each one representing a filter in a search.
We do. I was saying as a developer sometimes its much easier to just look at the top of the file to see its usage instead of having to open a separate doc. It's just a convenience thing. And the README will become big and hairy over time, which is the only reason I was suggesting it.

Either way, SGTM, was more of a suggestion.

2019-07-11 18:36 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> + * Renders a set of options, each one representing a filter in a search.
alright I'll start thinking about something and punt to another commit

2019-07-11 18:36 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +     * @type {Component[]}
I already switched all Array.<x> usages to x[] in this commit

2019-07-11 21:06 UTC, b1lly reviewed
Savage. Last comment.

Otherwise LGTM.

2019-07-11 21:06 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +          onChange: (f) => {
Was it done?

2019-07-11 21:06 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +    const allFilters = this.core.storage.getAll(StorageKeys.FILTER);
might be better for this to be provided as input for unit testing purposes.

But otherwise LGTM

2019-07-11 21:24 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +    const allFilters = this.core.storage.getAll(StorageKeys.FILTER);
eh it'll have to be mocked at some level, may as well be here

2019-07-11 21:30 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +    const allFilters = this.core.storage.getAll(StorageKeys.FILTER);
In this case you'll need two mocks and need to set state in the storage.

By just providing the filters as input, all you need to do is mock the verticalSearch and provide the input. The behavior to test is the search with filters, not the storage.

Either way nbd.

2019-07-11 21:31 UTC, b1lly approved these changes

2019-07-11 21:31 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +          onChange: (f) => {
hmm, must have got wrecked by my rebase, try now

2019-07-11 21:32 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +    const allFilters = this.core.storage.getAll(StorageKeys.FILTER);
punting for now

2019-07-11 21:37 UTC, merged