Storage keys uses enum
yext/answers-search-ui pull request #44
Opened 2019-07-09 15:38 UTC by b1lly

2019-07-09 18:59 UTC, Delerme requested changes

2019-07-09 18:59 UTC, Delerme commented on src/core/storage/storagekeys.js
> +export const StorageKeys = {
jsdoc and maybe export default?

2019-07-09 18:59 UTC, Delerme commented on src/ui/components/search/filterpickercomponent.js
> +    this._templateName = 'search/filterpicker';
this is actually meant to be search, and I was supposed to delete filterpicker.hbs, feel free to delete in this commit

2019-07-09 21:49 UTC, b1lly commented on src/ui/components/search/filterpickercomponent.js
> +    this._templateName = 'search/filterpicker';
I didn't want the filter picker and the search templates to be shared. It's possible they diverge, and we cant guarantee that someone in the future is going to want to customize one and not the other.

2019-07-10 16:13 UTC, b1lly commented on src/core/storage/storagekeys.js
> +export const StorageKeys = {
done. it's possible that we move the keys into the storage module as a named export in the future instead of having two files, though.

2019-07-10 16:20 UTC, Delerme approved these changes

2019-07-10 16:20 UTC, Delerme commented on src/ui/components/search/filterpickercomponent.js
> +    this._templateName = 'search/filterpicker';
cool, that worked out then

2019-07-10 16:20 UTC, Delerme commented on src/core/storage/storagekeys.js
> +export const StorageKeys = {
yea makes sense

2019-07-10 17:00 UTC, merged