Update docs, clean up bugs, and rename filterpicker
yext/answers-search-ui pull request #45
Opened 2019-07-09 17:57 UTC by b1lly

2019-07-09 19:09 UTC, Delerme requested changes
nice

2019-07-09 19:09 UTC, Delerme commented on src/core/errors/errors.js
> + * @extends Error
duplicate @extends

2019-07-09 19:09 UTC, Delerme commented on src/core/errors/errors.js
> + * AnswersCoreError represents errors for precondition failures
maybe just specify precondition failures in the core, not all precondition failures

2019-07-09 21:47 UTC, b1lly commented on src/core/errors/errors.js
> + * @extends Error
done.

2019-07-09 21:47 UTC, b1lly commented on src/core/errors/errors.js
> + * AnswersCoreError represents errors for precondition failures
done.

2019-07-09 21:50 UTC, Delerme submitted a review, later dismissed

2019-07-09 21:50 UTC, Delerme commented
Be sure to squash & rebase

2019-07-10 16:21 UTC, Delerme requested changes

2019-07-10 16:21 UTC, Delerme commented on src/ui/components/search/filtersearchcomponent.js
> +/** @module FilterSearchComponent */
can you also rename the handlebars template

2019-07-10 17:04 UTC, b1lly commented on src/ui/components/search/filtersearchcomponent.js
> +/** @module FilterSearchComponent */
done.

2019-07-10 17:18 UTC, Delerme approved these changes

2019-07-10 17:20 UTC, merged