Implement SortOptionsComponent
yext/answers-search-ui pull request #458
Opened 2020-01-16 23:54 UTC by oshi97

This commit implements the sort options component for adding a
filter component that lets users filter vertical results
based on configuration.

TEST=manual
Ran test site with component locally

2020-01-17 14:45 UTC, tmeyer2115 commented on src/ui/components/component.js
> +      // console.log('init', this);
Remove.

2020-01-17 14:45 UTC, tmeyer2115 commented on src/ui/components/component.js
> +        // console.log('uddate', this);
Remove.

2020-01-17 14:45 UTC, tmeyer2115 commented on src/ui/sass/modules/_SortOptions.scss
> +.yxt-SortOptions {
Was this all the styling necessary to match the mocks?

2020-01-17 14:45 UTC, tmeyer2115 commented on src/core/core.js
> +        sortBys: JSON.stringify(this.globalStorage.getState(StorageKeys.SORT_BY) || undefined)
Is the || undefined necessary here? Won't getState(StorageKeys.SORT_BY) be undefined if sortBys are not present in the state?

2020-01-17 14:45 UTC, tmeyer2115 commented on src/core/core.js
> +    this.globalStorage.set(StorageKeys.SORT_BY, sortBys);
Do we also want the sortBy info to wind up in persistent storage? Does it do this already?

2020-01-17 14:45 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +export default class SortOptionsComponent extends Component {
We'll want to add Jest tests for this component. We should try and have these tests exercise as much of the component's functionality as possible. Take a look at the tests that already exist in tests/ui/components for some examples.

2020-01-17 21:07 UTC, oshi97 commented on src/core/core.js
> +        sortBys: JSON.stringify(this.globalStorage.getState(StorageKeys.SORT_BY) || undefined)
it's sorta weird but getState returns null when the key isn't found, and JSON.stringify(null) returns 'null' rather than null

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +  // Optional, The label used for the “default” sort (aka sort the order provided by the config).
"(aka the sort specified by the experience config)"?

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +  for (let i = 0; i < updatedConfig.options.length; i++) {
Minor nit, but let's use updatedConfig.options.forEach

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    const option = updatedConfig.options[i];
Will this loop also modify the config.options? I know arrays in JS are passed by copy of a reference. I'm not sure if that also applies to assignments (like the one on line 156). We'd definitely want to avoid mutating the input config.

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    const isField = OPTION_TYPES.indexOf(option.type) === -1;
Why don't we have FIELD as part of OPTION_TYPES? Seems like it would make this cleaner.

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    option.label = option.label || (isField ? 'FIELD' : option.type);
I think the default logic here is if label is not present: 
- Display name of the field (i.e. "First Name") if option corresponds to a field. Do we have access to this info? 
- Distance if the type is ENTITY_DISTANCE
- Relevance if the type is RELEVANCE
Not sure what the display name should be for RELEVANCE_RANDOM. May be a question for Rose

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    if (this.showMore && !this.allShown) {
I think things might be clearer if this conditional was just if (this.hideExcessOptions) { blah }. We could replace allShown with hideExcessOptions. The logic for initializing hideExcessOptions would be: 
this.showMore && # of options > limit.
Then we could toggle hideExcessOptions like you have on line 96.

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    if (this._searchOnChange) {
How does the searchOnChange behavior work elsewhere? Do we need to have the this.core.setSortBys call before we call this._search()?

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +        if (index !== -1) {
What does the value of -1 correspond to? Nothing selected?

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +  updateSelectedOption () {
Is it not possible to move this logic to the HBS template? I think there would be a couple ways to do this. One would be to give the options an isSelected property. Another way would be to pass currentlySelectedOption to the template. In the template, you'd conditionally set 'checked'.

2020-01-21 14:10 UTC, tmeyer2115 commented on src/ui/templates/controls/sortoptions.hbs
> +    <button class="yxt-SortOptions-showToggle">
showMoreToggle?

2020-01-21 22:35 UTC, oshi97 commented on src/ui/sass/modules/_SortOptions.scss
> +.yxt-SortOptions {
nope but luckily looks like filteroptions has identical styling

2020-01-21 22:35 UTC, oshi97 commented on src/core/core.js
> +    this.globalStorage.set(StorageKeys.SORT_BY, sortBys);
yes

2020-01-21 22:35 UTC, oshi97 commented on src/core/core.js
> +    this.globalStorage.set(StorageKeys.SORT_BY, sortBys);
*Yes we want it no it doesn't do it already

2020-01-21 22:36 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +export default class SortOptionsComponent extends Component {
I had a lot of fun adding tests, not quite sure why might need to see some kind of therapist

2020-01-21 22:37 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +  // Optional, The label used for the “default” sort (aka sort the order provided by the config).
english hard

2020-01-21 22:39 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +  for (let i = 0; i < updatedConfig.options.length; i++) {
was a little worried about "Modifying local variable from inside lambda" but I guess that's just a java issue

2020-01-21 22:44 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    const option = updatedConfig.options[i];
Yes it will mutate the input config

2020-01-21 22:56 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    option.label = option.label || (isField ? 'FIELD' : option.type);
Don't think we can get the name of the field without either adding a hardcoded map or making some call, will ask rose about RELEVANCE_RANDOM

2020-01-21 23:10 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    if (this.showMore && !this.allShown) {
Yes sounds good to me

2020-01-21 23:10 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +        if (index !== -1) {
Yeah default value

2020-01-21 23:14 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    if (this._searchOnChange) {
The only other filter this is implemented on is the geolocationfilter, which runs a search every time after it updates persistent/global storage. We need to call this.core.setSortBys (which just updates global storage) so the search has the updated filter value.

2020-01-21 23:36 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +  updateSelectedOption () {
Yeah, it's probably a good thing this came up because it forced me to clean up the default logic to not use -1

2020-01-21 23:37 UTC, oshi97 commented on src/ui/templates/controls/sortoptions.hbs
> +    <button class="yxt-SortOptions-showToggle">
Think this is fine as it is since it's more for whether or not the option is enabled in config, maybe shouldShowMore?

2020-01-22 14:13 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    option.label = option.label || (isField ? 'FIELD' : option.type);
According to the spec, if it's a field, the default should be the display name. Talk with Rose and see how she wants to proceed, given that we don't have access to that info.

2020-01-22 15:06 UTC, tmeyer2115 commented on src/core/core.js
> +  setSortBy (namespace, sortBy) {
Is the namespace what is used to link this to a particular SearchBar?

2020-01-22 15:06 UTC, tmeyer2115 commented on src/core/core.js
> +      this.globalStorage.delete(`${StorageKeys.SORT_BY}.${namespace}`);
Is this behavior we rely on where we set sortBy to null to delete? The other setters in core don't implement this kind of deleting behavior. How do we clear values for those things (such as filter)?

2020-01-22 15:06 UTC, tmeyer2115 commented on src/core/core.js
> +        sortBys: JSON.stringify(this.globalStorage.getAll(StorageKeys.SORT_BY))
Do we need to scope this using a namespace?

2020-01-22 15:06 UTC, tmeyer2115 commented on src/core/search/searchapi.js
> +  verticalSearch (verticalKey, { input, filter, facetFilter, limit, offset, id, geolocation, isDynamicFiltersEnabled, skipSpellCheck, queryTrigger, sessionTrackingEnabled, sortBys }) {
Can we have multiple sortBys here or only the one?

2020-01-22 15:06 UTC, tmeyer2115 commented on src/ui/components/filters/filterboxcomponent.js
> +    /**
Lets make the integration with Filterbox a separate PR. I think it would be good to break the commits up into: 
- Create a stand-alone SortOptions.
- Integrate SortOptions into Filterbox.
Whenever it makes sense, I think it's good to break things into multiple, smaller commits.

2020-01-22 15:06 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this.hideExcessOptions = this.showMore;
Would the default logic be:
this.hideExcessOptions = this.showMore && # of options > showMoreLimit?

2020-01-22 15:06 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    const optionIndex = parseInt(this.core.globalStorage.getState(`${this.name}`)) || 0;
Does there need to be a StorageKeys.SORT_BY here?

2020-01-22 15:06 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this.currentlySelectedOption = optionIndex;
Minor nit, but let's call this selectedOptionIndex or some such thing. Calling it currentlySelectedOption makes me think it's an option object.

2020-01-22 15:06 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +      this.core.setSortBy(this.name, null);
Do we need to explicitly handle the optionIndex of 0 case? Will it cause problems on the backend if we send the same sortBy as the default sort?

2020-01-22 15:06 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    // Run additional on change function, either from user config or FilterBox
We'll need to add a section to the README about this new component. In that section, we should make clear that the onChange handler is run after the search (if searchOnChange is true).

2020-01-22 15:06 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +      facetFilter: JSON.stringify(facetFilter)
Do we need to pass the sortBy here too?

2020-01-22 16:18 UTC, oshi97 commented on src/core/core.js
> +      this.globalStorage.delete(`${StorageKeys.SORT_BY}.${namespace}`);
I think they just call delete directly, maybe a deleteSortBy method would be better?

2020-01-22 16:22 UTC, oshi97 commented on src/core/search/searchapi.js
> +  verticalSearch (verticalKey, { input, filter, facetFilter, limit, offset, id, geolocation, isDynamicFiltersEnabled, skipSpellCheck, queryTrigger, sessionTrackingEnabled, sortBys }) {
I just wanted to match the request param name, but I do need to change the code to restrict it to just option in the array at a time

2020-01-22 16:22 UTC, oshi97 commented on src/ui/components/filters/filterboxcomponent.js
> +    /**
Sure

2020-01-22 16:26 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    const optionIndex = parseInt(this.core.globalStorage.getState(`${this.name}`)) || 0;
This was just to initialize the component from persistent storage, but it seemed like the current pattern in the code was to only use persistent storage to seed global store and then getState off of global storage

2020-01-22 16:30 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +      this.core.setSortBy(this.name, null);
Yeah if I send the backend an option with just label or even as an empty { } it returns an error, I could move the massaging to the setSortBy method though?

2020-01-22 16:49 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +      facetFilter: JSON.stringify(facetFilter)
I wanted to put the getting of the sortBys from global storage inside of verticalSearch instead of outside of it since that doesn't seem like something most components should be worried about

2020-01-22 17:29 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    option.label = option.label || (isField ? 'FIELD' : option.type);
decided to make label required

2020-01-22 17:35 UTC, oshi97 commented on src/ui/components/filters/filterboxcomponent.js
> +    /**
sure

2020-01-22 17:35 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this.hideExcessOptions = this.showMore;
I think if the component can display all options without going over the limit showMore should be false, and no button should be rendered at all

2020-01-22 17:36 UTC, oshi97 commented on src/ui/templates/controls/sortoptions.hbs
> +    <button class="yxt-SortOptions-showToggle">
Sorry this statement isn't completely correct, right now it's for whether some kind of show more/show less button needs to be rendered at all

2020-01-22 18:49 UTC, b1lly requested changes

2020-01-22 18:49 UTC, b1lly commented on src/ui/components/filters/sortoptionscomponent.js
> +    this._config = assignDefaults(config);
can you not do

super(assignDefaults(config), systemConfig));?

2020-01-22 18:49 UTC, b1lly commented on src/ui/components/filters/sortoptionscomponent.js
> +    this.optionSelector = this._config.optionSelector;
Is there a reason these are needed? since they are already part of the config?

2020-01-22 18:49 UTC, b1lly commented on src/ui/components/filters/sortoptionscomponent.js
> +      optionSelector: this._config.optionSelector
you shouldn't need ANY of this, because the template should already have access to the config object.

In the template, you'd do something like `{{_config.optionSelector}}`

2020-01-22 19:28 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    const optionIndex = parseInt(this.core.globalStorage.getState(`${this.name}`)) || 0;
after a little thinking I think ideally we would store this in persistent storage as this.name -> array containing necessary args from persistent store, have an additional constructor argument called something like ...persistentState, and then in during ComponentManager.create get the components persistentState array and pass that in

2020-01-22 19:30 UTC, oshi97 commented on src/core/core.js
> +  setSortBy (namespace, sortBy) {
after talking with rose we decided on not worrying about mutltiple sort options for now

2020-01-22 20:12 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +      optionSelector: this._config.optionSelector
I wanted to be explicit about which fields were used by the template if somebody else came along and tried to understand the code

2020-01-22 20:13 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this._config = assignDefaults(config);
I didn't want to run any code before calling the inherited constructor but yeah I think I could do that

2020-01-22 20:23 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this.optionSelector = this._config.optionSelector;
I wanted to be explicit about which fields were being used by the template

2020-01-22 22:04 UTC, b1lly submitted a review, later dismissed

2020-01-22 22:04 UTC, b1lly commented on src/ui/components/filters/sortoptionscomponent.js
> +      optionSelector: this._config.optionSelector
Part of the design is that all configuration options can be used by templates. Regardless of what you're doing here, they're all still available within the template via the config object.

What you're doing HERE is merging configuration options with template data instead of keeping the concerns separate.

By using the mechanism that exists for configuration and templates, you're saving yourself a ton of boilerplate in the class, and helping to keep the concerns separate. I believe it's EASIER to read a template and see anything that is prefixed with `{{_config.foo}}` and understand that its configuration, versus reading `{{foo}}`.

It's also clearer when reading through the class, to understand what properties are configuration, because you'd access them through `this._config.foo`

Take a look at this example:
https://github.com/yext/answers/blob/master/src/ui/components/questions/questionsubmissioncomponent.js

If you follow the pattern there, you can create two objects if you'd like:

```
const DEFAULT_CONFIG = {};

const TEMPLATE_CONFIG = {}
```

That would give the people reading the component the understanding of which ones are for which, even though they'd still all be available everywhere... but at least your being organized and explicit about their purpose in the definition.

2020-01-22 22:08 UTC, tmeyer2115 requested changes

2020-01-22 22:08 UTC, tmeyer2115 commented on README.md
> +There may only one sort options component per page.
Currently, there may be only one of these components per page.

2020-01-22 22:08 UTC, tmeyer2115 commented on src/core/core.js
> +    this.globalStorage.set(`${StorageKeys.SORT_BYS}`, JSON.stringify(sortBys));
Don't think you need a template string here.

2020-01-22 22:08 UTC, tmeyer2115 commented on src/core/core.js
> +    this.globalStorage.delete(`${StorageKeys.SORT_BYS}`);
Same.

2020-01-22 22:08 UTC, tmeyer2115 commented on src/ui/components/filters/filterboxcomponent.js
> +    const query = this.core.globalStorage.getState(StorageKeys.QUERY) || '';
Are these changes needed for the standalone SortOptions component?

2020-01-22 22:08 UTC, tmeyer2115 commented on src/ui/components/filters/filteroptionscomponent.js
> +    this.showReset = config.showReset && this.options.length > 0;
Same q about being needed for the standalone component

2020-01-22 22:08 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this._config = assignDefaults(config);
Yeah, lets go with Billy's suggestion. I think that's good practice, we can view assignDefaults as creating a "sane" config. We'd want to pass that "sane" config to the super too.

2020-01-22 22:08 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this.optionSelector = this._config.optionSelector;
Having them explicit like this breaks the pattern we follow in our other components (where we access them in the template via _config.). It adds a lot of unnecessary info to our state. Architecturally, I believe things specified in the config should not be duplicated in the state's data. This isn't how all of the components work, but is how the newer ones (such as QuestionSubmission) do. I think this is a pattern we want to follow from now on.

2020-01-22 22:08 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    if (this._searchOnChange) {
Ack.

2020-01-22 22:08 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +function throwConfigError (message) {
Minor nit, but lets move all these functions into the class.

2020-01-22 22:43 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this.optionSelector = this._config.optionSelector;
Yeah I'm dumb changing it is way cleaner

2020-01-22 22:44 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +      optionSelector: this._config.optionSelector
yeah it was much cleaner to use _config, thanks :)

2020-01-22 22:48 UTC, oshi97 commented on src/ui/components/filters/filterboxcomponent.js
> +    const query = this.core.globalStorage.getState(StorageKeys.QUERY) || '';
no, I can put the bugfix in a separate pr

2020-01-22 23:23 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +    this._config = assignDefaults(config);
I thought I was doing this._config = assignDefaults(this._config) but I'll still change it to what Billy suggested

2020-01-22 23:47 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +function throwConfigError (message) {
honestly this probably shouldn't have a method

2020-01-22 23:50 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +function throwConfigError (message) {
don't think I can move assignDefaults into the class since I have to call this before super if I do that?

2020-01-23 15:24 UTC, oshi97 commented on src/ui/components/filters/sortoptionscomponent.js
> +function throwConfigError (message) {
'this' the javascript keyword sorry if that was unclear

2020-01-24 13:42 UTC, tmeyer2115 requested changes

2020-01-24 13:42 UTC, tmeyer2115 commented on README.md
>     - [QASubmission Component](#qa-submission-component)
The PR is attempting to merge the SortOptions stuff directly into master. We want to merge this into v0.12.1. I'm not sure if Git lets you edit the target of a PR. May need to make a new one.

2020-01-24 13:42 UTC, tmeyer2115 commented on src/ui/components/filters/filterboxcomponent.js
> +          showMore: this.showMore,
Do we need to make any changes to the filterbox in this PR? I think it would be better to hold off on the integration with FilterBox and add that as a separate PR.

2020-01-24 13:42 UTC, tmeyer2115 commented on src/ui/components/filters/sortoptionscomponent.js
> +    console.log(this);
Remove.

2020-01-24 13:42 UTC, tmeyer2115 commented on src/ui/sass/modules/_SortOptions.scss
> +    margin: 12px 0;
We should be trying to use variables as much as possible instead of hardcoding px. Sometimes making something a variable doesn't make a whole lot of sense, but we should always be looking for opportunities to use them. Here, for instance we use 12px in a few different places. Might be good then to create a common size variable. That variable should be related to sizing in _layout.scss.

2020-01-24 13:42 UTC, tmeyer2115 commented on src/ui/sass/modules/_SortOptions.scss
> +    margin: 12px 0;
One example of not really needing a var would be 0px.

2020-01-24 13:42 UTC, tmeyer2115 commented on src/ui/sass/modules/_SortOptions.scss
> +    height: 40px;
Should we be hard coding width and height here? Does it change on mobile?

2020-01-24 13:42 UTC, tmeyer2115 commented on src/ui/templates/controls/sortoptions.hbs
> +    <div class='yxt-SortOptions-legendLabel'>
Do we need this inner div or can we just have <legend class=...>{{_config.label}}</legend>?

2020-01-24 13:42 UTC, tmeyer2115 commented on src/ui/templates/controls/sortoptions.hbs
> +  {{#if _config.showReset}}
Rose wants to only show reset if showReset is true and the default value isn't selected. In the component, then, maybe the showReset we pass in isn't the _config.showReset, but a showReset living in state that's computed according to the way Rose specified.

2020-01-24 15:18 UTC, oshi97 commented on src/ui/components/filters/filterboxcomponent.js
> +          showMore: this.showMore,
oh this was more of a bugfix but yeah I'll move everything off

2020-01-24 15:20 UTC, oshi97 commented on README.md
>     - [QASubmission Component](#qa-submission-component)
updated

2020-01-24 15:21 UTC, oshi97 commented on src/ui/sass/modules/_SortOptions.scss
> +    margin: 12px 0;
ok got it

2020-01-24 15:24 UTC, oshi97 commented on src/ui/sass/modules/_SortOptions.scss
> +    height: 40px;
I just copied the css from filterbox + filteroptions but probably shouldn't be hard coded

2020-01-24 15:45 UTC, oshi97 commented on src/ui/templates/controls/sortoptions.hbs
> +    <div class='yxt-SortOptions-legendLabel'>
there's some styling I think I want to be specific to it

2020-01-24 16:56 UTC, tmeyer2115 approved these changes

2020-01-24 18:44 UTC, merged