Pass sessionTrackingEnabled with all non-Analytics API requests
yext/answers-search-ui pull request #463
Opened 2020-01-21 20:23 UTC by tmeyer2115

This CR ensures that the sessionTrackingEnabled param is passed along with all non-Analytics API requests issued by the SDK. The ApiRequest class now expects sessionTrackingEnabled as part of the configuration object passed to its constructor. If this value is not present in the config, an error will be thrown. This offers a bit of future proofing by ensuring that anyone adding new
ApiRequests must pass in a sessionTrackingEnabled param. This should resolve issue #419 .

J=ANS-436
TEST=auto, manual

Updated Jest tests. Verified that I saw the sessionTrackingEnabled param with the following requests:
    - Vertical Autocomplete
    - Universal Autocomplete
    - Vertical Search
    - Universal Search
    - Error reporting
    - Q&A submission

2020-01-21 20:49 UTC, data-enabler commented
> I removed the setSessionsOptIn method from answers-umd. Users can already set the sessionTrackingEnabled variable in their Answers config and adding the ability to dynamically change this value didn't seem especially valuable.

Was this discussed with Product? At any rate, we shouldn't be changing the public api in a bugfix release.

2020-01-22 14:00 UTC, tmeyer2115 commented
@data-enabler Added the setSessionsOptIn method back. Passed globalStorage to the various services so that they can pass an up-to-date sessionTrackingEnabled value when constructing ApiRequests.

2020-01-22 19:00 UTC, apokellypse submitted a review, later dismissed

2020-01-22 19:00 UTC, apokellypse commented on src/answers-umd.js
> +    if (typeof parsedConfig.apiKey !== 'string') {
would recommend the error checking of the config be factored out into a validateConfig method, similar to how you did parseConfig, which was nice.

2020-01-22 19:04 UTC, data-enabler reviewed
Also, prefixing the commit message with "Answers SDK" is pretty redundant.

2020-01-22 19:06 UTC, data-enabler requested changes

2020-01-22 19:06 UTC, data-enabler commented on src/core/http/apirequest.js
> +    this._sessionTrackingEnabled = opts.sessionTrackingEnabled;
When I was talking about passing globalStorage through, I meant passing it all the way through to ApiRequest. It's not a very clean solution either way, but at least we won't have boilerplate all over the place.

Also, we should leave a TODO somewhere in this class to make it clear that this isn't really a desired state, and we want to move to something else like a service interface with dependency injection.

2020-01-22 19:06 UTC, data-enabler commented on src/answers-umd.js
> +    if (typeof config.sessionTrackingEnabled === 'boolean') {
This is fine for now, but In the long term we should probably be validating the config with JSON Schema or something, so we'll be able to use Object.assign to handle the defaults for this as well.

2020-01-22 21:28 UTC, tmeyer2115 commented on src/answers-umd.js
> +    if (typeof parsedConfig.apiKey !== 'string') {
Done.

2020-01-22 21:28 UTC, tmeyer2115 commented on src/core/http/apirequest.js
> +    this._sessionTrackingEnabled = opts.sessionTrackingEnabled;
Done.

2020-01-22 22:26 UTC, data-enabler requested changes

2020-01-22 22:26 UTC, data-enabler commented on src/core/http/apirequest.js
> +     */
JSDoc needs to go immediately before the declaration. I would also get rid of the superfluous description.

2020-01-22 22:26 UTC, data-enabler commented on src/core/http/apirequest.js
> +    // implementation of that interface here.
Not really what I meant. An `ApiService` implementation should get passed as a dependency to `ErrorReporter`, `AutoCompleteApi`, etc. It's fine for the `ApiService` implementation to have a reference to `GlobalStorage`.

2020-01-22 22:50 UTC, data-enabler approved these changes

2020-01-22 23:00 UTC, merged