Add locale parameter to configuration & requests in Js library
yext/answers-search-ui pull request #47
Opened 2019-07-09 22:05 UTC by vijay267

WAT-244

The configuration now takes an optional "locale" parameter on initialization and passes that parameter value to all of its api requests as a "locale" request parameter (query, vertical query, autocomplete, vertical autocomplete, and autocomplete filter). Currently the default for locale is 'en'.

E.g. Requests will now look like GET /v2/accounts/me/answers/query?locale=[locale]&api_key=[api_key]...

TEST=manual
Tested by manually testing the various API requests and made sure the correct locale appeared (either specified or default if not specified). Updated appropriate tests.

2019-07-10 00:00 UTC, Delerme requested changes

2019-07-10 00:00 UTC, Delerme commented on src/core/core.js
> +    if (opts.locale != null) {
you can replace this with 
`this._locale = opts.locale || 'en';

2019-07-10 00:00 UTC, Delerme commented on src/core/core.js
> +     * For autocomplete filter, vertical autocomplete, and universal autocomplete
I think we're now calling autocomplete filter "filter search"

2019-07-10 00:00 UTC, Delerme commented on src/core/search/autocomplete.js
> +    this._locale = opts.locale || null;
is this a required param? if so don't fallback to null and instead chech that opts.locale is provided and throw if now

if (!opts.locale) {
 throw new AnswersBasicError(...);
}

2019-07-10 00:00 UTC, Delerme commented on src/core/search/search.js
> +    this._locale = opts.locale || null;
ditto

2019-07-10 19:33 UTC, vijay267 commented on src/core/core.js
> +    if (opts.locale != null) {
Done

2019-07-10 19:33 UTC, vijay267 commented on src/core/core.js
> +     * For autocomplete filter, vertical autocomplete, and universal autocomplete
True, was originally trying to match other code, but might as well use the current name.

2019-07-10 19:36 UTC, Delerme reviewed
lgtm, to @b1lly

2019-07-11 15:50 UTC, b1lly submitted a review, later dismissed
Yeah, I think this is fine for now.

I think there's a bigger refactor coming where:

1. There is a singleton HTTPRequester
2. The HTTPRequestor is available through the core, to `search` and `autocomplete`
3. The HTTPRequestor has some `global properties` that can be configured
4. HTTPRequestor acts on APIRequest, which contains data about the request, and can inherit `global` state from the HTTPRequestor or override them if defined
5. The HTTPRequestor contains things like api key, answers key, and local as some of the global options

That way when we make changes like this in the future we can just do it in one place.

@Delerme 

Otherwise, LGTM.

2019-07-11 17:27 UTC, Delerme submitted a review, later dismissed

2019-07-11 21:53 UTC, Delerme approved these changes

2019-07-11 21:54 UTC, merged