refactor ResultItemComponent to Cards
yext/answers-search-ui pull request #485
Opened 2020-02-03 21:35 UTC by oshi97

following commits will change implementation

2020-02-03 22:50 UTC, tmeyer2115 commented on src/ui/components/cards/standardcardcomponent.js
> +     * verticalConfigId used for analytics and passed to children
Remove "and passed to children". This component has no children, right?

2020-02-03 22:50 UTC, tmeyer2115 commented on src/ui/components/cards/standardcardcomponent.js
> +     * true if this component is added by the UniversalResultsComponent
Same thing about referring to children in the docs.

2020-02-03 22:50 UTC, tmeyer2115 commented on src/ui/components/cards/standardcardcomponent.js
> +    return templateToType[this.defaultTemplateName()];
Could we flip this logic around? We could hardcode the string 'StandardCard' here and refer to the static method in the consts.js map.

2020-02-03 22:50 UTC, tmeyer2115 commented on src/ui/components/cards/standardcardcomponent.js
> +    return cardTemplates.Standard;
Same thing about hard coding the string here and using that in the consts.js map.

2020-02-04 00:09 UTC, oshi97 commented on src/ui/components/cards/standardcardcomponent.js
> +    return templateToType[this.defaultTemplateName()];
Changed to cardTypes and cardTemplates I think doing two references like I was doing is a little silly

2020-02-04 17:20 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +/** @module StandardCardComponent */
Update.

2020-02-04 17:20 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +      data
Do we need data here? Is it not enough to have data as the 2nd arg to Object.assign?

2020-02-04 17:20 UTC, tmeyer2115 commented on src/ui/components/registry.js
> +  StandardCardComponent,
Minor organizational nit, but lets create a new section in this list for the various card components:
// Card Templates
CardComponent,
StandardCardComponent,
AccordionCardComponet,
...

2020-02-04 20:52 UTC, tmeyer2115 requested changes

2020-02-04 20:52 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +    super(config, systemConfig);
I think we want to follow the pattern set by QuestionSubmissionComponent. We build what we want the config object to be, then pass it into super(config, systemConfig). This automatically sets this._config for us and ensures consistency between the config provided to super(...) and the config we use in this class. If we call super first, then make changes to config and manually set this._config, I worry it could have some weird side effects. The super class has a different config than this class.

2020-02-04 20:52 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +    const data = config.data;
Could we update this doc? Not sure what data is exactly. Don't see it listed in the spec. Are the attributes in template mapping what we see on the card?

2020-02-04 20:52 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +export default class CardComponent extends Component {
How are templateMappings used in this class?

2020-02-04 20:52 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +  addChild (data, type, opts) {
It seems like we could do things in such a way that we don't have to override addChild. We can just manually build opts (should just be two attributes). I share your aversion to overriding addChild, so I think we should avoid it here, when we can.

2020-02-04 21:27 UTC, b1lly requested changes

2020-02-04 21:27 UTC, b1lly commented on src/ui/components/cards/cardcomponent.js
> +      console.error(err);
Whats the point of try->catch->console log?

If you care about the error, instead of console logging it, you should throw a new AnswersError here.... probably AnswersComponentError to be specific, or AnswersUiError.

e.g.

```
try {
   ...
} catch (e) {
  throw new AnswersComponentError('CardComponent: Invalid template mappings provided', e);
}
```

OR, you can provide specific details 


https://github.com/yext/answers/blob/master/src/core/errors/errors.js

By throwing an `AnswersError` it'll integrate more effectively with the error reporter.

2020-02-04 22:04 UTC, oshi97 commented on src/ui/components/cards/cardcomponent.js
> +  addChild (data, type, opts) {
I did it this way because I don't think the card component should ever have any children besides it's one child card, and putting the opts as stringified into data-opts puts all into the html which is pretty hideous by its own respect. I'll change it but we definitely need to refactor how we pass config to children.

2020-02-04 22:04 UTC, oshi97 commented on src/ui/components/cards/cardcomponent.js
> +export default class CardComponent extends Component {
I can move them to the next commit

2020-02-04 22:04 UTC, oshi97 commented on src/ui/components/cards/cardcomponent.js
> +    const data = config.data;
How I understood it was config.data is passed in from data-prop in vertical results. In this case we expect it to be profile data for the result this card cares about. This gets passed into templateMappings to construct the config for the card.

2020-02-04 22:45 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +    this.itemTemplate = config.itemTemplate;
If you do: 
this.render = config.renderItem
this.template = config.template
You can save yourself the call to setRender and setTemplate below.

2020-02-04 22:45 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +      cardOpts: JSON.stringify(new CardConfig(this._config))
This is a minor thing, but let's be explicit here about what cardOpts actually contains. It just needs verticalConfigId and isUniversal, right? I think we should just JSON.stringify and Object containing those. Then, it will be clear to someone reading the code what we're passing down. We shouldn't pass it a config with more than it needs.

2020-02-05 16:07 UTC, tmeyer2115 approved these changes

2020-02-05 16:27 UTC, merged

2020-02-05 22:06 UTC, b1lly commented on src/ui/components/results/verticalresultscomponent.js
> +    return super.addChild(data, type, opts);
`opts` is an old name. Can we rename it to `config` everywhere so that its consistent? That way we avoid confusion, and we always know what we're actually dealing with.

2020-02-05 22:06 UTC, b1lly commented on src/ui/components/cards/cardcomponent.js
> +      cardData: data
I'd probably do most of this through configuration and component-markup-syntax.

Something like this:

```
this._config = Object.assign({}, this._config, {
   cardType: ...,
   childConfig: { 
      verticalConfigId,
      isUniversal
   }
});
```

And then the template becomes:

```
<div data-component="{{_config.cardType}}"
  data-prop="cardData"
  data-opts="{{_config.childConfig}}">
</div> 
```
Also note my other comment. I'd like to rename `data-opts`, to `data-config` and standardize the naming to keep it consistent. `opts` was the old name. 

As you work through areas of the code with the legacy name, might be worth updating it! That way you don't have to update it everywhere at once.

Separately, for child components and configuration, i'd probably what i'd probably think about is a better architectural pattern that makes configuration flow more easily to child components without having to do things like this. Or define a pattern/practice for how to do it thats consistent.