CTAs for cards
yext/answers-search-ui pull request #491
Opened 2020-02-10 20:28 UTC by oshi97

This commit implements CTAs by creating CTAComponent as a subcomponent
of StandardCardComponent.

TEST=manual

2020-02-10 21:11 UTC, tmeyer2115 requested changes

2020-02-10 21:11 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +  handleCTA (cta) {
I think all the logic for mapping a result to a CTA should live inside the CTAComponent itself. This way, CTAComponent is just kind of a black box that the CardComponent can call into.

2020-02-10 21:11 UTC, tmeyer2115 commented on src/ui/components/cards/cardcomponent.js
> +      return cta(this.result);
Confirm with Rose, but I think the 3 cases we want to handle for CTA are:

1. item => list of CTAs
2. There is a list of CTAs, where each CTA is an object whose values are determined by a function on item.
3. FieldNames.

Are we leaving option 3 for a later PR? If so, that's fine. I think, then, handleCTA needs to return a list of CTAs, since one mapping can potentially yield multiple CTAs.

2020-02-10 21:11 UTC, tmeyer2115 commented on src/ui/sass/modules/helper/_CTA.scss
> +  @include CTA();
I feel like we should get rid of the Mixin and move all the CSS into this class. I feel like the Mixin for CTAs has way too many arguments. Additionally, cards are the only consumers of CTAs, so the Mixin would not be widely used. Can you just override the default styling for the CTA in _StandardCard.scss in your various .yxt-CTA selectors?

2020-02-10 21:11 UTC, tmeyer2115 commented on src/ui/sass/modules/_StandardCard.scss
> +      &:only-child .yxt-CTA {
So the mocks call for lots of customization of the CTAs depending on if it's mobile or there's only one item? Kinda annoying.

2020-02-11 01:06 UTC, oshi97 commented on src/ui/components/cards/cardcomponent.js
> +  handleCTA (cta) {
updated to use CTACollectionComponent

2020-02-11 01:06 UTC, oshi97 commented on src/ui/components/cards/cardcomponent.js
> +      return cta(this.result);
Updated

2020-02-11 01:54 UTC, oshi97 commented on src/ui/sass/modules/helper/_CTA.scss
> +  @include CTA();
Yes I can, I was hoping the mixing would make life easier for people but I guess it did the opposite

2020-02-11 01:56 UTC, oshi97 commented on src/ui/sass/modules/_StandardCard.scss
> +      &:only-child .yxt-CTA {
Yeah, I think it's important to customize for mobile but not sure about the only child thing

2020-02-11 15:44 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +  handleCTA (cta) {
I think the work of translating the callsToAction mappings in the config to actual ctas should happen in the component, not the config class. That feels like too much responsibility for the config class. I don't think we always need a ComponentConfig class either, especially if the config is relatively straightforward.

2020-02-11 15:44 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +          shouldRender: _cta.url && _cta.label
What's this shouldRender?

2020-02-11 15:44 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +  handleCTA (cta) {
For clarity, I think we should do some renaming. We could call this method resolveCTAMapping or something to give a better indication for what it does. I think it should have params ctaMapping and result. We could add some docs too.

2020-02-11 15:44 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +      for (let [ctaOption, optionValue] of Object.entries(cta)) {
[ctaAttribute, attributeMapping]?

2020-02-11 15:44 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +      const calculatedCTA = { ...cta };
Wouldn't we want to initialize calculatedCTA as empty?

2020-02-11 15:44 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacomponent.js
> +    this.eventOptions = config.eventOptions ? JSON.parse(config.eventOptions) : {};
Why do we need to JSON.parse here? Were we JSONifying the eventOptions at some point higher in the chain?

2020-02-11 16:22 UTC, tmeyer2115 commented on src/ui/sass/answers.scss
> +@import "modules/helper/CTA";
I don't think we need to create a helper dir for this. I think it should just live in modules.

2020-02-11 16:42 UTC, oshi97 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +          shouldRender: _cta.url && _cta.label
Rose didn't want to render the cta if there was no label and url

2020-02-11 16:44 UTC, oshi97 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +      const calculatedCTA = { ...cta };
no because we want to keep any static values

2020-02-11 16:45 UTC, oshi97 commented on src/ui/components/ctas/ctacomponent.js
> +    this.eventOptions = config.eventOptions ? JSON.parse(config.eventOptions) : {};
The spec has eventOptions as a json string not sure which is better

2020-02-11 17:01 UTC, alexisgrow reviewed
LG, left a few CSS comments

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/_StandardCard.scss
> +            margin: 0 0 0 $standard-card-base-spacing/2;
Instead of the four numbers here, margin-left can be more readable

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/_StandardCard.scss
> +        word-break: break-word;
looks like 
```
        margin: 0;
        text-align: center;
        word-break: break-word;
``` 
can be moved up to .yxt-CTA bc it's shared

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/_StandardCard.scss
> +          flex-direction: row;
i think this is also shared with the regular .yxt-CTA one

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/_StandardCard.scss
> +          margin: $standard-card-base-spacing-sm/2 0 0 0;
margin-top?

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/helper/_CTA.scss
> +  flex-direction: row;
this is default for display:flex, nit, you can omit!

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/helper/_CTA.scss
> +  margin: 0 0 0 $base-spacing;
margin-left :octocat:

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/helper/_CTA.scss
> +    margin: 0 0 0 $base-spacing-sm/2;
same 👾

2020-02-11 17:01 UTC, alexisgrow commented on src/ui/sass/modules/helper/_CTA.scss
> +  &:hover, &:focus {
:active as well?

2020-02-11 18:48 UTC, oshi97 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +  handleCTA (cta) {
updated!

2020-02-11 19:53 UTC, oshi97 commented on src/ui/sass/modules/_StandardCard.scss
> +            margin: 0 0 0 $standard-card-base-spacing/2;
tried to update all the css things lmk what can still be improved!

2020-02-11 19:53 UTC, oshi97 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +          shouldRender: _cta.url && _cta.label
updated to use the json hbs helper!

2020-02-11 21:55 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +   * @param {Array<Function|Object|string>} ctaMapping
Doesn't this just take in a single Function?

2020-02-11 21:55 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +      callsToAction = callsToAction(this._config.result) || [];
Can this case be handled by resolveCTAMapping? According to the doc, it supports a function that returns a CTA's config. Is this handled separately because the function could return a list of CTA objects? If so, we could modify resolveCTAMapping to return an array of CTA objects (and then use a flatMap in your loop below).

2020-02-11 21:55 UTC, tmeyer2115 commented on src/ui/sass/modules/_StandardCard.scss
> +      $style: italic);
Remove extra tab.

2020-02-11 22:09 UTC, oshi97 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +      callsToAction = callsToAction(this._config.result) || [];
This is for a function that returns the array of cta config objects, are you saying just include this portion inside resolveCTAMapping and have resolveCTAMapping take in an array?

2020-02-11 22:18 UTC, tmeyer2115 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +      callsToAction = callsToAction(this._config.result) || [];
resolveCTAMapping wouldn't take in an array, it would output an array. Yeah, I think we should make that change, seems a bit cleaner. In the other cases, resolveCTAMapping would just return an array with one element. You can use a flatMap down below in your map(...)

2020-02-11 22:52 UTC, oshi97 commented on src/ui/components/ctas/ctacollectioncomponent.js
> +      callsToAction = callsToAction(this._config.result) || [];
Ah ok that's really smart does this work?

2020-02-11 23:01 UTC, tmeyer2115 approved these changes

2020-02-12 00:02 UTC, merged