Add footer to vertical results
yext/answers-search-ui pull request #492
Opened 2020-02-10 21:33 UTC by oshi97

TEST=manual

2020-02-11 22:15 UTC, tmeyer2115 requested changes

2020-02-11 22:15 UTC, tmeyer2115 commented on src/ui/components/results/verticalresultscomponent.js
> +    this.footer = {
I think the footer will also be used for UniversalResults, so it could make sense to have a FooterComponent that can be reused.

2020-02-11 22:15 UTC, tmeyer2115 commented on src/ui/components/results/verticalresultscomponent.js
> +      ...config.footer
This syntax obscures what's going on. It makes it seem like we're hardcoding the various config values above.

2020-02-11 22:15 UTC, tmeyer2115 commented on src/ui/components/results/verticalresultscomponent.js
> +      logo: 'yext',
The spec called for the ability to do an in-line SVG. Are we not doing that for security reasons (which is totally fine)?

2020-02-11 23:10 UTC, oshi97 commented on src/ui/components/results/verticalresultscomponent.js
> +      logo: 'yext',
Yeah I put a comment in the spec about not doing that anymore

2020-02-12 16:08 UTC, oshi97 commented on src/ui/components/results/verticalresultscomponent.js
> +    this.footer = {
Updated!

2020-02-12 16:08 UTC, oshi97 commented on src/ui/components/results/verticalresultscomponent.js
> +      ...config.footer
Updated

2020-02-13 15:06 UTC, tmeyer2115 commented on src/ui/components/utils/footercomponent.js
> +/** @module VerticalResultsComponent */
Update.

2020-02-13 15:06 UTC, tmeyer2115 commented on src/ui/components/utils/footercomponent.js
> +    this._config.newWindow = config.newWindow;
Do we need a default for this?

2020-02-13 15:06 UTC, tmeyer2115 commented on src/ui/components/utils/footercomponent.js
> +    this._config.image = !this._config.icon && logo;
The logic for setting this._config.icon and this._config.image is confusing. this._config.icon is always going to be true here, isn't it? Shouldn't we set this._config.icon = Icons[logo]?

2020-02-13 15:06 UTC, tmeyer2115 commented on src/ui/templates/cards/card.hbs
> +<li data-component="{{cardType}}" data-prop="result">
Why is this an li now? Should card.hbs be scoped to only one result?

2020-02-13 15:06 UTC, tmeyer2115 commented on src/ui/templates/results/verticalresults.hbs
> +        data-opts='{{json _config.footer}}'
How come we need a json helper here? Isn't _config.footer a normal object without function values?

2020-02-13 17:01 UTC, oshi97 commented on src/ui/components/utils/footercomponent.js
> +/** @module VerticalResultsComponent */
updated!

2020-02-13 17:01 UTC, oshi97 commented on src/ui/components/utils/footercomponent.js
> +    this._config.newWindow = config.newWindow;
Felt like || false was redundant and can lead to confusion when || true doesn't work as expected but will add it

2020-02-13 17:01 UTC, oshi97 commented on src/ui/components/utils/footercomponent.js
> +    this._config.image = !this._config.icon && logo;
updated

2020-02-13 17:01 UTC, oshi97 commented on src/ui/templates/cards/card.hbs
> +<li data-component="{{cardType}}" data-prop="result">
I mean, I think it should be scoped to one result but this change has 0 effect on the ui with the current styling

2020-02-13 19:12 UTC, tmeyer2115 approved these changes

2020-02-13 19:13 UTC, merged