Use FilterView instead of Filter
yext/answers-search-ui pull request #506
Opened 2020-02-20 21:39 UTC by oshi97

This commit implements FilterView and FacetView,
which are container classes for Filter and Facets
which contain additional metadata
TEST=manual
Created a test site testing that FilterOptions, FilterBox, Facets,
DateRangeFilter, GeolocationFilter, DateRangeFilter, RangeFilter,
and GeoLocationFilter still filtered properly and also contained
desired metadata

2020-02-24 16:58 UTC, tmeyer2115 requested changes

2020-02-24 16:58 UTC, tmeyer2115 commented on src/core/models/filterview.js
> +export default class FilterView {
I think we should leave the Filter class as is, with all those static methods. Those methods are all at the same level of abstraction as the Filter class, they create a Filter. I don't think the FilterView class should provide static methods for you to create Filters. It operates at a higher level of abstraction than a Filter.

2020-02-24 16:58 UTC, tmeyer2115 commented on src/core/models/facet.js
> +export default class FacetView {
How come we didn't add a new class for FacetView?

2020-02-24 16:58 UTC, tmeyer2115 commented on src/core/core.js
> +   * Stores the given filter view into storage, to be used for the next search
Stores the given filter view into storage. The view's filter data object will be used in the next search.

2020-02-24 16:58 UTC, tmeyer2115 commented on src/ui/components/filters/daterangefiltercomponent.js
> +    this._onChange(filterView);
Seems like we probably want to call _onChange with the actual filter. At the very least, for backwards compatibility in case anyone has written onChange methods for this component already. Plus, I don't think folks will care about the metadata object in any onChange method they create.

2020-02-24 16:58 UTC, tmeyer2115 commented on src/ui/components/filters/filteroptionscomponent.js
> +    this.config.onChange(filterView);
Same comment about onChange

2020-02-24 16:58 UTC, tmeyer2115 commented on src/ui/components/filters/geolocationcomponent.js
> +    if (typeof this.filterView === 'string') {
This is kinda weird. When would the type of filterView be string? Is this what happens when the filter is seeded from persistentStorage?

2020-02-24 17:26 UTC, oshi97 commented on src/ui/components/filters/geolocationcomponent.js
> +    if (typeof this.filterView === 'string') {
Yeah the current code stores the filter as json in the url for a few but not all filters

2020-02-25 02:43 UTC, oshi97 commented on src/ui/components/filters/daterangefiltercomponent.js
> +    this._onChange(filterView);
included metadata in additional parameter because we need it for filterbox

2020-02-25 22:35 UTC, tmeyer2115 commented on src/core/core.js
> +    const allFilters = this.globalStorage.getAll(StorageKeys.FILTER_VIEW) || [];
allFilterViews?

2020-02-25 22:35 UTC, tmeyer2115 commented on src/core/models/facet.js
> +  static fromFilterViews (availableFieldIds, ...filters) {
Is ...filters a list of Filters or FilterViews? If the former, we should continue calling this fromFilter. I think having this take in a list of Filter would make the most sense, as Facet should not be built with anything that is purely a presentation concern (like the Metadata in FilterView).

2020-02-25 22:35 UTC, tmeyer2115 commented on src/core/models/facetview.js
> +     * Metadata for the filter.
facet?

2020-02-25 22:35 UTC, tmeyer2115 commented on src/core/models/facetview.js
> +     * The exactly formatted filter to send to the backend.
Not sure what's meant by exactly formatted. Should we be referring to it as a filter?

2020-02-25 22:35 UTC, tmeyer2115 commented on src/core/models/filterview.js
> +    this.displayValues = [ displayValues ].flat();
Do we also want to have a separator here for the displayValues?

2020-02-26 16:13 UTC, tmeyer2115 commented on src/core/models/filtermetadata.js
> +export default class FilterMetadata {
Even though it will be simple, let's fill out this class a bit. 
constructor(metadata) {
   this._metadata = metadata;
}

get() {
  return this._metadata;
}

2020-02-26 16:13 UTC, tmeyer2115 commented on src/core/models/filtermetadata.js
> +   * @param  {Array<Object>} metadataArray
Array of FilterMetadata

2020-02-26 16:13 UTC, tmeyer2115 commented on src/core/models/filtermetadata.js
> +    return metadataArray.reduce((group, metadata) => {
Let's update this to work with the filled-out FilterMetadata class.

2020-02-26 16:13 UTC, tmeyer2115 commented on src/core/models/filterview.js
> +  static and (...filterViews) {
I think we should just expose one static method for combining filters. I think it's a bit difficult for someone reading the code to understand the difference between combineFilterViews and the and method. We could make and a private static method by renaming it _and. Anything that calls _and would be updated to call combineFilterViews. Do we also need to handle the case of or'ing filter views together? Could we add a param to combineFilterViews that indicates how they should be combined?

2020-02-26 16:13 UTC, tmeyer2115 commented on src/ui/components/filters/daterangefiltercomponent.js
> +    this._onChange(filterView.filter, filterView.metadata);
I think we should maintain the existing contract we have with onChange. It is only passed back the actual Filter data. I don't think people should be writing onChange handlers that depend on any FilterMetadata. The FilterMetadata is pretty internal to the SDK.

2020-02-26 16:13 UTC, tmeyer2115 commented on src/ui/components/filters/filterboxcomponent.js
> +          onChange: (filter, metadata) => {
Same thing about onChange

2020-02-26 16:19 UTC, oshi97 commented on src/core/models/filterview.js
> +  static and (...filterViews) {
Or-ing together filters is only used in filteroptions (and by extension filterbox which uses it and facet with uses filterbox) so or-ing together filter views currently isn't needed

2020-02-26 16:24 UTC, oshi97 commented on src/ui/components/filters/daterangefiltercomponent.js
> +    this._onChange(filterView.filter, filterView.metadata);
This is needed by FilterBox to update the FilterViews in global storage, it shouldn't have any impact on preexisting onChange functions because they should only be passing back one parameter anyways

2020-02-26 16:30 UTC, oshi97 commented on src/core/models/filtermetadata.js
> +export default class FilterMetadata {
I think it makes sense to add Object.assign(this, metadata) as a constructor and wrap any metadata with this class but anything beyond that feels like just adding get() calls everywhere without really having cleaner code or anything

If we need to add additional properties in the future I don't think it would hard to refactor things

2020-02-26 17:38 UTC, tmeyer2115 approved these changes

2020-02-26 17:42 UTC, merged