AppliedFiltersComponent
yext/answers-search-ui pull request #511
Opened 2020-02-26 18:14 UTC by oshi97

This commit adds the AppliedFiltersComponent,
which is used internally only within vertical results
to display results count, applied filters, and applied
sorts in the header.

TEST=manual
Created a test site with all filters except FilterSearch,
checked that filters and styling worked as expected.
There are issues with facets not updating correctly or
at least weirdly from the url, however this issue was present
prior to this change.

2020-02-26 22:32 UTC, tmeyer2115 requested changes

2020-02-26 22:32 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this.moduleId = StorageKeys.VERTICAL_RESULTS;
Are applied filters used with universal results as well?

2020-02-26 22:32 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.showAppliedFilters = config.showAppliedFilters === undefined ? true : config.showAppliedFilters;
Why do we have this boolean in this class? If this is false, shouldn't we just not render the AppliedFiltersComponent? Is this component doing something else besides showing the applied filters?

2020-02-26 22:32 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.hiddenFields = config.hiddenFields || [];
Should entity type be a default here?

2020-02-26 22:32 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.resultsCountSeparator = config.resultsCountSeparator || '|';
What would you think about making a ResultsHeader component that invokes the AppliedQueryFilter component? The ResultsHeader would be responsible to rendering results count.

2020-02-26 22:32 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +    return Object.entries(metadata).map(([displayField, displayValues]) => ({
Does Object.entries(metadata) not return an array of displayField, displayValues pairs?

2020-02-26 22:32 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +  getAppliedFilters () {
I might have missed this in a previous CR, but where are we pulling in the NLP filters from the back-end? It seems like these filters might violate our assumption that only one filter can be applied to a field. In the spec, it seems like multiple NLP filters can be applied to a field.

2020-02-26 22:32 UTC, tmeyer2115 commented on src/ui/templates/results/appliedfilters.hbs
> +    {{#each appliedQueryFilters}}
What's the difference between appliedQueryFilters and appliedFilters?

2020-02-26 23:50 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +    return Object.entries(metadata).map(([displayField, displayValues]) => ({
It does but I think we prefer to have an array of objects not array of arrays, so that in the handlebars we dont have to do some weird loop.  maybe the syntax I used is unclear, if so let me know, but it's creating objects of
`{
displayField: 'alkdjlfasdj',
displayValues: ['1','2','3312413']
}
`

2020-02-27 00:02 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +  getAppliedFilters () {
I asked rose what we should do about these. These can be combined pretty easily with the other filter metadata, but looking into the later mocks if we want to be able to click an applied filter in the header and remove it for the search that obviously wouldn't work for any nlp filters

2020-02-27 02:33 UTC, oshi97 commented on src/ui/templates/results/appliedfilters.hbs
> +    {{#each appliedQueryFilters}}
these are the nlp filters from the backend, and are also what they are called in the response. I felt uncomfortable with the current naming but also uncomfortable with renaming it to be inconsistent with the response

2020-02-27 02:42 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.hiddenFields = config.hiddenFields || [];
Yes

2020-02-27 02:43 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.showAppliedFilters = config.showAppliedFilters === undefined ? true : config.showAppliedFilters;
Created ResultsHeaderComponent

2020-02-27 02:43 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.resultsCountSeparator = config.resultsCountSeparator || '|';
created!

2020-02-27 02:44 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this.moduleId = StorageKeys.VERTICAL_RESULTS;
was being used to get the appliedQueryFilters (nlpFilters) but probably better to pass them in directly

2020-02-27 02:44 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +  getAppliedFilters () {
Rose says we don't need to worry about it

2020-02-27 16:01 UTC, tmeyer2115 commented on src/core/models/filtermetadata.js
> + *    'Your Favorite Bird': ['rooster', 'penguin', 'turkey', 'chikn', 'dog']
Why are there multiple display labels and lists of display values under c_birdTypes? Won't there only be one display name for the filter and one list of display values for it? Something like:

c_birdTypes: {
   displayName: 'Name';
   displayValues: [...]
}

2020-02-27 16:01 UTC, tmeyer2115 commented on src/core/models/section.js
> +    this.fieldId = Filter.getFilterKey(appliedQueryFilter.filter);
Where's fieldId used here?

2020-02-27 16:01 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.resultsCountSeparator = config.resultsCountSeparator || '|';
Do we still need this here? Could we not put this logic in the ResultsHeader component?

2020-02-27 16:01 UTC, tmeyer2115 commented on src/ui/components/results/appliedfilterscomponent.js
> +  getAppliedFilters () {
What does she mean by that? Like we'll deal with it later? Does the back-end currently send us these NLP filters back?

2020-02-27 16:01 UTC, tmeyer2115 commented on src/ui/components/results/resultsheadercomponent.js
> +    this._config.resultsCount = config.resultsCount || 0;
Why is resultsCount part of the config? Isn't that data we can just pull from the globalStore?

2020-02-27 16:01 UTC, tmeyer2115 commented on src/ui/components/results/resultsheadercomponent.js
> +      appliedQueryFilters: config.appliedQueryFilters || [],
Same thing here, these don't seem like config options. Wouldn't we just get this from the globalStore?

2020-02-27 16:01 UTC, tmeyer2115 commented on src/ui/components/results/resultsheadercomponent.js
> +      hiddenFields: config.hiddenFields || [ 'builtin.entityType' ]
I would assume that Rose is aware of this, but seems kinda difficult for customers to use the hiddenFields if they have to know what the API names are. Not sure of a way around this though

2020-02-27 16:01 UTC, tmeyer2115 commented on src/ui/components/results/verticalresultscomponent.js
> +      showAppliedFilters: config.showAppliedFilters === undefined ? true : config.showAppliedFilters,
Could we make the appliedFilterOpts object here? Then the ResultsHeader wouldn't have to do it and would be able to pass it straight through.

2020-02-28 15:27 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +  getAppliedFilters () {
The backend sends us back these NLP filters in the response for vertical search. She said we shouldn't worry about them filtering on the same fields as a static filter, we can just display them separately

2020-02-28 15:40 UTC, oshi97 commented on src/core/models/filtermetadata.js
> + *    'Your Favorite Bird': ['rooster', 'penguin', 'turkey', 'chikn', 'dog']
Yeah you're right the user should not be adding multiple filters for the same fieldId with different labels, I still think it would be good to support it in the code with for loops or something

2020-02-28 15:44 UTC, oshi97 commented on src/core/models/section.js
> +    this.fieldId = Filter.getFilterKey(appliedQueryFilter.filter);
Oh this is only used for removing hidden fields in the AppliedFiltersComponent, since otherwise that information is lost

2020-02-28 15:48 UTC, oshi97 commented on src/ui/components/results/verticalresultscomponent.js
> +      showAppliedFilters: config.showAppliedFilters === undefined ? true : config.showAppliedFilters,
updated!

2020-02-28 20:18 UTC, oshi97 commented on src/ui/components/results/appliedfilterscomponent.js
> +    this._config.resultsCountSeparator = config.resultsCountSeparator || '|';
removed

2020-02-28 20:19 UTC, oshi97 commented on src/ui/components/results/resultsheadercomponent.js
> +    this._config.resultsCount = config.resultsCount || 0;
ah so I wanted to avoid listening on global store since there's universal and also vertical results using this component

2020-02-28 20:20 UTC, oshi97 commented on src/ui/components/results/resultsheadercomponent.js
> +      appliedQueryFilters: config.appliedQueryFilters || [],
moving this to data

2020-03-02 23:18 UTC, oshi97 commented on src/ui/components/results/resultsheadercomponent.js
> +      hiddenFields: config.hiddenFields || [ 'builtin.entityType' ]
Yeah not sure what the best way around this is

2020-03-05 23:42 UTC, oshi97 commented
CLOSING this pull request until the higher priority card/section items for hitchhikers are completed

2020-03-05 23:42 UTC, closed without merging