Add AccordionCardComponent
yext/answers-search-ui pull request #518
Opened 2020-02-27 04:58 UTC by oshi97

This commit adds the AccordionCardComponent which is
a card template that looks like an accordion.
Also re-adds resultsaccordion.hbs which should not have been deleted and is still used by universal results.
TEST=manual
Tested that card template loaded correctly, has proper
cardMappings, ctas fires analytics events correctly and goes to url,
opening and closing accordion fires analytics event and changes
aria-expanded for toggle and aria-hidden for content, and that animation is smooth.

2020-02-27 05:02 UTC, oshi97 commented on src/ui/sass/modules/_AccordionCard.scss
> +.yxt-Card {
This is icky but there's I couldn't find another way to reference whether a certain AccordionCard component was the last one, since it has to be wrapped in a container div thanks to how data-component works, and also can't just remove the yxt-AccordionCard container in accordion.hbs and change the data-component container class to yxt-AccordionCard because we need be able to select it inside the javascript

Just having border: border-default without some kind of logic like this results in a double border and I just KNOW somebody is going to yell at me for that

2020-02-28 15:39 UTC, creotutar commented on README.md
> +    // Optional: The type of card, currently only 'Standard' and 'Accordion' ard supported, defaults to 'Standard'
typo

2020-02-28 15:41 UTC, creotutar commented on README.md
> +  expanded: false
does this mean only the first will be expanded or all will be expanded on load?

2020-02-28 15:52 UTC, creotutar commented
@oshi97 I'm seeing a commit for the QA outside of adding AccordionCard, is that intentional? possible to split into two different PRs?

2020-02-28 19:21 UTC, oshi97 commented on src/ui/components/cards/standardcardcomponent.js
> +    console.log(this);
Ah shoot I'll remove this

2020-02-28 20:15 UTC, oshi97 commented on README.md
> +  expanded: false
Ah so cardMappings are on a per card basis, would "Whether this cardMapping's accordion should be..." work better?

2020-02-29 05:33 UTC, creotutar commented on README.md
> +  expanded: false
Ah no, what you have current makes sense!

2020-02-29 05:42 UTC, creotutar commented on src/ui/components/cards/cardcomponent.js
> +      cardMappings = cardMappings(result);
is this meant to be `config=cardMappings(result)`?

2020-02-29 05:50 UTC, creotutar commented on src/ui/components/cards/cardcomponent.js
> +      cardMappings = cardMappings(result);
if that's the case, we may want to go through the entries and add to config as you're doing below

2020-02-29 05:58 UTC, creotutar commented on src/ui/components/cards/standardcardcomponent.js
> +    Object.assign(this, CardComponent.applyCardMappings(this.result, cardMappings));
do we want to give the user control over the `this` variables in this component? if i'm reading this correctly if i give the cardMapping

```
{
  result: 'hacked result!'
}
```

then the result variable should be overridden and changed for the other lines relying on this.result?

2020-02-29 06:21 UTC, creotutar commented on src/ui/components/results/verticalresultscomponent.js
> +    this.verticalKey = this._config.verticalConfigId;
if this is a private variable (from js doc above), do we want to follow the `_` naming convention?

2020-02-29 06:28 UTC, creotutar commented on src/ui/sass/modules/_AccordionCard.scss
> +.yxt-Card
why do we need this parent class? is there a situation when we have a `.yxt-AccordionCard` without a `.yxt-Card` parent?

2020-02-29 06:31 UTC, creotutar commented on src/ui/sass/modules/_AccordionCard.scss
> +  .yxt-CTA
in the ideal modularized scss world, only AccordionCard module styling would live in this file. if we needed a CTA that had specific stying /only/ for AccordionCard, then we would have a CTA variant etc: `.yxt-CTA--accordionCard` which would live in the `CTA.scss`

this makes it easier to trace scss styling as all module styles live in one file

this may be difficult to achieve as i dont think the library is set up to pass around classes given some contexts. do you have any insight here?

2020-02-29 06:36 UTC, creotutar commented on src/ui/components/cards/accordioncardcomponent.js
> +    this.isExpanded = false;
this is always false? where does the config option come to play?

2020-02-29 06:40 UTC, creotutar commented on src/ui/components/cards/accordioncardcomponent.js
> +    iconEl.classList.toggle('yxt-AccordionCard-icon-expanded');
if we are following SUIT naming conventions, this class should be `yxt-AccordionCard-icon--expanded` (double hyphens to indicate a modifier)

2020-02-29 06:41 UTC, creotutar commented on src/ui/components/cards/accordioncardcomponent.js
> +    const toggleEl = DOM.query(this._container, '.yxt-AccordionCard-toggle');
if we are querying DOM elements in the JS, we should be targeting `js-*` classes to separate concerns of styling and js selector classes

2020-02-29 06:46 UTC, creotutar requested changes
Looks great! A few minor things about element selectors. Also want to make sure we aren't letting user options unintentionally override our class variables.

2020-03-02 19:58 UTC, oshi97 commented on src/ui/components/cards/standardcardcomponent.js
> +    Object.assign(this, CardComponent.applyCardMappings(this.result, cardMappings));
OH wow that's a really cool catch, no they shouldn't be allowed to mess with the result

2020-03-02 19:58 UTC, oshi97 commented on src/ui/components/results/verticalresultscomponent.js
> +    this.verticalKey = this._config.verticalConfigId;
Yes, updated!

2020-03-02 19:58 UTC, oshi97 commented on src/ui/sass/modules/_AccordionCard.scss
> +  .yxt-CTA
Ok I think this is a really good suggestion for the long run to make styling easier, I tried to do this by passing in a context config option to the CTAs and then inserted that as an additional class like .yxt-CTA-AccordionCard

2020-03-02 19:58 UTC, oshi97 commented on src/ui/sass/modules/_AccordionCard.scss
> +.yxt-Card
this was for the :first-child selector

2020-03-02 19:58 UTC, oshi97 commented on src/ui/components/cards/cardcomponent.js
> +      cardMappings = cardMappings(result);
soo I had it as `cardMappings = cardMappings(result)` instead of `config = cardMappings(result); } else if...` just for the case where somebody could function cardMappings that returned an object with functions inside it. 

Tom convinced me that isn't behavior we want to encourage, but I still feel like it would be good to handle it just in case?

2020-03-02 19:58 UTC, oshi97 commented on src/ui/components/cards/cardcomponent.js
> +      cardMappings = cardMappings(result);
I think I should remove the `if (typeof cardMappings === 'object') {` check, which might make the code a little cleaner and maybe things should error if your function cardMappings doesn't return an object?

2020-03-02 19:58 UTC, oshi97 commented on src/ui/components/cards/accordioncardcomponent.js
> +    const toggleEl = DOM.query(this._container, '.yxt-AccordionCard-toggle');
ah ok makes sense

2020-03-02 19:58 UTC, oshi97 commented on src/ui/components/cards/accordioncardcomponent.js
> +    iconEl.classList.toggle('yxt-AccordionCard-icon-expanded');
updated!

2020-03-02 19:58 UTC, oshi97 commented on src/ui/components/cards/accordioncardcomponent.js
> +    this.isExpanded = false;
updated!

2020-03-02 21:24 UTC, oshi97 commented on src/ui/sass/modules/_AccordionCard.scss
> +.yxt-Card
updated so that it uses .yxt-AccordionCard--{{index}} selectors

2020-03-03 20:03 UTC, closed without merging

2020-03-03 20:13 UTC, oshi97 commented
Sorry I didn't realize this would close when I deleted vr/qa