custom map pin support for mapbox
yext/answers-search-ui pull request #70
Opened 2019-07-17 14:30 UTC by aginsberg

2019-07-17 14:31 UTC, Delerme reviewed
looks fine to me, will let billy take a look and approve

2019-07-17 20:47 UTC, b1lly requested changes
Nice. The implementation looks sound, but i'd like to clean up the code a little bit by separating some of the concerns while we're here, and add some tests if possible. 

I think by encapsulating the configuration logic into a configuration model it'll make the implementation cleaner and easier to extend in the future.

Also, important for tests ;)

2019-07-17 20:47 UTC, b1lly commented on src/ui/components/map/providers/mapboxmapprovider.js
>        if (mapData && mapData.mapMarkers.length > 0) {
I know you didn't write this, but this check shouldn't be needed anymore (since it already gets short circuited up at the top of init).

2019-07-17 20:47 UTC, b1lly commented on src/ui/components/map/providers/mapboxmapprovider.js
> +          if (pinConfig && typeof pinConfig === 'function') {
Do you want to pull the configuration stuff out into a separate class, similar to what we did for google?

Basically, create a MapBoxConfig model that represents the configuration for MapBox, using our configuration format as input?

Then we can use those objects to create the map using the mapbox api, as well as add some tests.

Thoughts?

2019-07-18 13:20 UTC, aginsberg commented on src/ui/components/map/providers/mapboxmapprovider.js
> +          if (pinConfig && typeof pinConfig === 'function') {
Sounds good to me! I'll try and get something out later today/tomorrow

2019-07-18 16:54 UTC, b1lly approved these changes
Savage! LGTM

2019-07-18 16:57 UTC, merged