templates: Add new AccordionResult template
yext/answers-search-ui pull request #79
Opened 2019-07-22 20:33 UTC by benmcginnis

Adds new AccordionResult template and updates UniversalResults to respond to
a new "useAccrdion" VerticalResult config property, which will cause the
Vertical to use the AccordionResult component instead of the standard
Results component.

2019-07-23 14:05 UTC, Delerme commented
Sweet, can you add JSDoc comments to the AccordionResultsComponent class and all of its methods

2019-07-30 16:23 UTC, b1lly requested changes
A few minor styling nits, and then a structural comment about using local state instead of the DOM for the collapsed state.

2019-07-30 16:23 UTC, b1lly commented on src/ui/templates/results/resultsaccordion.hbs
> +                <li class="yxt-Accordion-item js-yxt-Accordion-item yxt-AccordionResult{{#if collapsed}} is-collapsed{{/if}}{{#if resultModifier}} yxt-AccordionResult--{{resultModifier}}{{/if}}">
Where does the template get all these states from? Is it provided by the component itself? 'Cause I don't see a setState override anywhere. So not exactly sure where `collapsed` and `resultModifier` etc are coming from.

2019-07-30 16:23 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +const selectorBase = '.js-yxt-Accordion';
I'd bake this into the constructor so that it could be configurable.

2019-07-30 16:23 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +    this._templateName = opts.templateName || 'results/resultsaccordion';
we started adding JS doc to all of our new classes (and ones we modify)

2019-07-30 16:23 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +        this.setupAnimations(accordion, item);
accordianEl, itemEl

2019-07-30 16:23 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +  setupAnimations (accordion, item) {
^

2019-07-30 16:23 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +    item.isCollapsed = item.classList.contains('is-collapsed');
shouldn't this state be part of the result items data instead of the state being attached/retrieved from the DOM? If we triggered a re-render, this wouldn't work.

I think the idea is that the state powers the renderable state.

State -> Render (should know if an item is expanded or collapsed).
Click Handler -> Updated State -> Triggers Re-render.

The way that i'd approach this:
1. During setState, augment each`result` item object with the views stateful 'isCollapsed' property
2. Each `Result` should have an `identifier` that can be referenced. When the template is rendered, the DOM should have this reference somewhere (e.g. data-result-id="1"). The template should also include the class for `collapsed` based on the result state.
3. On click of DOM, it grabs the reference above, uses `getState` and updates the proper `Result` data item based on the reference with the proper collapsed state.
4. Trigger a new setState with the updated data, which will trigger a re-render.

2019-08-23 16:55 UTC, benmcginnis commented on src/ui/components/results/accordionresultscomponent.js
> +    item.isCollapsed = item.classList.contains('is-collapsed');
As we've discussed, I'm concerned about the accessibility impact of destroying and re-rendering the elements on click.  I'd like to move forward with this architecture and perhaps look at migrating to the state based implementation in the future when we have time for thorough screen-reader testing.

2019-08-27 04:17 UTC, creotutar commented on src/ui/templates/results/resultsaccordion.hbs
> +          <div class="yxt-AccordionResult-details">
can we have details on the same line

2019-08-27 04:19 UTC, creotutar commented on src/ui/templates/results/resultsaccordion.hbs
> +          <div class="yxt-AccordionResult-details">
for when we do `white-space: pre-line` so we don't have that beginning newline but preserve the newlines in the text*

2019-09-05 02:02 UTC, benmcginnis commented on src/ui/components/results/accordionresultscomponent.js
> +  _onMount () {
onMount / mount are not currently being called on children components, so I had to override _onMount

2019-09-05 07:10 UTC, b1lly approved these changes

2019-09-05 07:10 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +  constructor (opts = {}) {
we use `config` as the object now, `opts` is legacy pattern.

2019-09-05 07:10 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +  _onMount () {
gotcha. I think @Delerme change in the 0.9.0 version actually resolves this.

2019-09-05 07:10 UTC, b1lly commented on src/ui/components/results/accordionresultscomponent.js
> +  constructor (opts = {}) {
Just need to address this and we're good.

2019-09-05 20:06 UTC, merged