templates: Update DirectAnswers, Results & Result templates
yext/answers-search-ui pull request #80
Opened 2019-07-22 20:34 UTC by benmcginnis

Updates DirectAnswers, Results and ResultsItem templates based on updated
designs. Also adds a new resultssectionheader template to encapsulate
new heading designs.

2019-07-23 05:09 UTC, b1lly reviewed
I think you need the accompany these templates with the proper data models transforms internally. You can look at the core/models for some of this stuff. The goal would be to refactor those to be able to power these templates directly.

Additionally, also, want to talk to you a little bit about the various types of `resultitem` cards and how you see that being powered by configuration. Certainly, we'd have to refactor the component JS to accept the proper configuration, but I'd like to understand what your thinking for this if possible.

Aside, the markup looks good with the minor nit:

Is it possible to switch all the HTML to `2 space tab indent`, instead of 4? This goes for all commits. We should probably add HTML linting to the library builds @Delerme

2019-07-25 00:55 UTC, benmcginnis commented
@b1lly added the basic models here, as we discussed.  Works out of the box for profiles that have a description field as well as GCSE results.

2019-07-31 15:22 UTC, creotutar commented on src/ui/templates/results/directanswer.hbs
> +      {{{answer.value}}}
can we have some answerValue field rather than use the answer.value? that way if a client wants to have a custom value for a specific `answer.fieldApiName`, they won't have to override answer.value and rather can pass it in as a separate attribute? unless we are thinking they shouldn't be spread adding data and instead passing in their own fields

e.g. not
```
transformData {
return {
 ...data
}
}
```

but rather
```
transformData {
return {
 answer: {
   entityName: x
   fieldName: y
   value: something
}
}
}
```

2019-07-31 15:34 UTC, creotutar commented on src/ui/templates/results/directanswer.hbs
> +      {{{answer.value}}}
silly me! you can just do, feel free to ignore

```
transformData {
  return { 
    ...data,
    answer: {...data.answer, value: 'new val'},
  }
}
```

2019-07-31 16:26 UTC, benmcginnis commented on src/ui/templates/results/directanswer.hbs
> +      {{{answer.value}}}
I think your first point is actually right though.  if you see the Results model we move the profile into a _raw field to avoid overwriting any profile fields.  I think we probably want to do that in DirectAnswers too, I just implemented this first and didn't update it in response to the change in Results.js

2019-08-01 20:57 UTC, b1lly requested changes

2019-08-01 20:57 UTC, b1lly commented on src/core/models/result.js
>    }
This is a great start! I think what we're going to want to do here is define our model, and separate the transformation logic so that we can scale the number of incoming models easily.

So:

1. Create the Result data model (this._raw, this.title, this.details, etc) like you did.
2. Using a factory pattern, inspect data and call different transformers to return the Result.

So for instance:

```
ResultFactory {
  /**
    * @returns {Result}
    */
  static from(data) {
    // .. inspect the data and choose different transformers
    if (data.htmlSnippet) {
      return ResultFactory.fromGSCE(data)
    }
  }

  static fromGSCE(data) {
    return Result({ ... })
  }

 static fromLocation(data) {
   return Result({ ... })
  }

 static fromEvent(data) {
   return Result({ ... })
  }
}
```

And then the caller would just do

```
ResultFactory.from(data)
```

That way we can have unit tests for all the transformations in the factory, and scale the variations of input models really easily.

2019-08-01 20:59 UTC, b1lly commented on src/core/models/result.js
>    }
@Delerme Just to collaborate on the thinking here.

2019-08-02 17:29 UTC, benmcginnis commented
@ndawg we also need to rebase this and handle the conflicts

2019-08-02 17:30 UTC, benmcginnis commented on src/core/models/result.js
>    }
@b1lly should we go ahead and delete the LocationResult, EventResult, etc. ?  We can do it in this pr and replace with the result factory.

2019-08-02 17:30 UTC, benmcginnis commented on src/core/models/result.js
>    }
I think right now, we probably can only really do the GSCE result / base result, but we can setup the factory

2019-08-02 18:56 UTC, benmcginnis commented on src/core/models/resultfactory.js
> +      return ResultFactory.fromGeneric(data, index)
you don't need the else

2019-08-02 18:56 UTC, benmcginnis commented on src/core/models/result.js
> +  constructor (data = {}, index) {
i think, with the factory update you can revert this change

2019-08-02 18:56 UTC, benmcginnis commented on src/core/models/result.js
> +      results.push(new Result(resultsData[i].data || resultsData[i], i));
i think you need this to be `ResultFactory.from(resultsData[i].data || resultsData[i], i)`

2019-08-02 18:56 UTC, benmcginnis commented on src/core/models/result.js
> +      results.push(new Result(resultsData[i].data || resultsData[i], i));
or we would need to delete this method

2019-08-02 18:56 UTC, benmcginnis commented on src/ui/components/results/locationresultsitemcomponent.js
> +  static defaultTemplateName () {
this is on a separate PR

2019-08-02 18:57 UTC, benmcginnis commented
Can you also run `npm run fix` on the latest commit?

2019-08-05 21:39 UTC, b1lly commented on src/core/models/result.js
>    }
@benmcginnis Yeah, I think the idea is to delete the individual `entity templates/components` like you suggest, and use a default one based off the core data model (e.g. title, subtitle, etc). This will require us to change some of the logic in the ResultsComponent too.

I think the goal is for the `entity-specific` components/templates to change from being `entity-specific`, to being more 'Layout-specific`.

2019-08-06 14:15 UTC, ndawg commented on src/core/models/result.js
> +      results.push(new Result(resultsData[i].data || resultsData[i], i));
I didn't see `Result.from` being used anywhere, so this method could probably be deleted

2019-08-07 14:17 UTC, ndawg commented
@b1lly I believe all your requested changes have been addressed whenever you're ready to take a look!

2019-08-07 15:13 UTC, b1lly requested changes

2019-08-07 15:13 UTC, b1lly commented on src/core/models/result.js
>      Object.assign(this, data);
instead of using Object.assign(this, data)... can you explicitly define all the core properties about the model here?

For instance,

```
this.title = data.title || 'defaultValue'; // or null if it's default should be null

this.details = data.details || null;

// ... etc
```

2019-08-07 15:13 UTC, b1lly commented on src/ui/templates/results/eventresultsitem.hbs
> +    {{#if callsToAction}}
I don't see this being set as part of the model in any of the factory transformers. Can you please define it in the Result model as well in regard to the other comment I had?

2019-08-07 15:13 UTC, b1lly commented on src/ui/templates/results/eventresultsitem.hbs
> +        {{/if}}
aka

```
{{#if link}}
  <a class="yxt-Result-titleLink" href="{{link}}">{{title}}</a>
{{else}}
  {{title}}
{{/if}} 
```

2019-08-07 15:13 UTC, b1lly commented on src/ui/templates/results/eventresultsitem.hbs
> +    {{#if startDate.day}}
I also don't see this as part of the core model/factory defined above.

2019-08-07 15:13 UTC, b1lly commented on src/ui/templates/results/resultsitem.hbs
> +    {{#if image.url}}
Same comment about all these properties (ordinal, bigDate, image, etc) They all seem to be missing from the core model definition.

2019-08-07 17:22 UTC, benmcginnis commented on src/core/models/result.js
> +    this.callsToAction = data.callsToAction || null;
i think we also want to have the raw profile data here.  So I think in here we should have `this._profile` or `this._raw` like I had before.

2019-08-07 17:22 UTC, benmcginnis commented on src/core/models/resultfactory.js
> +      id: data.id
and here you would pass `profile: data` or `raw: data`

2019-08-07 17:22 UTC, benmcginnis commented on src/ui/components/results/directanswercomponent.js
> +    return 'results/directanswer';
this is on another pr, please remove

2019-08-07 17:22 UTC, benmcginnis commented on src/ui/templates/results/eventresultsitem.hbs
> +    {{#if startDate.day}}
@ndawg you can actually remove the changes to the eventresultsitem.hbs, it's not actually ready for prime time.

2019-08-07 17:22 UTC, benmcginnis commented on src/ui/templates/results/eventresultsitem.hbs
> +    {{#if callsToAction}}
I think right now there is no way for us to generically define a call to action for every profile or even a default profile, other than "View Details" or something similar.  @ndawg can add the `this.callsToaction = null` field for completeness, but I think it's probably a lot more to think about for what the call to action model should look like and how implementors should be able to add them to a result as it's incredibly custom implementation to implementation and entity to entity

2019-08-07 17:22 UTC, benmcginnis commented on src/ui/templates/results/locationresultsitem.hbs
> +<li class="yxt-Result{{#if modifier}} yxt-Result--{{modifier}}{{/if}} yxt-Result-item">
@ndawg you can also reset the changes to this template, it's not ready for prime time.

2019-08-07 17:22 UTC, benmcginnis commented on src/ui/templates/results/resultsitem.hbs
> +    {{#if image.url}}
@ndawg added them though we still need to add `this.image = null`, `this.showOrdinal = false` and `this.callsToAction = []`

2019-08-07 17:24 UTC, benmcginnis commented on src/core/models/resultfactory.js
> +      id: data.id
@b1lly are you still good with this mechanism for preserving access to the raw profile?

2019-08-07 17:58 UTC, benmcginnis commented on src/ui/templates/results/resultsitem.hbs
> +    {{#if image.url}}
@b1lly this should be resolved.

2019-08-07 18:28 UTC, benmcginnis commented on src/ui/templates/results/resultsitem.hbs
> +                {{#if eventOptions}} data-eventoptions='{{eventOptions}}'{{/if}}>
i think these actually need to be `this.eventType` and `this.eventOptions` in order to have the context of the iteration

2019-08-07 21:37 UTC, b1lly requested changes
SUPER close!

Some minor nits, but really liking the outcome :)

2019-08-07 21:37 UTC, b1lly commented on src/core/models/result.js
> +    this.showOrdinal = data.showOrdinal || false;
I think `showOrdinal` is a configuration property and not a data property (it's provided from the component).

You probably want `ordinal` here though, right?

Your template actually should use ``{{#if _config.showOrdinal}}`` I think? @benmcginnis 


Also, would you mind adding JS doc to each of the properties?

2019-08-07 21:37 UTC, b1lly commented on src/core/models/resultfactory.js
> +      id: data.id
Yes, raw is great :)

2019-08-07 21:37 UTC, b1lly commented on src/ui/sass/modules/_Result.scss
> +    padding-bottom: 8px;
aka

`padding: 8px;`

Can you adjust this EVERYWHERE that you're setting padding?

I know this is a little bit of a nit and a micro optimization, but using short hands as much as possible is a good practice for file size optimizations. Over a pretty large code base they can add up.

2019-08-07 21:37 UTC, b1lly commented on src/ui/sass/modules/_Result.scss
> +    padding-bottom: 10px;
aka `padding: 10px;`

2019-08-08 00:51 UTC, benmcginnis commented on src/ui/sass/modules/_Result.scss
> +    padding-bottom: 8px;
So, generally we follow this practice in consulting: https://csswizardry.com/2016/12/css-shorthand-syntax-considered-an-anti-pattern/

We also use cssnano, which I forgot to include in the build tools and one of the things cssnano does is collapse these automatically but it will do the minimum shorthand thereby ensuring we don't accidentally clobber properties by using the short hand.

I've added css nano and the output css is using the short hand.

2019-08-08 16:16 UTC, b1lly requested changes
Just need JSDoc for the main model and we're pretty good ;)

2019-08-08 16:16 UTC, b1lly commented on src/core/models/resultfactory.js
> +      id: data.id
I think this makes sense for generic/default. Is the long term vision to support other entities for the other fields that aren't currently being utilized?

e.g. bigDate, image, etc.

I think they make sense for `events` or `people`. And I think those are the three entities we're planning to launch with. Perhaps we can utilize the `data.type` to know which entity it is to power these fields properly?

2019-08-08 16:16 UTC, b1lly commented on src/core/models/result.js
> +    this.callsToAction = data.callsToAction || [];
just need jsdoc and we're good!

2019-08-08 17:40 UTC, b1lly approved these changes

2019-08-08 19:04 UTC, merged