templates: allow implementors to set config.templateName
yext/answers-search-ui pull request #82
Opened 2019-07-22 20:36 UTC by benmcginnis

config.templateName was defined but not used by any of the Components.  This
changes each component to respect config.templateName if it's defined and if
not, fallback to the default templateName for the Component.  For Components
with multiple allowable templates, this will allow implementors to choose
a variation without overriding the template parameter.

2019-07-22 21:44 UTC, Delerme commented
seems fine to me, to billy

2019-07-23 05:00 UTC, b1lly reviewed
I think this makes sense.

Just an idea: 

One alternative approach could be to update the base `Component` class to do something like:

```
this._templateName = config.templateName || this.constructor.defaultTemplateName() ;
```

And then, the implementation pattern wouldn't be to deal with the configuration for assignment in the constructor. Instead, each subclass would just have to create a static method override like:

```
static defaultTemplateName() {
  return 'search/filtersearch';
}
```

It's the same thing, but I think it abstracts away the `configuration` stuff to that is supposed to be part of the core configuration into the base class, and creates an 'override' pattern to follow. 

Either way works for me, though. Just wanted to see your thoughts here.

2019-07-23 13:48 UTC, benmcginnis commented
That's a lot nicer, updating.

2019-07-23 14:20 UTC, benmcginnis commented
@b1lly updated based on your comment.

2019-07-23 19:48 UTC, b1lly requested changes

2019-07-23 19:48 UTC, b1lly commented on src/ui/components/component.js
> +    this._templateName = opts.templateName || this.constructor.defaultTemplateName();
I just realized you might have to provide `opts` to this.constructor.defaultTemplateName(opts);

There's only one use case thats going to need it (see below).

2019-07-23 19:48 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +  static defaultTemplateName () {
Was this tested, does this work? If it does, i'd be surprised, since `this` should be pointing at the class object and not the instance object... But if its magically working then great,  can ignore what I say below.


If its not working we need to do what I suggested above and:

```
static defaultTemplateName (config) {
  return `controls/${config.control}`
}
```

Unless you got a better idea?

2019-08-08 20:27 UTC, b1lly approved these changes

2019-08-08 20:38 UTC, merged