Static mapbox custom markers
yext/answers-search-ui pull request #84
Opened 2019-07-23 14:54 UTC by aginsberg

2019-07-23 19:50 UTC, b1lly requested changes
Nice job!

2019-07-23 19:50 UTC, b1lly commented on tests/ui/components/map/providers/mapboxmapprovider.js
> +    })];
Is this not the same as:

```
const markers = MapBoxMarkerConfig.from([{
  map: map,
  position: { ... }
  // ... etc
},
{
  map: map,
  position: { ... }
}]
```

2019-07-23 19:55 UTC, aginsberg commented on tests/ui/components/map/providers/mapboxmapprovider.js
> +    })];
Not sure I understand, in the case of the first marker, it doesn't need the label since it's using a url for the marker image. In the second one, it's using the marker's label as part of the encoded marker, i.e. the expected output from this test is 'url-https%3A%2F%2Fimg.png(45,44),pin-s-2(31,30)', the 'pin-s-2' is using the label for the 2.

2019-07-25 16:11 UTC, b1lly commented on tests/ui/components/map/providers/mapboxmapprovider.js
> +    })];
I'm saying the way that you're constructing your list of MapBoxMarkerConfigs can be done more simply by using the .from() method and passing it the array of object literals.

2019-07-25 16:45 UTC, aginsberg commented on tests/ui/components/map/providers/mapboxmapprovider.js
> +    })];
Ah I see, I'll change this

2019-07-26 19:05 UTC, b1lly approved these changes

2019-07-26 19:06 UTC, merged