Set babel target to ie11, refactor and add polyfills
yext/answers-search-ui pull request #85
Opened 2019-07-23 19:24 UTC by Delerme

2019-07-23 19:53 UTC, b1lly requested changes
Lets remove all polyfilling, but keep the merge object change for now.

2019-07-23 19:53 UTC, b1lly commented on .babelrc
> +  ]
Lets remove all the polyfilling for now.

Keep the merge change, though.

2019-07-30 15:47 UTC, b1lly commented
Should I close this PR?

2019-07-30 15:48 UTC, Delerme commented
Yup, I got it

2019-07-30 15:48 UTC, closed without merging