adding filter reset option to FiltersBoxComponent
yext/answers-search-ui pull request #86
Opened 2019-07-24 16:10 UTC by aginsberg

2019-07-25 15:02 UTC, Delerme requested changes
any template changes needed?

2019-07-25 15:02 UTC, Delerme commented on src/ui/components/filters/filterboxcomponent.js
> +        for (const option of filterComponent._options) {
this shouldn't access filterComponent's private properties, instead have filterOption.clear() do all the necessary clearing it should do, so move this there

2019-07-31 16:11 UTC, b1lly requested changes

2019-07-31 16:11 UTC, b1lly commented on src/ui/components/filters/filterboxcomponent.js
> +    this._search();
I don't think clearFilters should be automatically triggering a search. I think that should be a decision made by the code that's calling to clear filters. For instance, what if someone wanted to clear the filters, select a few other things, and then search? By separating them, you're able to reuse this method and just re-implement a new caller,.

This should be part of the resetButton handler. I feel LESS strongly about decoupling the saving of filters with the clear action, but ultimately i'm leaning towards also making that the responsibility of the caller.

For instance, the code should be more:

```
DOM.on(resetButton, 'click', () => {
  this._clearFilters();
  this._saveFiltersToStorage();
  this._search();
});

2019-07-31 16:11 UTC, b1lly commented on src/ui/templates/filters/filterbox.hbs
> +        {{/if}}
@Delerme do we want to figure out a pattern for defaulting data values? Right now we'd just override setState, so that we wouldn't need to do this type of checking in the template. I think if ``{{title}}`` defaulted to a `Filters in the component, that probably would be a better approach to this?

That would also give the component the flexibility of a configuration option to override it.

2019-08-08 20:32 UTC, b1lly requested changes
Please rebase this properly so the review doesn't include other peoples commits.

2019-08-16 13:17 UTC, aginsberg commented
@b1lly Is there anything else I can do here? I believe I addressed all the requested changes, but please let me know if I missed anything.

2019-09-30 15:43 UTC, b1lly commented
What is the deal with this? is this something that is still needed? Is it dead? can I close it? Should we figure out how to merge it in?

2019-10-02 16:32 UTC, b1lly commented
I'm going to close this, if no response @benmcginnis @aginsberg

2019-10-02 16:36 UTC, benmcginnis commented
Hey @b1lly sorry this slipped my mind.  We probably do need a solution to this in the library for WCAG reasons, but we can probably close this PR, I think it needs more thinking from UX.

2019-10-02 16:36 UTC, closed without merging