Prevent duplicate searches in core
yext/answers-search-ui pull request #94
Opened 2019-07-25 14:36 UTC by Delerme

2019-07-25 16:01 UTC, b1lly requested changes

2019-07-25 16:01 UTC, b1lly commented on src/core/core.js
>    }
I actually think that this behavior should be prevented in the UI library instead of the core.

2019-07-25 16:01 UTC, b1lly commented on src/core/core.js
> +    if (input === this._lastSearch.query) {
As a note, I'm not sure we care about restricting the auto complete behavior. We certainly can, but I don't think its really necessary.

2019-07-25 16:52 UTC, Delerme commented on src/core/core.js
> +    if (input === this._lastSearch.query) {
Yea figured it didn't really matter either way, but may as well

2019-07-25 16:53 UTC, Delerme commented on src/core/core.js
>    }
hmm it seems better to prevent it at the core level, I don't think we want ill-configured components or templates to ever spam the api with duplicate requests

2019-07-29 18:46 UTC, b1lly requested changes

2019-07-29 18:46 UTC, b1lly commented on src/ui/components/search/searchcomponent.js
> +    this._searchCooldown = opts.searchCooldown || 1000;
do we want to rename opts = config while we're here? Also, I think 1 second is too long. Lets start with like 200-300ms

2019-07-29 18:59 UTC, Delerme commented on src/ui/components/search/searchcomponent.js
> +    this._searchCooldown = opts.searchCooldown || 1000;
yea may as well. Changed to 300

2019-07-29 19:39 UTC, b1lly approved these changes
Might need to update the readme too, to say its default is 300ms not 1s

Otherwise LGTM

2019-07-29 19:48 UTC, merged