Filter options
yext/answers-search-ui pull request #96
Opened 2019-07-25 14:39 UTC by aginsberg

2019-07-25 14:46 UTC, Delerme requested changes
any template changes needed?

2019-07-25 14:46 UTC, Delerme commented on src/ui/components/filters/filteroptionscomponent.js
> +     * The label to br used in the legend
typo

2019-07-25 14:48 UTC, aginsberg commented on src/ui/components/filters/filteroptionscomponent.js
> +     * The label to br used in the legend
oops, will fix
I can include the template change in this cr as well

2019-07-25 14:57 UTC, Delerme requested changes

2019-07-25 14:57 UTC, Delerme commented on src/ui/templates/controls/multioption.hbs
> +    {{else}}
I'd probably remove the if/else logic if label is always expected to be defined

2019-07-25 14:58 UTC, aginsberg commented on src/ui/templates/controls/multioption.hbs
> +    {{else}}
Good point, will remove

2019-07-25 15:00 UTC, Delerme commented
lgtm, to billy

2019-07-25 15:57 UTC, b1lly requested changes

2019-07-25 15:57 UTC, b1lly commented on src/ui/components/filters/filteroptionscomponent.js
> +    console.log(config)
woops

2019-07-25 16:10 UTC, aginsberg commented on src/ui/components/filters/filteroptionscomponent.js
> +    console.log(config)
This has been removed!

2019-07-26 15:24 UTC, b1lly approved these changes
nice job.

2019-07-26 15:26 UTC, merged